### ISSUE TITLE
How can I change display language of date and hour format?

### ISSUE THREAD

**Issue by MagicFab** [Freeyourgadget/Gadgetbridge#682] opened 2017-05-08 19:22 UTC
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

How can I change the display language and format for the hour? I would like to specify a 24h format and French/Spanish for date display (day of week abbreviation and month names)

Is this possible?

Current software/hardware:

*MiBand 2 wit 1.0.1.39 firmware and font file
* LineageOS, Android 7.1.2
* GadgetBridge 0.19.1

**Comment by cpfeiffer** [comment] 2017-05-11 22:24
We actually check the system setting of the time format and use the same for the band. If your phone is set to 24h format, there's something wrong.

For the language, I honestly have no idea. Do you know if it is possible to change the language with Mi Fit?

**Comment by MagicFab** [comment] 2017-05-12 13:56
> We actually check the system setting of the time format and use the same for the band. If your phone is set to 24h format, there's something wrong.

I noticed it's using 24h, not sure if it's linked to OS as you indicate, thanks for the hint.

> For the language, I honestly have no idea. Do you know if it is possible to change the language with Mi Fit?

I have no clue, I assumed it coud be done.

**Comment by cpfeiffer** [comment] 2017-05-14 21:16
So, is the 12h/24h time format properly linked to your mobile's time format or doesn't this work? I don't want to make this configurable since we already have so many options.

Regarding a language change -- if you find out that this is possible, we need a btsnoop in order to reproduce the behavior.

In summary, I assume that all works as it should, so I'll close this issue. If something does not work as it should, feel free to reopen it.

**Closed by cpfeiffer** 2017-05-14 21:16 UTC
Labels: device mi2, documentation
