### ISSUE TITLE
hplus (zeband plus)

### ISSUE THREAD

**Issue by dawiddudek** [Freeyourgadget/Gadgetbridge#660] opened 2017-04-20 08:24 UTC
Hi, I buy Hplus (zeband) and install GB. I have a problem with notification. All notification is in chanise font.
Hplus app all notification show in latin font.

I use latest GB 0.18.5
Zeband plus (Hplus)
OnePlus 3 Android 7.0

I install debug 630 from https://github.com/Freeyourgadget/Gadgetbridge/issues/630 but it is that same problem with space between font/

Why? What i can do? In GB i check transliteration (or something like that) and is nothing happen.
![img_20170420_102018](https://cloud.githubusercontent.com/assets/27805071/25220850/639ef708-25b3-11e7-8b27-e445abcc0ba3.jpg) notification form Hplus app
![img_20170420_101023](https://cloud.githubusercontent.com/assets/27805071/25220875/7820aea6-25b3-11e7-9271-adb51300c546.jpg) notification from GadgetBridge app

**Comment by ashimokawa** [comment] 2017-04-20 11:32
Seems to be a duplicate of #630 then, is there a reason you opened a new issue?

**Comment by dawiddudek** [comment] 2017-04-20 13:05
I search but don't found first time. If I search manual i found issu #630. sorry
But this sugest it's not work.
I have a latest version 0.18.5

**Comment by ashimokawa** [comment] 2017-04-20 13:33
@dawiddudek 
Yes, thank you for reporting, the original reporter had given his Band to someone else, that's why @jpbarraca could not look into the issue further. Maybe the best would be if you could capture bluetooth hci dumps with the original app and working non-chinese notifications.
See https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files and report to #630 please.
I will close this one as duplicate.

**Closed by ashimokawa** 2017-04-20 13:33 UTC
Labels: duplicate
