### ISSUE TITLE
MI band - Deep sleep vs Light sleep.

### ISSUE THREAD

**Issue by geripgeri** [Freeyourgadget/Gadgetbridge#257] opened 2016-03-16 09:30 UTC
Hi,
I'm correctly using v0.8.2 with MI Band fw: 1.0.10.11.

With **older fw** and with **Mi fit** application my sleep was like 

Total | Deep | Light
--- | --- | ---
08:16 | 03:16 (40%) | 05:00 (60%)

**With GB:**

Total | Deep | Light
--- | --- | ---
08:17 | 07:10 (86%) | 01:07 (14%)

I think the first data seems legit. What could be the problem?

**Comment by danielegobbetti** [comment] 2016-03-16 22:27
There are two separate issues at play here, I believe.

first: we may get deep and shallow sleep inverted. unfortunately we get mixed reports about this :(
second: we show the data as we get them from the miband. the official app does some post processing that we don't know how to replicate.

help is much appreciated, you'll find some pointers in other issues (we'll merge this issue into another one soon btw)

**Comment by danielegobbetti** [comment] 2016-03-16 22:28
duplicate of #250

**Closed by danielegobbetti** 2016-03-16 22:28 UTC
Labels: duplicate, mi band
