### ISSUE TITLE
Mi Band 2 Firmwares thread

### ISSUE THREAD

**Issue by Jojonintendo** [Freeyourgadget/Gadgetbridge#477] opened 2016-12-29 13:22 UTC
Hello everyone!

I received my Mi Band 2 yesterday and I noticed in the wiki, only 1.0.0.39 is recommended. However I couldn't bind the Mi Band, so I had to update the firmware through the MiFit app. After unbinding from MiFit, I could finally make it work in GadgetBridge. Now the band information is this: HW: V0.1.3.2, FW: V1.0.1.28.

I have already tested every option I know about: alarms, live activity, synchronizing activity, heartrate measure (even when sleeping), and notifications. Everything seems to work great. I don't know if there is another way to tell you, developers, if a firmware version works or not, so I though this thread could do it.

If you think this is a good idea, then I think it would be great if any other Mi Band 2 user would report their firmware version, and what works, etc. This way we can keep track of latest updates, at least the most adventurous of us 😄.

Also, on another note, I couldn't flash latest firmware from the apk, the "Mili_pro.fw" wouldn't be sent to the band. I didn't try flashing other files (like "Mili_pro_53.fw" or "Mili_pro_tph.fw") because I don't know if this could brick the device.

Thanks to the developers for their great work, keep going!

**Comment by 6arms1leg** [comment] 2016-12-29 13:55
Great, I added your provided firmware information to the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Information).
I think what would really help the developers is a confirmed firmware upgrade with GB and the GB FW installer nr. + md5sum, so they can whitelist it in the app and other users can install the same file.
But GB doesn't show the installer nr. upon installation for Mi Band 2 FW and also the different FW files for the Mi Band 2 in newer APKs are confusing. Does anyone knows the difference between the *Mili_pro\*.fw* files?

**Comment by cpfeiffer** [comment] 2016-12-29 22:40
I don't know how to programmatically determine the firmware version for a Mili_pro.fw file, yet. So at the moment we simply hardcode some kind of hashcode of all well-known and working firmware versions.

So yes, reporting how well (or not) a specific version works is very much appreciated.

There have been several reports on the 'net that 1.0.0.39 was the last version that reliably supported heart rate measurements. Newer versions apparently could not measure when there was too much hair on the wrist or the skin color was not bright enough.

So we need some confirmations for version 1.0.1.28 from people who had problems with other firmware versions.

**Comment by cpfeiffer** [comment] 2016-12-29 22:42
I don't know the difference between Mili_pro.fw and Mili_pro_53.fw, sorry. If anyone finds out, please tell us!

Also, if you have a log of a non-working firmware update, please share it, so we can try to fix that.

**Comment by Jojonintendo** [comment] 2016-12-29 22:50
Ok, here is the log when trying to upload latest Mili_pro.fw to the device:

23:44:39.105 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.15.2
23:44:44.321 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
23:44:44.326 [main] WARN  n.f.g.i.GBDeviceCandidate - no cached services available for MI Band 2: F4:48:FD:9C:6E:C6
23:44:44.365 [main] WARN  n.f.g.i.GBDeviceCandidate - no cached services available for MI Band 2: F4:48:FD:9C:6E:C6
23:44:44.380 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
23:44:46.086 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.install
23:44:46.086 [main] INFO  n.f.g.s.DeviceCommunicationService - will try to install app/fw
23:44:46.087 [main] INFO  n.f.g.i.GBDevice - Mark device as busy: Operation starting...
23:44:46.088 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 11:44:46 PM: Transaction task: disabling some notifications with 1 actions
23:44:46.100 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 11:44:46 PM: Transaction task: send firmware info with 2 actions
23:44:46.115 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 29 décembre 23:44: NotifyAction on characteristic: 00001531-0000-3512-2118-0009af100700
23:44:46.127 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.NotifyAction - use NOTIFICATION
23:44:46.947 [Binder_4] DEBUG n.f.g.s.b.BtLEQueue - descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
23:44:46.950 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 29 décembre 23:44: nodomain.freeyourgadget.gadgetbridge.service.btle.actions.SetDeviceBusyAction: Mise à jour du micrologiciel...
23:44:46.951 [Gadgetbridge GATT Dispatcher] WARN  n.f.g.i.GBDevice - Attempt to mark device as busy with: Mise à jour du micrologiciel..., but is already busy with: Operation starting...
23:44:46.951 [Gadgetbridge GATT Dispatcher] INFO  n.f.g.i.GBDevice - Mark device as busy: Mise à jour du micrologiciel...
23:44:46.957 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 29 décembre 23:44: WriteAction on characteristic: 00001531-0000-3512-2118-0009af100700
23:44:46.959 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 00001531-0000-3512-2118-0009af100700: 0x 1 0x 0 0xc0 0x 3
23:44:46.984 [main] WARN  n.f.g.i.GBDeviceCandidate - no cached services available for MI Band 2: F4:48:FD:9C:6E:C6
23:44:47.009 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
23:44:47.984 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00001531-0000-3512-2118-0009af100700 value:  0x10 0x1 0x4
23:44:47.985 [Binder_1] ERROR n.f.g.s.d.m.o.UpdateFirmwareOperation - Unexpected notification during firmware update: 
23:44:47.985 [Binder_1] INFO  n.f.g.s.d.m.MiBand2Support - RECEIVED DATA WITH LENGTH: 3
23:44:47.985 [Binder_1] WARN  n.f.g.s.d.m.MiBand2Support - DATA: 0x10
23:44:47.985 [Binder_1] WARN  n.f.g.s.d.m.MiBand2Support - DATA: 0x 1
23:44:47.985 [Binder_1] WARN  n.f.g.s.d.m.MiBand2Support - DATA: 0x 4
23:44:47.986 [Binder_1] ERROR n.f.g.u.GB - Problème avec le transfert de métadonnées du micrologiciel
23:44:47.986 [Binder_1] INFO  n.f.g.s.d.m.o.UpdateFirmwareOperation - Operation done.
23:44:47.986 [Binder_1] INFO  n.f.g.i.GBDevice - Mark device as NOT busy anymore: Mise à jour du micrologiciel...
23:44:47.987 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - about to add: 11:44:47 PM: Transaction task: reenabling disabled notifications with 1 actions
23:44:47.988 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 00001531-0000-3512-2118-0009af100700 (success)
23:44:47.989 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 29 décembre 23:44: NotifyAction on characteristic: 00001531-0000-3512-2118-0009af100700
23:44:47.991 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.NotifyAction - use NOTIFICATION
23:44:48.016 [main] WARN  n.f.g.i.GBDeviceCandidate - no cached services available for MI Band 2: F4:48:FD:9C:6E:C6
23:44:48.062 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
23:44:49.026 [Binder_4] DEBUG n.f.g.s.b.BtLEQueue - descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
23:44:51.321 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.install
23:44:51.322 [main] INFO  n.f.g.s.DeviceCommunicationService - will try to install app/fw
23:44:51.322 [main] INFO  n.f.g.i.GBDevice - Mark device as busy: Operation starting...
23:44:51.323 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 11:44:51 PM: Transaction task: disabling some notifications with 1 actions
23:44:51.324 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 29 décembre 23:44: NotifyAction on characteristic: 00001531-0000-3512-2118-0009af100700
23:44:51.327 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.NotifyAction - use NOTIFICATION
23:44:51.332 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 11:44:51 PM: Transaction task: send firmware info with 2 actions
23:44:52.666 [Binder_2] DEBUG n.f.g.s.b.BtLEQueue - descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
23:44:52.669 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 29 décembre 23:44: nodomain.freeyourgadget.gadgetbridge.service.btle.actions.SetDeviceBusyAction: Mise à jour du micrologiciel...
23:44:52.670 [Gadgetbridge GATT Dispatcher] WARN  n.f.g.i.GBDevice - Attempt to mark device as busy with: Mise à jour du micrologiciel..., but is already busy with: Operation starting...
23:44:52.671 [Gadgetbridge GATT Dispatcher] INFO  n.f.g.i.GBDevice - Mark device as busy: Mise à jour du micrologiciel...
23:44:52.681 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 29 décembre 23:44: WriteAction on characteristic: 00001531-0000-3512-2118-0009af100700
23:44:52.682 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 00001531-0000-3512-2118-0009af100700: 0x 1 0x 0 0xc0 0x 3
23:44:52.690 [main] WARN  n.f.g.i.GBDeviceCandidate - no cached services available for MI Band 2: F4:48:FD:9C:6E:C6
23:44:52.713 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
23:44:53.705 [Binder_2] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00001531-0000-3512-2118-0009af100700 value:  0x10 0x1 0x4
23:44:53.706 [Binder_2] ERROR n.f.g.s.d.m.o.UpdateFirmwareOperation - Unexpected notification during firmware update: 
23:44:53.706 [Binder_2] INFO  n.f.g.s.d.m.MiBand2Support - RECEIVED DATA WITH LENGTH: 3
23:44:53.706 [Binder_2] WARN  n.f.g.s.d.m.MiBand2Support - DATA: 0x10
23:44:53.706 [Binder_2] WARN  n.f.g.s.d.m.MiBand2Support - DATA: 0x 1
23:44:53.706 [Binder_2] WARN  n.f.g.s.d.m.MiBand2Support - DATA: 0x 4
23:44:53.707 [Binder_2] ERROR n.f.g.u.GB - Problème avec le transfert de métadonnées du micrologiciel
23:44:53.707 [Binder_2] INFO  n.f.g.s.d.m.o.UpdateFirmwareOperation - Operation done.
23:44:53.707 [Binder_2] INFO  n.f.g.i.GBDevice - Mark device as NOT busy anymore: Mise à jour du micrologiciel...
23:44:53.708 [Binder_2] DEBUG n.f.g.s.b.BtLEQueue - about to add: 11:44:53 PM: Transaction task: reenabling disabled notifications with 1 actions
23:44:53.709 [Binder_2] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 00001531-0000-3512-2118-0009af100700 (success)
23:44:53.720 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 29 décembre 23:44: NotifyAction on characteristic: 00001531-0000-3512-2118-0009af100700
23:44:53.724 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.NotifyAction - use NOTIFICATION
23:44:53.739 [main] WARN  n.f.g.i.GBDeviceCandidate - no cached services available for MI Band 2: F4:48:FD:9C:6E:C6
23:44:53.770 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
23:44:55.266 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
23:45:43.574 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
23:45:43.574 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
23:45:43.615 [main] WARN  n.f.g.i.GBDeviceCandidate - no cached services available for MI Band 2: F4:48:FD:9C:6E:C6
23:45:43.626 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true

**Comment by cpfeiffer** [comment] 2016-12-29 23:23
Thanks for the log. Maybe the firmware is larger than the previous ones and needs special handling. It answers 0x10, 0x1, 0x4 after we tell the firmware size. We expect 0x10,0x1,0x1.

Needs more investigations with a Mi Fit hcidump.

**Comment by Jojonintendo** [comment] 2016-12-30 11:12
Here goes the btsnoop. I hope it is useful!
[btsnoop_hci.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/678562/btsnoop_hci.zip)

**Comment by killkimo** [comment] 2016-12-30 12:20
Mili_pro.fw- new firmware , Mili_pro_53.fw- old 53 firmware, Mili_pro_tph.fw- bad firmware ban is broken!!!!

**Comment by cpfeiffer** [comment] 2016-12-30 16:40
So the tph version is a good one that we can use with any mi band 2? Should we recommend to use that one over  Mili_pro.fw?

**Comment by 6arms1leg** [comment] 2016-12-30 16:53
@cpfeiffer, well

> Mili_pro_tph.fw- bad firmware ban[d] is broken!!!!

sounds more like we shouldn't use that one at all.
@killkimo, were did you get the information? Did you actually try them all (and bricked your device with the last one)?

**Comment by cpfeiffer** [comment] 2016-12-30 17:18
Or the "ban of the (previous) bad firmware is broken". I recall people complaining about heart rate measurement problems with recent fw versions.

**Comment by 6arms1leg** [comment] 2016-12-30 17:30
Ah OK :bulb: 
Thought it was a typo...

**Comment by Jojonintendo** [comment] 2016-12-30 18:14
I tried a few things. In the following btsnoop you'll see this:

1- I tried to flash "53" firmware. It seems to begin well (the band shows the up arrow), but then it fails, and I have to force close GB.
2- I reconnect the band.
3- I try to flash "tph" firmware, which fails right away, the band doesn't even need to reconnect.

[btsnoop_hci_53_tph.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/679043/btsnoop_hci_53_tph.zip)

**Comment by 6arms1leg** [comment] 2016-12-30 18:43
BTW, do you have a "real" 24h clock on your Mi Band 2? I only have a 12h clock but without AM/PM indication (FW v1.0.0.39), which I find rather annoying.
I wonder if this is FW related or whether there is a (hidden) option somewhere, that I haven't yet found. I have seen devices with a 24h clock...

**Comment by Jojonintendo** [comment] 2016-12-30 18:47
Yes, I have a 24h clock set. But I had to use the official Mi Fit app first, to upgrade to latest firmware and then connect to GB. Within Mi Fit I set the band the way I like, so I guess it remained this way with GB. Now you say it, I don't see any option to change time format between 12H/24H.

**Comment by killkimo** [comment] 2016-12-30 19:43
I tried them all and only the Mili_pro.fw file is good for us  /I'm sorry for my bad english/

**Comment by killkimo** [comment] 2016-12-30 19:45
the caller's number is displayed to you?

**Comment by Jojonintendo** [comment] 2016-12-31 12:28
@killkimo: do you mean the band can show the phone number calling you? I'm not even sure it has enough space to do so :D

I did aome tests about heart rate measure, and in my situation it just works perfect. I almost never get an error. I tried measuring from some distance of the wrist (like half a cm) and it still works. It seems the band tries to calibrate the light intensity that is required (it flashes very fast), and then the light is stable and measuring. Also the battery life seems awesome so far. I used it 3 days and 3 nights (with hr measures), with alarm, notifications and some manual hr measures, and it still has 90% of battery.

Oh and latest GB is awesome! Great work!

**Comment by 6arms1leg** [comment] 2016-12-31 15:59
> Yes, I have a 24h clock set. But I had to use the official Mi Fit app first, to upgrade to latest firmware and then connect to GB. Within Mi Fit I set the band the way I like [...]

@Jojonintendo, just to make sure I understand correctly:
For the 24h clock to work you had to do both, upgrading the firmware *and* enable it in the Mi Fit app?

**Comment by Jojonintendo** [comment] 2016-12-31 16:07
When I received the band, the hour was correct, but set to 12H. I could not manage to bind it to GB, so I installed MiFit. From there I could update it, and the hour in the app was automatically set to 24H, so the band got also set to 24H. I guess MiFit detects the setting from your phone, and applies it.

I don't know if updating the firmware is strictly necessary, but I had to do it to bind the device with GB. And this firmware works very good anyway. I hope I explained well, english is not my main language :)

**Comment by 6arms1leg** [comment] 2016-12-31 16:12
> @killkimo: do you mean the band can show the phone number calling you? I'm not even sure it has enough space to do so :D

@Jojonintendo, yes, I heard about that feature, too. The Mi Band 2 with new firmware can display the last three digits of a caller's number. IMO a totally useless feature though. In the age of smart phones who still memorizes telephone numbers? On my mobile, only names are shown. I wouldn't recognize anyone's number, let alone from the last three digits only. I don't even know my own mobile number.
Oh well, maybe others find it usefull...

**Comment by cpfeiffer** [comment] 2016-12-31 17:06
@Jojonintendo Thanks for the btsnoops, will have a look next year :-)

12h or 24h mode is probably configurable in Mi Fit. We do not have an option for this yet (as usual, btsnoops welcome, but please in a separate ticket.

**Comment by Jojonintendo** [comment] 2017-01-01 12:49
@6arms1leg Oh, that could be cool. Although I would prefer to see the contact name, or part of it.

@cpfeiffer I'm about to open a bunch of feature requests with according btsnoops right now :D.

**Comment by walkjivefly** [comment] 2017-01-01 17:32
I have 2 MiBand 2. Both report HW v0.1.3.2, one has FW v1.0.1.28, one has FW v1.0.0.34.
So far I've been using the 1.0.1.28 with MiFit. When I first connected it it gave me a settings screen which I haven't seen since. That let me choose 24 hour clock format and configure which displays (time/steps/distance/calories/HR/battery) are available. 10 days later my battery is still showing 74%. 
I get SMS and phonecall notifications on the band, they display the caller name from my contacts.

Gadgetbridge can connect to the 1.0.1.28 band at the same time as MiFit but loses the connection quite often. 
 
I haven't connected the 1.0.1.34 to MiFit yet or configured the display sequence but Gadgetbridge can talk to it.

I'm hoping to be able to contribute to the project but have a bit of a learning curve to overcome first: Android/Java development in general, AndroidStudio, bluetooth, BTLE & GATT, collecting and reading BT traces, Git and Github, etc.

**Comment by 6arms1leg** [comment] 2017-01-04 15:25
Hello @bluuub,

> I actually bought the thing only because I knew Gadgetbridge was around. Using it with the MI Fit app was (and still is) no option for me because of privacy concerns.

Same here. :+1: 

> [...] and after a few days the HR measurment refused to work (it seems to be a common problem).

Yes, I had the same issue. A firmware upgrade fixed it for me.

> 2. As @walkjivefly pointed out already the connection between the phone and the band is unstable [...]
> This did not happen with the fw the band originally came with but happens with both 1.0.0.39 and 1.0.1.28.

I can also confirm this issue. I'm on FW v1.0.0.39, but actually also had this problem with my old FW (v1.0.0.19).

> 3. [...] Band and app show different steps counters. The band is higher all the time.

Yes, [others also reported this porblem](https://github.com/Freeyourgadget/Gadgetbridge/issues/323#issuecomment-264134065) (#323). I have it, too. Since the last GB update (where #478 was fixed) it improved a lot – I now only observe small deviations in displayed steps between the Mi Band 2 and GB.

We should probably open seperate tickets for points 2. and 3. ...

**Comment by Jojonintendo** [comment] 2017-01-04 19:52
In my case, the step count of the band and GB are always exactly the same. Maybe I just got lucky :p.

But yes, the connection is sometimes unreliable.

**Comment by bluuub** [comment] 2017-01-04 21:18
Interesting that the step counter is so unreliable. Which fw version do you use @Jojonintendo? Maybe they updated the way the MI band is communicating the value (atleast that is the only reason I can think of - I have no clue how it actually works at this point though so it is just a guess).

**Comment by Jojonintendo** [comment] 2017-01-04 21:30
I'm using the latest one, 1.0.1.28, updated from Mi Fit, because GB couldn't flash it.

**Comment by bluuub** [comment] 2017-01-04 23:02
That is really awkward. I just checked: HW version is 0.1.3.2, yours?

**Comment by Jojonintendo** [comment] 2017-01-04 23:03
Same here, it seems to be the latest.

**Comment by bluuub** [comment] 2017-01-04 23:45
Well that is weird. At this point we should maybe open up an issue (if there is none already). Either the app is misreading the transferred value or the MI band is transferring the wrong value?

**Comment by walkjivefly** [comment] 2017-01-05 16:32
@cpfeiffer Thanks for the welcome. I think the ride is going to be a marathon rather than a sprint.

**Comment by cpfeiffer** [comment] 2017-01-05 20:40
Marathon's are most fun when there's lots of people :-)

**Comment by bluuub** [comment] 2017-01-07 21:53
> The band reports wrong activity data to the app or the app misinterprets it. Band and app show different steps counters. The band is higher all the time. The missing data is not added if one waits a few minutes. This happens with both fw versions as well. The heart reate measurments seem to be synchronized very well though.

Well it turns out it was just my bad. My fdroid somehow didn't suggest the update to GB version 0.16 (it wasn't even showing in the version list), although auto updates were turned on. Therefore I was sitting on 0.15.2 the whole time. As @6arms1leg pointed out correctly the issue I was referring too has already been updated in #478. After updating to GB version 0.16 my activity data is in perfect sync. Sorry for the useless confusion.

**Comment by Jojonintendo** [comment] 2017-01-08 13:04
I too see some small deviation when I have more than 10000 steps, GB showed something like 20 more or less steps than the band. Not something to worry about, but you can open another issue.

**Comment by cpfeiffer** [comment] 2017-01-08 22:34
@bluuub Thanks for letting us know!

**Comment by Bydgew7** [comment] 2017-01-10 23:45
* Received MiBand2 with HW 0.1.3.2 and FW 1.0.0.34.
* Using GB from F-Droid: Version 0.16.0, added on 2016-12-30.
* Could bind to GB. Quick test (Sync data, set time, set alarm, incoming call) fine.
* Update to 1.0.1.28 (Mili_pro.fw from APK 2.2.9; MD5 of .fw: 804903543b7958c1b4f9b5c0e420bcb5 ; GB whitelist code: 32450) failed consistently ("Error transmitting metadata" or similar).
* Had a look inside Mili_pro_53.fw (from same APK, MD5 of .fw: abdd122897234f40b556f775ba0b9dc2 ; GB whitelist code: 49197). Appeared to be MiBand2 firmware version 1.0.0.53. Flashed it; worked fine. Had to repair; worked fine. Quick test fine.
* Running FW 1.0.0.53 I could now flash 1.0.1.28 just fine. Quicktest fine. Am now using this version.
* Pairing MiBand2 with GB took numerous tries (Delete Device, Reboot Phone, Add Device, [wait], Stop Scanning, Select MiBand2, tap band, [wait], retry or press button on band upon band display indication) with every one of those firmware versions, but ultimately worked.

Features:
* Displays time in 12h format; would prefer 24h
* Displays date as "Wed.Jan 11". Would prefer "YYYY-MM-DD" or "-MM-DD, WW" with WW being shortened day of the week

Gimmicks:
 * does not yet support Discordian Dates
 * does not yet support Decimal Time

**Comment by 6arms1leg** [comment] 2017-01-11 14:52
@bluuub, @Jojonintendo, I opened another issue regarding the step count deviation (#499).

**Comment by 6arms1leg** [comment] 2017-01-11 15:25
> Appeared to be MiBand2 firmware version 1.0.0.53. Flashed it; worked fine. Had to repair; worked fine.

@Bydgew7, what does "Had to repair" mean? Can you please elaborate?

> Running FW 1.0.0.53 I could now flash 1.0.1.28 just fine.

Since others also reported this, it seems that the *Mili_pro_53.fw* firmware is an intermediate version that is needed to flash newer firmware versions – if that's true, it's probabaly the reason that file is shipped with all newer Mi Fit APKs. So that is the "official" way to upgrade to new firmware.
I would like to add that as a note to the wiki but I still hesitate. Should we wait until more people confirm this?

**Comment by Bydgew7** [comment] 2017-01-11 17:55
> > Appeared to be MiBand2 firmware version 1.0.0.53. Flashed it; worked fine. Had to repair; worked fine.

> @Bydgew7, what does "Had to repair" mean? Can you please elaborate?

What I meant to say was: "The MiBand2 was no longer listed in GB or Android anywhere. I simply paired it again." ("repair" as in "pair again")
On one hand, I do clearly remember being surprised, when after flashing the MiBand2 was suddenly no longer appearing on the phone anywhere. On the other, I see that it should not actually have been that way, it should not have unpaired itself :-)
Either I got things mixed up in the process, or it's a special aspect of .53; maybe pairing information has to be erased to prepare for a new storage format of newer firmwares. :-)

**Comment by Jojonintendo** [comment] 2017-01-11 18:00
The "official" flashing way seems to be:
- First, flash 53 firmware.
- Then, flash 28.
I used the official Mi Fit app to do this because I couldn't flash the 28 firmware (and I didn't want to try the 53 one, as I didn't know what it was), and it rebooted and flashed the band twice. So it probably did this.

**Comment by bluuub** [comment] 2017-01-11 19:46
Yeah, that seems to be the correct way to do it. I can confirm that you have to flash an intermediate version before 1.28 (I don't remember which one though - I guess it was .53). I think we can add this to the firmware wiki page.

**Comment by cpfeiffer** [comment] 2017-01-11 23:08
Thanks, that looks like a good explanation for the Mili_pro_53.fw file. And thanks for the wiki addition!

**Comment by 6arms1leg** [comment] 2017-01-12 20:41
> [...] "repair" as in "pair again" [...]

Ah OK, now I get it. :bulb: :see_no_evil: 
Thanks!

**Comment by Lemlin** [comment] 2017-01-13 22:35
Hi people, 

just wanted to say hello and share some experiences.

Received MiBand2 with HW 0.1.3.2 and FW 1.0.0.34.
Using GB without F-Droid (APK Download): Version 0.16.0, added on 2016-12-30.
Received my Mi Band 2 four days ago, have been using a Mi Band 1S with Mi Band Tools so far.
Mi Band 2 is paired with a Galaxy Note 4 running Android 6.0.1

These are the fw versions I tried today and in this order:
1.0.0.34 -> version I received the band with
1.0.0.39 -> version I upgraded to because you guys recommended it
1.0.0.53 -> Even if probably not needed I still used this as intermediate version to upgrade to 1.0.1.28
1.0.1.28 -> my current version

As already mentioned before I sometimes use the connection to GB with v1.0.1.28. It's too early to tell how often that happens and how much it bothers me. 
What I recognized is that with the new version more app icons (39 altogether) are available.
Unfortunately it's still not possible to display a callers name, but last three digits are working fine (which I configured using Notify &Fitness for Mi Band).
Biggest problem for me so far has been that even if the band was successfully paired with GB and Notify & Fitness, I couldn't find the band in the list of Androids Bluetooth devices and therefore couldn't use it for Androids Smart Lock function. Took me several restarts und unpairing in GB to finally make it visible in Android again.

Now it's all good, everything working like expected. Heart rate monitor is working fine, smart unlock works, "real" 24h clock appears and even the buttons alternative functions are working great (press 1 time: next title in Poweramp, press 2 times: start/stop Poweramp playpack).

I'm bad at programming but if you have any questions I could help you with, please ask. :)

**Comment by Lemlin** [comment] 2017-01-14 11:28
I can confirm that the smart alarms are not working with v.1.0.1.28. Wanted to let you know since this is still worded as a question on [Mi Band Firmware Information Site](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Information).

Yesterday Mi Fit 2.2.11 has been released but the Mili_pro.fw file has the same size like the one which flashes 1.0.1.28.

**Comment by Jojonintendo** [comment] 2017-01-23 15:27
Latest Mi Fit apk brings new firmware and apparently only bugfixes. I installed it, it says 1.0.1.34 and so far it seems to go well. Further testing incoming. GB reports 51770 as version number.

**Comment by cpfeiffer** [comment] 2017-01-23 22:33
@Lemlin thanks for the feedback! I removed the question mark on the firmware wiki page. Looks like there's quite a few different Bluetooth quirks in the different Android ROMs. 

One thing to keep in mind is that a device (e.g. a Mi Band) that is currently connected, typically does not advertise itself. So when connected, the Android Bluetooth dialog won't find it.

If you pair the device, it should be displayed though.

@JohnnySun Thanks for the info, looking forward to further reports :-)

**Comment by cpfeiffer** [comment] 2017-01-26 20:08
I think we can close this now as an issue. Feel free to add further feedback about working or non-working firmware versions or better yet, add it directly to the wiki.

**Closed by cpfeiffer** 2017-01-26 20:08 UTC
Labels: device mi2, discussion, documentation
