### ISSUE TITLE
VLC makes Gadgetbridge crash

### ISSUE THREAD

**Issue by Jojonintendo** [Freeyourgadget/Gadgetbridge#533] opened 2017-01-31 11:47 UTC
#### Your issue is:

When playing any music on VLC, Gadgetbridge (0.17.3) crashes. After restarting GB and setting the default music player to another value, the problem seems to disappear, but then it happens again after some time.

#### Your wearable device is:

Mi Band 2, FW: 1.0.1.34. It happened with previous versions.

#### Your android version is:

LineageOS 14.1 (Android 7.1.1) on Xiaomi Redmi Note 3 Pro

#### Your Gadgetbridge version is:

0.17.3

[gadgetbridge.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/741855/gadgetbridge.zip)

If anything else is needed, feel free to ask! Thank you very much for your hard work!

**Comment by walkjivefly** [comment] 2017-01-31 13:35
Hope I'm not treading on anyone's toes here...

Doesn't reproduce for me using 0.17.3 (self-built) with VLC 2.0.6 and Mi Band 2, FW 1.0.1.28, CM 12.1 (Android 5.1.1) on Redmi 3 Pro. I installed VLC, started playing some music, opened GB. No crash. Changed default music player in GB settings to VLC, quit, restarted, no crash. Swiped through a couple of activity screens, no crash, disconnected, reconnected, no crash. Music is still playing, GB still running. 

Your logfile covers only 5 seconds from app startup to almost the end of initialisation/connecting to device. Is that the correct logfile and is it complete?

Is there a particular sequence of actions you use to reproduce the problem?

**Comment by Jojonintendo** [comment] 2017-01-31 15:17
The log should cover the crash. I enabled logging inside GB, and then almost immediately started VLC to play music, which leads to GB crash. I don't know if in this case the log is lost, maybe? I can provide a longer one if needed.

The sequence that makes GB crash is the following:

1- Have GB connected to Mi Band 2. No music playing.
2- Open VLC and play some music.
3- Right when music starts, GB crashes.
4- I can reopen GB and it connects without problem.
5- Issue seems solved, but after some time (maybe reboot) it fails again.

I'm still not sure how I can re-trigger the issue when it seems gone, but it definitely happens from time to time, only with VLC. I'll try to narrow down the issue.

**Comment by walkjivefly** [comment] 2017-01-31 15:36
I suspect the log doesn't capture the crash. Maybe a logcat would show what's happening. I noticed in mine a bunch of message like 
01-31 22:29:35.937 1931-1931/nodomain.freeyourgadget.gadgetbridge W/Bundle: Key duration expected Integer but value was a java.lang.Long.  The default value 0 was returned.
01-31 22:29:35.938 1931-1931/nodomain.freeyourgadget.gadgetbridge W/Bundle: Attempt to cast generated internal exception:
                                                                            java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
                                                                                at android.os.BaseBundle.getInt(BaseBundle.java:800)
                                                                                at android.content.Intent.getIntExtra(Intent.java:5160)
                                                                                at nodomain.freeyourgadget.gadgetbridge.externalevents.MusicPlaybackReceiver.onReceive(MusicPlaybackReceiver.java:39)
                                                                                at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:867)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
01-31 22:29:35.938 1931-1931/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.externalevents.MusicPlaybackReceiver: Update Music Info: Touch and Go / I Find You Very Attractive / Straight to ... number one
01-31 22:29:35.941 1931-1931/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo

every time the playing song changes but despite the exception GB stays running. Maybe it depends on the Android or VLC version. Which version VLC do you have?

**Comment by Jojonintendo** [comment] 2017-01-31 20:30
I know how to reproduce this issue, at least on my device:

1- Reboot phone.
2- Connect Mi Band 2 to GB.
3- Play some song on VLC > instant GB crash.
4- Reopen GB.
5- Play song again > instant crash.
6- Reopen GB, problem gone.

Somehow it only fails two times, then GB no longer crashes. I provide the logcat of doing all steps above. VLC version is 1.9.0, the F-Droid one.

[GB-crash.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/743085/GB-crash.zip)

**Comment by danielegobbetti** [comment] 2017-01-31 20:59
Please report the vlc version, will test on my device

**Comment by Jojonintendo** [comment] 2017-01-31 21:17
It is the 1.9.0, the one on F-Droid.

**Comment by danielegobbetti** [comment] 2017-02-01 22:01
If you are running a self built version of Gadgetbridge please try the current master as the issue is possibly fixed.

**Comment by Jojonintendo** [comment] 2017-02-01 22:45
Thank you very much for your time. There seems to be problem with latest VLC versions on F-Droid, but it might be solved soon. As for Gadgetbridge, I'll try a newly compiled version tomorrow.

**Comment by nico202** [comment] 2017-02-02 10:31
@Jojonintendo Same problem with fdroid-vlc + fdroid-gadgetbridge, but only sometimes (or certain songs?). Android version: 7.1.1 LG G3

**Comment by danielegobbetti** [comment] 2017-02-02 11:42
Enabling fdroid archive repo enabled fdroid install for me, and I don't see crashes on current master.

**Comment by danielegobbetti** [comment] 2017-02-02 17:26
I stand corrected, latest master fixes only one problem. There is another route the media information can come in, and that route yields to a crash. And, yes, it's our fault, not vlc's.

**Comment by nico202** [comment] 2017-02-03 11:49
@danielegobbetti (I didn't want to be rude saying that's your fault) Thanks for all your work :)

**Comment by danielegobbetti** [comment] 2017-02-05 14:15
Current master should not crash anymore, but the notifications that crashed us before are also ignored as a side effect so it could be that the music information when using VLC are less accurate.

**Comment by cpfeiffer** [comment] 2017-02-12 23:55
AFAIU this is now fixed.

**Closed by cpfeiffer** 2017-02-12 23:55 UTC
Labels: bug
