### ISSUE TITLE
Apps being removed from blacklist after reboot

### ISSUE THREAD

**Issue by malmsey** [Freeyourgadget/Gadgetbridge#664] opened 2017-04-22 00:57 UTC
#### Your issue is:
Whenever I reboot my phone, every blacklisted app save for two (yaata messenger and google play store) gets unlisted.  Every time I reboot I have to remember to go back into the blacklist menu and select all the same apps again.  Some of these apps are Muzei and a variety of Muzei extensions, Join (by joaomgcd), and maybe some more that I'm forgetting.  The new search bar in the blacklist menu helps a lot with this problem but the situation is not ideal...

#### Your wearable device is:
Pebble 2

*Please specify model and firmware version if possible*
FW v4.3

#### Your android version is:
Android 6.0.1 (Dirty Unicorns ROM)

#### Your Gadgetbridge version is:
18.5 (issue has existed for the past several versions, when I started using gadgetbridge)

P.S. thanks to everyone working on gadgetbridge!

**Comment by gianlucapir** [comment] 2017-04-22 13:11
I have the same problem, but just after disabling and activating some apps like auto startup or automatic reconnection, just tap my icon and then everything is saved correctly

**Comment by malmsey** [comment] 2017-04-22 18:00
> I have the same problem, but just after disabling and activating some apps like auto startup or automatic reconnection, just tap my icon and then everything is saved correctly

Could you clarify what you mean? What icon are you tapping?

**Comment by gianlucapir** [comment] 2017-04-22 18:50
![20170422_204814](https://cloud.githubusercontent.com/assets/26039906/25307205/24125a12-279d-11e7-8c45-69c132e3a1b3.png)

**Comment by gianlucapir** [comment] 2017-04-22 18:53
I do not know but I have the same problem but deactivating those functions then re-activating it all works properly
Pebble time stell con gadgetbridge  0.18.5
Sansung  Galaxy S7 con Nougat

**Comment by danielegobbetti** [comment] 2017-05-01 09:29
0.19.1 just hit fdroid, please let us know if the issue is fixed for you.

**Comment by gianlucapir** [comment] 2017-05-03 14:34
Risolto grazie :-)

**Comment by danielegobbetti** [comment] 2017-05-03 16:32
Please show respect for the community and post in english as everyone else is doing. 

I'm closing this since it's confirmed to be fixed.

**Closed by danielegobbetti** 2017-05-03 16:32 UTC
Labels: potentially fixed / needs confirmation

**Comment by gianlucapir** [comment] 2017-05-03 16:41
Ok! Sorry so much
