### ISSUE TITLE
Add an option to synchronise automatically

### ISSUE THREAD

**Issue by ghost** [Freeyourgadget/Gadgetbridge#336] opened 2016-06-21 06:13 UTC
It'll be more convenient to use Gadgetbridge if there is an option to synchronise activity and sleep data automatically after the initial connection, instead of performing synchronisation manually every time.

**Comment by cpfeiffer** [comment] 2016-06-22 22:55
Yes, totally agreed.

**Comment by robin13** [comment] 2016-06-26 11:43
+1

**Comment by gigawebs** [comment] 2018-06-24 00:11
+1

**Comment by danielegobbetti** [comment] 2018-06-24 07:54
Closing this (actually looks like a duplicate of 698 or vice versa)

**Closed by danielegobbetti** 2018-06-24 07:54 UTC
Labels: device mi, enhancement

**Comment by glumanda99** [comment] 2018-06-24 10:44
@danielegobbetti Can you link to it pls? 698 is also closed.

**Comment by robin13** [comment] 2018-06-27 13:34
@danielegobbetti Please re-open this issue

**Comment by danielegobbetti** [comment] 2018-06-27 13:53
@robin13 why? Issue is fixed in 0.27

**Comment by robin13** [comment] 2018-06-27 14:04
Ahh... good to know. :) This was not visible here...

**Comment by IzzySoft** [comment] 2018-06-27 14:33
:rofl: @danielegobbetti problem was you said

> Closing this (actually looks like a duplicate of 698 or vice versa)

while Carsten closed #336 a year ago as duplicate of this one. So you created a closed circle, both ends saying "look over there" – and none of them saying "solved". :roll_eyes:

**Comment by danielegobbetti** [comment] 2018-06-27 14:59
Now I understand the perplexity. I was thinking of #1116

I hope this closes the circle. :)

**Comment by IzzySoft** [comment] 2018-06-27 16:18
@danielegobbetti Ah! That explains. There it explicitly states: "danielegobbetti (Daniele Gobbetti) closed this in 36aae1e 8 days ago", which clearly says "solved by that commit". Thanks for shedding light!
