### ISSUE TITLE
Gadgetbridge becomes foreground when rotating device

### ISSUE THREAD

**Issue by EureEminenz** [Freeyourgadget/Gadgetbridge#817] opened 2017-09-14 11:38 UTC
#### Before opening an issue please confirm the following:
- [x ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
When Gadgedbridge is running and I use any other app (tried Firefox, Contacts,...) every time I rotate my device (entering or leaving landscape mode) Gadgetbridge comes in foreground which is very annoying.
I'm not sure whether this is related to Gadgetbridge or OS, since new behaviour first occured after updating to latest nightly.
This also happens when Gadgetbridge is not the latest used app so it's not just toggeling the last active apps it's always Gadgetbridge which comes to foreground.
This does also happen when device is not connected. It doesn't happen when Gadgetbridge is closed.
Any one else experiencing this? Should I produce a log file? Anything else I could do help troubleshooting?

#### Your wearable device is:

MiBand2, FW 1.0.1.34, HW V0.1.3.2

#### Your android version is:

LineageOS 14.1 20170912

#### Your Gadgetbridge version is:
0.21.0

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by IzzySoft** [comment] 2017-09-14 12:19
> * [x ] I have searched the issues, and I didn't find a solution to my problem / an answer to my question.

Really? Duplicate of #802, isn't it?

**Closed** 2017-09-14 12:20 UTC
