### ISSUE TITLE
Amazfit Bip - Firmware 1.1.5.02

### ISSUE THREAD

**Issue by FreeTheTech101** [Freeyourgadget/Gadgetbridge#1324] opened 2018-11-07 18:49 UTC
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

Just confirming that firmware revision 1.1.5.02 does in-fact work with Gadgetbridge. Battery percent, notifications, and fitness information seems to be syncing perfectly.

#### Your wearable device is:

Amazfit Bip

#### Your android version is:

9.0

#### Your Gadgetbridge version is:

0.31.0

**Comment by FreeTheTech101** [comment] 2018-11-07 19:00
Also, according to the Wiki, call ignoring is a feature which is not yet implemented. However, I can confirm that ignoring the call on the watch does in-fact dismiss the notification, and pressing decline (not sure of the exact string name at the time) does in fact hang-up the call.

**Comment by ashimokawa** [comment] 2018-11-07 22:13
Thanks for the report! We will have to fix gpx then

**Comment by arocketguy** [comment] 2018-11-07 22:36
your welcome. Just verified it works with the Notify and Fitness app if that is of any help.

Also, the plot of the track looks to be shifted like 20 miles to the east of my location. The first few data points are clearly wrong (including the starting point - which is close, but not quite right), then the remaining track looks to shifted off to the east.

**Comment by 2Napoca** [comment] 2018-11-08 06:47
I'm confirming the same issue. It's related to altitude / <ele> field in the .gpx file.
I'm attaching two logs of the same route (first before firmware upgrade, second after latest firmware upgrade).
As you can see the elevation is way off with the latest firmware (the real altitude being 468m):
in the old firmware was: <ele>468.000000</ele>
in the new firmware is: <ele>4076.000000</ele>

[GPXFiles.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/2560577/GPXFiles.zip)

As a sidenote: in the MiFit application since the latest upgrade the red track log is not continuous anymore, it is missing some segments (I suppose because of same altitude issues). It wasn't missing segments before the firmware upgrade so I'm not sure if this is a firmware problem or gadgetbridge one.

Anyways, thanks for a great tool and keep up the good work.

**Comment by Pepe404** [comment] 2018-11-08 09:19
No silent disconnect? No reconnection problems? In all previous versions (older GB versions and older watch firmwares), those problems finally appeared, usually after a day or two, not immediately.

**Comment by 2Napoca** [comment] 2018-11-08 09:57
So far except for GPS/Elevation I noticed no other problems.

**Comment by ashimokawa** [comment] 2018-11-08 14:49
Please keep in mind that this issue is with tracks _RECORDED_ with the new firmware and not when syncing older tracks with the new firmware.

@2Napoca 
I can confirm your findings with elevation. When I divide that by 10 I get a sane track.
Now I need to find out how to decide whether he have to divide by 10 or not :/

**Comment by ashimokawa** [comment] 2018-11-08 16:19
I think it is fixed in master now

**Comment by ashimokawa** [comment] 2018-11-08 19:14
Fixed. And the Firmware is whitelisted. Closing

**Closed by ashimokawa** 2018-11-08 19:14 UTC

**Comment by 2Napoca** [comment] 2018-11-09 06:30
Thanks for the prompt reply. Unfortunately I have made a new test with the latest gadgetbridge version and today's tracklog elevation is closer to reality but still off with about 2000 meters (instead of 450m the real altitude). I'm attaching a log with the same route made today.
[GPXFile.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/2564822/GPXFile.zip)

**Comment by ashimokawa** [comment] 2018-11-09 07:31
@2Napoca 
Too bad :( For me an elevation of "43" looked sane here where I am.
It seems there where two bugs then - one being the altitude and another bug that caused the track being completely broken (which is fixed, and confirmed also by @danielegobbetti).
Remeber you can reset your "last fetched" date by pressing the menu button in the upper right in the activities screen. So you can re-fetch your last track without recording a new one. Then you can also fetch the tracks that were recorded with an old firmware to double check that they are okay.

Another idea would be to try firmware 1.1.5.04 from Mi Fit 3.5.4.1, but then remember to record a new track.

**Comment by ashimokawa** [comment] 2018-11-09 07:32
@2Napoca 
Just to be sure you compiled 0.31.1 yourself?

**Comment by 2Napoca** [comment] 2018-11-09 07:48
No, I don't know how to compile a version myself. I was using the latest compiled version: 0.31.0.
If you could be so kind and help me compile the 0.31.1 I can redo / do more tests anytime.

**Comment by ashimokawa** [comment] 2018-11-09 08:38
@2Napoca
0.31.1 is the fixed version and should appear on fdroid shortly. As always we have no influence when that will happen. But normally it is 1-2 days.

**Comment by 2Napoca** [comment] 2018-11-09 08:46
Thank you. I will wait for it to appear then remake all my tests with the new version and let you know.

**Comment by ktau221** [comment] 2018-11-09 13:34
Thanks, i will test it too.

**Comment by arocketguy** [comment] 2018-11-09 16:42
I compiled the new version and I can confirm it fixes my GPS track issue. Thank you!

**Comment by 2Napoca** [comment] 2018-11-12 05:13
The latest version finally appeared on F-Droid and I confirm that in v0.31.1 the elevation problem is fixed.
Everything is now back to normal with the GPS logging. Thank you very much for all for your help.
