### ISSUE TITLE
Rate limit notifications 

### ISSUE THREAD

**Issue by Qwertie-** [Freeyourgadget/Gadgetbridge#942] opened 2018-01-18 07:36 UTC
I have an app that scans for new notifications once a day and when it does it sends about 50 notifications all at once, android just groups these all in to one but my pebble watch tries to show them all and then crashes and reboots. Would be great if gadgetbridge would have a rate limiter which only allows `n` notifications in 10 seconds so an app sending a lot at once or if you just reconnect after a while and a lot of apps get notifications your watch doesn't crash.

#### Device:

Pebble time steel

#### Android version:
7.1.2
#### Gadgetbridge version:

0.23.2

**Comment by Avamander** [comment] 2018-01-18 09:44
Duplicate of https://github.com/Freeyourgadget/Gadgetbridge/issues/663

**Closed** 2018-01-18 10:06 UTC
