### ISSUE TITLE
Notifications are repeated

### ISSUE THREAD

**Issue by albertsal** [Freeyourgadget/Gadgetbridge#684] opened 2017-05-10 07:38 UTC
#### Before opening an issue please confirm the following:
- [x ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
It's been a while since when I get a message on whatsapp i get 2 or 3 times the same message.I do not understand if the problem is whatsapp or gb, the other notifications i get it correctly ... to help you an example message is

0x43 0x 2 0x 1 0x56 0x69 0x72 0x67 0x69 0x6e 0x69 0x61 0x20 0x56 0x65 0x73 0x63 0x6f 0x20 0x40 0x53
[gadgetbridge.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/989019/gadgetbridge.zip)

#### Your wearable device is:

zeband:zeblaze 2.44

#### Your android version is:
galaxy s6 V 6.0.1

#### Your Gadgetbridge version is:
0.19.1

**Comment by danielegobbetti** [comment] 2017-05-10 08:35
duplicate of #668

**Closed** 2017-05-10 08:36 UTC
Labels: duplicate
