### ISSUE TITLE
show runnerup track-data on pebble

### ISSUE THREAD

**Issue by kas70** [Freeyourgadget/Gadgetbridge#208] opened 2016-01-19 18:55 UTC
https://github.com/jonasoreland/runnerup/

**Comment by danielegobbetti** [comment] 2016-01-19 21:54
related issue on the other project:
https://github.com/jonasoreland/runnerup/issues/98

**Comment by danielegobbetti** [comment] 2016-01-20 13:49
After looking at the code of the mentioned app, the issue is not app specific, but rather the same as already reported on #130. Hence I'm closing this issue.

**Closed by danielegobbetti** 2016-01-20 13:49 UTC
