### ISSUE TITLE
No able to connect Miband 1S with Android Marshmellow

### ISSUE THREAD

**Issue by irpainel** [Freeyourgadget/Gadgetbridge#307] opened 2016-05-20 02:36 UTC
Hi guys, thank for this amazing app. It is exactly what I was looking for.
Unfortunately I have a problem, I'm not able to connect my miband 1S to the GB. My phone is a HTC One M8, for some weird reason it's not possible to connect the band using the bluetooth dialog (it says the pin is wrong). I had to get the mac address and add it manually to GB sees my phone.

Here is my log:

```
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: new device connection state: CONNECTED
D/BluetoothGatt: discoverServices() - device: C8:0F:10:4E:2F:18
I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Attempting to start service discovery:true
D/BluetoothGatt: onSearchComplete() = Device=C8:0F:10:4E:2F:18 Status=0
I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Attempting to pair MI device...
D/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Requesting Device Info!
D/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Writing User Info!
I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Attempting to set wear location...
I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Attempting to set Fitness Goal...
I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Sending current time to Mi Band: May 19 (20 May 2016 02:27:10 GMT)
D/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Requesting Battery Info!
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: about to add: 11:27:10 PM: Transaction task: Initializing device with 21 actions
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: May 19, 11:27 PM: SetDeviceStateAction to INITIALIZING
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: May 19, 11:27 PM: NotifyAction on characteristic: 0000ff03-0000-1000-8000-00805f9b34fb
D/BluetoothGatt: setCharacteristicNotification() - uuid: 0000ff03-0000-1000-8000-00805f9b34fb enable: true
I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
D/nodomain.freeyourgadget.gadgetbridge.service.btle.TransactionBuilder: use NOTIFICATION
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: May 19, 11:27 PM: WriteAction on characteristic: 0000ff09-0000-1000-8000-00805f9b34fb
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic write: 0000ff09-0000-1000-8000-00805f9b34fb (success)
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: May 19, 11:27 PM: ReadAction on characteristic: 0000ff0a-0000-1000-8000-00805f9b34fb
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic read: 0000ff0a-0000-1000-8000-00805f9b34fb (success)
I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Got Mi Band Date: May 19, 11:27 PM
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: May 19, 11:27 PM: WriteAction on characteristic: 0000ff0f-0000-1000-8000-00805f9b34fb
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic changed: 0000ff03-0000-1000-8000-00805f9b34fb value:  0x8
W/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: DATA: 0x 8
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic changed: 0000ff03-0000-1000-8000-00805f9b34fb value:  0x8
W/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: DATA: 0x 8
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic changed: 0000ff03-0000-1000-8000-00805f9b34fb value:  0x8
W/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: DATA: 0x 8
D/BluetoothGatt: onClientConnectionState() - status=22 clientIf=5 device=C8:0F:10:4E:2F:18
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: connection state change, newState: 0 (failed: 22)
W/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: connection state event with error status 22
I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Disconnected from GATT server.
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: handleDisconnected: 22
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: internal gatt callback set to null
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: new device connection state: NOT_CONNECTED
D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: disconnect()
```

Thanks a lot!

**Comment by cpfeiffer** [comment] 2016-05-20 17:34
I week have a look at this later in the evening. Nothing suspicious from a quick glance. Did you set some user information in the preferences?

Were you able to bond the devices by tapping the band when it blinked, or didn't it blink at all during connection?

And, are you on marshmallow?

**Comment by cpfeiffer** [comment] 2016-05-20 18:47
Another question: do you happen to know the firmware version of your mi band?

**Comment by cpfeiffer** [comment] 2016-05-20 19:03
AFAIU, the problem is that your device is not paired. 

Mi Bands use an application level pairing in addition to the bluetooth pairing, and the connection fails exactly when trying to do the application level pairing.

Do you have another device, e.g. a tablet or a friend's phone you could use for testing?

**Comment by irpainel** [comment] 2016-05-21 19:46
Hey @cpfeiffer, thanks for replying.
Answering your questions:
- My band does not blink at all when it's connecting.
- I am on Marshmallow
- The firmware is 4.16.3.7. I got the band a month ago so it was updated. I'm not able to downgrade it.
- I'm able to pair with the official app.

- I'm going to try on another device later, to see if it works.

**Comment by cpfeiffer** [comment] 2016-05-21 20:58
Hmm, so we can rule out 
- the phone/bluetooth stack because it worked fine with Mi Fit
- the firmware version (I'm successfully running the same version with Gadgetbridge)

When you say, you cannot pair the band in the bluetooth dialog, I'm wondering if it isn't already paired from Mi Fit?

Could it be that Mi Fit is still running in the background?

**Comment by irpainel** [comment] 2016-05-25 00:06
Sorry about the delay, i've been busy at work.

So I tried in a different device (a One plus one) and it did not work.
I tried even without the miFit app installed, not luck there as well.

**Comment by cpfeiffer** [comment] 2016-05-25 22:19
This is really weird. I've never seen a device that can be paired with Mi Fit, but not with Gadgetbridge, nor with the pairing dialog.

So, when you pair it with Mi Fit, afterwards it should be shown as paired in Android's bluetooth dialog, right? And (after ensuring that Mi Fit is not running anymore), you still cannot connect it with Gadgetbridge? Can you post another log of this, in case it is different from your earlier one? In particular, a complete log of a single connection attempt? Maybe your device reports a different hardware version and is recognized as an older Mi Band. What does Gadgetbrige show as device information, can you post a screenshot?

The last resort I see is capturing the bluetooth traffic, once with Mi Fit and once with Gadgetbridge and then  checkings what's different. (Open the Android Settings, Development Settings, enable "Bluetooth HCI Snoop").

**Comment by cpfeiffer** [comment] 2016-05-25 22:21
Or maybe Gadgetbridge lacks Bluetooth Admin permission? I suppose it has to be explicitly granted on Marshmellow.

**Comment by ashimokawa** [comment] 2016-05-26 13:26
@cpfeiffer 
No, even though the code to check and request bt permission is in place, it will never be triggered because it is not supported as a runtime permission, so we have that always granted via manifest.

If someone revoked the permission with other permission editor then there could be problem though.

**Comment by hevayo** [comment] 2016-05-30 09:27
Hi guys, I would like to thank you for this great app. It is very useful for my work. I have a MI1S and had gadget bridge working with older mi band firmware as I remember (4.15.12.10). Then I update my Moto G2nd gen to marshmallow and it was still working since the band was paired with GB.

Then I disconnected the band tried to pair it again with GB but couldn't and I am getting the same error as this issue. Please find the log bellow. 

```
05-30 14:40:04.776 7260-7260/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
05-30 14:40:04.776 7260-7260/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: disconnect()
05-30 14:40:04.777 7260-11196/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Thread interrupted
05-30 14:40:04.777 7260-11196/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Queue Dispatch Thread terminated.
05-30 14:40:04.779 7260-7260/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Attempting to connect to MI
05-30 14:40:04.781 7260-7260/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: connect() - device: C8:0F:10:2B:08:14, auto: false
05-30 14:40:04.781 7260-7260/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: registerApp()
05-30 14:40:04.781 7260-7260/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: registerApp() - UUID=7d0e495f-a5ca-477d-8d40-27e9d007c97d
05-30 14:40:04.782 7260-7276/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: onClientRegistered() - status=0 clientIf=5
05-30 14:40:04.783 7260-7260/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: new device connection state: CONNECTING
05-30 14:40:04.786 7260-7260/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
05-30 14:40:04.789 7260-11761/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Queue Dispatch Thread started.
05-30 14:40:06.463 7260-7260/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.externalevents.BluetoothConnectReceiver: got connection attempt
05-30 14:40:06.463 7260-7260/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.externalevents.BluetoothConnectReceiver: will connect to MI
05-30 14:40:06.474 7260-7260/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
05-30 14:40:06.479 7260-7638/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=5 device=C8:0F:10:2B:08:14
05-30 14:40:06.479 7260-7638/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: connection state change, newState: 2 (success)
05-30 14:40:06.479 7260-7638/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Connected to GATT server.
05-30 14:40:06.479 7260-7638/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: new device connection state: CONNECTED
05-30 14:40:06.479 7260-7638/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: discoverServices() - device: C8:0F:10:2B:08:14
05-30 14:40:06.481 7260-7638/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Attempting to start service discovery:true
05-30 14:40:06.500 7260-7260/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
05-30 14:40:06.538 7260-7260/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
05-30 14:40:06.538 7260-7277/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: onSearchComplete() = Device=C8:0F:10:2B:08:14 Status=0
05-30 14:40:06.538 7260-7277/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Attempting to pair MI device...
05-30 14:40:06.539 7260-7277/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Requesting Device Info!
05-30 14:40:06.539 7260-7277/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Writing User Info!
05-30 14:40:06.539 7260-7277/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Attempting to set wear location...
05-30 14:40:06.539 7260-7277/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Attempting to set Fitness Goal...
05-30 14:40:06.540 7260-7277/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Sending current time to Mi Band: May 30 (30 May 2016 09:10:06 GMT)
05-30 14:40:06.540 7260-7277/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Requesting Battery Info!
05-30 14:40:06.540 7260-7277/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: about to add: 2:40:06 PM: Transaction task: Initializing device with 21 actions
05-30 14:40:06.541 7260-11761/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: May 30, 2:40 PM: SetDeviceStateAction to INITIALIZING
05-30 14:40:06.541 7260-11761/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: May 30, 2:40 PM: NotifyAction on characteristic: 0000ff03-0000-1000-8000-00805f9b34fb
05-30 14:40:06.541 7260-11761/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: setCharacteristicNotification() - uuid: 0000ff03-0000-1000-8000-00805f9b34fb enable: true
05-30 14:40:06.542 7260-11761/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.TransactionBuilder: use NOTIFICATION
05-30 14:40:06.544 7260-7260/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
05-30 14:40:06.606 7260-7638/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
05-30 14:40:06.607 7260-11761/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: May 30, 2:40 PM: WriteAction on characteristic: 0000ff09-0000-1000-8000-00805f9b34fb
05-30 14:40:06.706 7260-7277/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic write: 0000ff09-0000-1000-8000-00805f9b34fb (success)
05-30 14:40:06.707 7260-11761/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: May 30, 2:40 PM: ReadAction on characteristic: 0000ff0a-0000-1000-8000-00805f9b34fb
05-30 14:40:06.900 7260-7276/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic read: 0000ff0a-0000-1000-8000-00805f9b34fb (success)
05-30 14:40:06.901 7260-7276/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Got Mi Band Date: May 30, 2:40 PM
05-30 14:40:06.901 7260-11761/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: May 30, 2:40 PM: WriteAction on characteristic: 0000ff0f-0000-1000-8000-00805f9b34fb
05-30 14:40:07.116 7260-7277/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic changed: 0000ff03-0000-1000-8000-00805f9b34fb value:  0x8
05-30 14:40:07.116 7260-7277/nodomain.freeyourgadget.gadgetbridge W/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: DATA: 0x 8
05-30 14:40:07.470 7260-7276/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic changed: 0000ff03-0000-1000-8000-00805f9b34fb value:  0x8
05-30 14:40:07.470 7260-7276/nodomain.freeyourgadget.gadgetbridge W/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: DATA: 0x 8
05-30 14:40:07.485 7260-7638/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: onClientConnectionState() - status=34 clientIf=5 device=C8:0F:10:2B:08:14
05-30 14:40:07.485 7260-7638/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: connection state change, newState: 0 (failed: 34)
05-30 14:40:07.485 7260-7638/nodomain.freeyourgadget.gadgetbridge W/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: connection state event with error status 34
05-30 14:40:07.485 7260-7638/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Disconnected from GATT server.
05-30 14:40:07.485 7260-7638/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: handleDisconnected: 34
05-30 14:40:07.485 7260-7638/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: internal gatt callback set to null
05-30 14:40:07.485 7260-7638/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: new device connection state: NOT_CONNECTED
05-30 14:40:07.486 7260-7638/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: disconnect()
05-30 14:40:07.486 7260-7638/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Disconnecting BtLEQueue from GATT device
05-30 14:40:07.486 7260-7638/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: cancelOpen() - device: C8:0F:10:2B:08:14
05-30 14:40:07.488 7260-7260/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
05-30 14:40:07.489 7260-7638/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: close()
05-30 14:40:07.489 7260-7638/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: unregisterApp() - mClientIf=5
05-30 14:40:07.490 7260-7638/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: new device connection state: NOT_CONNECTED
05-30 14:40:07.527 7260-7260/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
```

Let me know if I can help in any other way. 

Thanks

**Comment by hevayo** [comment] 2016-05-30 11:06
Hi I checked on another phone Nexus 5 with marshmallow (6.0.1) and the band worked. Android version on my phone indicate 6.0.

**Comment by cpfeiffer** [comment] 2016-05-31 20:46
Does it help if you clear the cache of Gadgetbridge? And maybe reboot your mobile?

Just wild guesses, but I had a really, really weird situation myself yesterday, where the pairing activity would crash my phone repeatedly, location could not be read because the location providers seemed to be disabled. And then, suddenly, it all worked again, after clean-installing Gadgetbridge (in contrast to hot-code-replace with Android Studio).

**Comment by Assault** [comment] 2016-06-02 20:06
Same behavior on my device. As i read about connection problems i found somewhere in the miui forum (that was somthing about two weeks ago). It seems it is a typical Problem when you use Android 6.0.0. With Android 6.0.1 many other people report, that the mi band 1s is working like a charm. Its also often reported, that the mi1s is working, when you have connected it on android 5.x before and than upgrade to 6.0.0.

I tried using the mi band 1s with my moto e (lte / 2015) android 6.0.0. Gadgetbridge is able to discover the mi1s but can't pair it. a log file is not written. The mi1s is not paired with the original xiaomi app that moment. Connecting with the xiaomi app is working without any problem. the mi band just somtetimes appears in the bluetooth settings but it can't be paired. 

Rebooting mobile, clearing app data nothing helps.

the mi band version is 4.16.3.7 
the heart rate version is 1.3.76.18

**Comment by cpfeiffer** [comment] 2016-06-04 23:01
Thanks for testing and your report. It would indeed be nice to know whether the problems could be related to android 6.0.0 vs 6.0.1.

I for one have 6.0.1 and pairing works fine.

To check this, we need someone who could try pairing with 6.0.0 with MiFit after clearing its cache and app data and then configuring different user info.

If pairing still works, we can try to find out how to do that as well. Background: Mi Band remembers paired devices (Mac address) but in combination with the configured user info (name, age, height, weight,...). It could be that connecting still worked because the band recognized the app/device based on user info and thus without requiring pairing). GB OTOH, with different user info would need proper pairing to "take over" the band.

**Comment by cpfeiffer** [comment] 2016-06-06 19:37
FWIW, other people have the same problem. There's a long thread at http://en.miui.com/thread-172180-1-1.html with a blog posting offering solutions at http://kowsikbabu.blogspot.de/2016/06/mi-band-pairing-issuesproblems-fix-mi.html

If someone succeeds with this, I'd appreciate to know what worked.

**Comment by rd999** [comment] 2016-06-13 09:39
I ran into the same problem. Unpaired my MI Band 1s on my LG-G3 with Android 6. GB worked after upgrade from Android 5 to 6. Pairing was not removed during that. But now successfully displayed the band during scan but it cannot pair it, or in other words it takes forever to pair.
I tried the Mi Fit and the Mi Band Notify app and both got it paired but that made no difference for GB.
Still not working with GB. Please help to get it working again.

**Comment by cpfeiffer** [comment] 2016-10-28 21:53
Is this still an issue? If it still is, please make sure to activate location (network or GPS) before discovery.

**Comment by rd999** [comment] 2016-11-02 06:01
It worked then by entering the band's address directly without search.
With that I could use GB and 1s without problems.
2 weeks ago I bought Mi Band 2. So now it isnt a problem at all.

**Comment by cpfeiffer** [comment] 2016-11-04 21:37
Thanks. I'll close this issue now. We have some larger changes for discovery in planning, anyway.

**Closed** 2016-11-07 21:35 UTC
Labels: mi band
