### ISSUE TITLE
Crash when Neutron Music Player changes track

### ISSUE THREAD

**Issue by gwenhael-le-moine** [Freeyourgadget/Gadgetbridge#778] opened 2017-08-24 08:49 UTC
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Gadgetbrige crashes when Neutron Music Player changes track, see logcat below.

#### Your wearable device is:
Pebble Time (HW: snowy_dvt, FW: v4.3)

#### Your android version is:
Android 7.0 stock LG h990n

#### Your Gadgetbridge version is:
Version 0.20.1 from F-Droid

Relevant (?) extract of logcat:
```
08-24 10:37:21.342  3351  3351 I MusicController: [MusicControllerMediaSessionManager.java:106:onPlaybackStateChanged()] oooooo 
08-24 10:37:21.343  2534  2534 I PhoneStatusBar: onPlaybackStateChanged(): PAUSED
08-24 10:37:21.345  2976  3327 I BluetoothAvrcpServiceJni: onMediaPlayerStateChangedNative: sBluetoothAvrcpInterface: 0xd4dd3d20
08-24 10:37:21.345  2976  3327 D Avrcp_btif_rc: on_media_player_state : state = 2
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler: Uncaught exception: Error receiving broadcast Intent { act=com.android.music.playbackcomplete flg=0x10 } in nodomain.freeyourgadget.gadgetbridge.externalevents.MusicPlaybackReceiver@a8ae927java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.music.playbackcomplete flg=0x10 } in nodomain.freeyourgadget.gadgetbridge.externalevents.MusicPlaybackReceiver@a8ae927
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler:  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1172) ~[na:0.0]
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler:  at android.os.Handler.handleCallback(Handler.java:751) ~[na:0.0]
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler:  at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler:  at android.os.Looper.loop(Looper.java:154) ~[na:0.0]
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler:  at android.app.ActivityThread.main(ActivityThread.java:6247) ~[na:0.0]
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler:  at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872) ~[na:0.0]
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) ~[na:0.0]
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set android.os.Bundle.keySet()' on a null object reference
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler:  at nodomain.freeyourgadget.gadgetbridge.externalevents.MusicPlaybackReceiver.onReceive(MusicPlaybackReceiver.java:51) ~[na:0.0]
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler:  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1162) ~[na:0.0]
08-24 10:37:21.348  6364  6364 E nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler:  ... 7 common frames omitted
08-24 10:37:21.348  6364  6364 E AndroidRuntime: FATAL EXCEPTION: main
08-24 10:37:21.348  6364  6364 E AndroidRuntime: Process: nodomain.freeyourgadget.gadgetbridge, PID: 6364
08-24 10:37:21.348  6364  6364 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.music.playbackcomplete flg=0x10 } in nodomain.freeyourgadget.gadgetbridge.externalevents.MusicPlaybackReceiver@a8ae927
08-24 10:37:21.348  6364  6364 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1172)
08-24 10:37:21.348  6364  6364 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
08-24 10:37:21.348  6364  6364 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
08-24 10:37:21.348  6364  6364 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
08-24 10:37:21.348  6364  6364 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6247)
08-24 10:37:21.348  6364  6364 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-24 10:37:21.348  6364  6364 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
08-24 10:37:21.348  6364  6364 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
08-24 10:37:21.348  6364  6364 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set android.os.Bundle.keySet()' on a null object reference
08-24 10:37:21.348  6364  6364 E AndroidRuntime:        at nodomain.freeyourgadget.gadgetbridge.externalevents.MusicPlaybackReceiver.onReceive(MusicPlaybackReceiver.java:51)
08-24 10:37:21.348  6364  6364 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1162)
08-24 10:37:21.348  6364  6364 E AndroidRuntime:        ... 7 more
08-24 10:37:21.352  1799  9633 W ActivityManager:   Force finishing activity nodomain.freeyourgadget.gadgetbridge/.activities.ControlCenterv2
08-24 10:37:21.358  1799  1863 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{a00203c u0 com.android.music.metachanged} to ReceiverList{a6623d2 6364 nodomain.freeyourgadget.gadgetbridge/10625/u0 remote:8678e5d}: process crashing
08-24 10:37:21.358  3351  3351 I MusicController: [MusicControllerMediaSessionManager.java:173:updatePlayerInformation()] oooooo PlayState : 2
08-24 10:37:21.358  3351  3351 I MusicController: [MusicControllerMediaSessionManager.java:184:updatePlayerInformation()] oooooo Is need View update : true
08-24 10:37:21.379  1799  1864 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@1049c46
```

**Comment by danielegobbetti** [comment] 2017-08-25 20:04
@gwenhael-le-moine the issue is probably fixed in master, so please check again with the next release on f-droid and re-open this issue if the problem persist!
For the time being, I am closing this.

**Closed by danielegobbetti** 2017-08-25 20:04 UTC
Labels: android integrations/notifications, device pebble
