### ISSUE TITLE
Gadgetbridge crashes when trying to add third party pebble apps

### ISSUE THREAD

**Issue by Kurolox** [Freeyourgadget/Gadgetbridge#897] opened 2017-11-30 09:42 UTC
#### Before opening an issue please confirm the following:
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Gadgetbridge crashes as soon as I press the button to look for third party pebble app files on the system.

Log: https://gist.github.com/Kurolox/7be96c6e06975716af4534dfb3a0cde4

#### Your wearable device is:
Pebble time (Firmware 4.3)

#### Your android version is:
Android 7.1.2

#### Your Gadgetbridge version is:
0.22.4

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment] 2017-11-30 12:36
You mean it crashes when you press the + button in app manager?

Can you try to select a pbw from within  your file manager and see if you can install that way?

**Comment by Kurolox** [comment] 2017-11-30 13:18
Yeah, it crashes whenever I press the + button.

Installing them from a file manager works fine, though.

**Comment by ashimokawa** [comment] 2017-12-04 21:45
@Kurolox 
Unfortunately the log does not contain the crash (this is is problem we have recently), so I am not sure why this happens. :(

**Comment by cpfeiffer** [comment] 2017-12-22 00:55
Added #916 for this.

**Comment by cpfeiffer** [comment] 2018-01-03 23:17
#916 is fixed for 0.23.3 or higher, so a log created with the new version should contain the stacktrace.

**Comment by Kurolox** [comment] 2018-01-03 23:29
Will provide new logs in the next 24 hours then.

**Comment by danielegobbetti** [comment] 2018-02-17 17:42
@Kurolox I'm closing this issue but feel free to add the logs in case the issue is still present for you.

**Closed by danielegobbetti** 2018-02-17 17:42 UTC
Labels: bug, device pebble, no feedback
