### ISSUE TITLE
Unable to remove paired device

### ISSUE THREAD

**Issue by dmig** [Freeyourgadget/Gadgetbridge#1462] opened 2019-03-21 04:31 UTC
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Trying to remove previously connected Amazfit Bip (named 'MI') with no reaction and no errors.

#### Your android version is:
LineageOS 15.1

#### Your Gadgetbridge version is:
0.32.2, 0.32.3

[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/2990821/gadgetbridge.log)
![Screenshot_20190321-112611_Gadgetbridge](https://user-images.githubusercontent.com/388564/54733556-d4604000-4bcc-11e9-958b-96e7214e4946.png)

**Comment by vanous** [comment] 2019-09-02 15:01
Hello, sorry about the issue, this is a duplicate of https://github.com/Freeyourgadget/Gadgetbridge/issues/1605 , where i also found the cause and you can find a temporary solution.

@IzzySoft duplicate, please close in favor of https://github.com/Freeyourgadget/Gadgetbridge/issues/1605

**Closed** 2019-09-02 20:16 UTC
