### ISSUE TITLE
Calendar events duplicated on timeline

### ISSUE THREAD

**Issue by masakoodaa** [Freeyourgadget/Gadgetbridge#818] opened 2017-09-14 14:50 UTC
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Calendar events duplicated on timeline

![duplicatedevents](https://user-images.githubusercontent.com/26069787/30435950-baa9a19a-9973-11e7-96dd-4e1c677c4255.png)

As you can see in the image above, some (marked with different colors), but not all events are duplicated on the Pebble's timeline. This happens to all events at random, both local and synced events (ICSdroid) as well as single events and recurring events. I haven't found a recurring pattern as some events are duplicated once and some two times (resulting in 3 identical events on the timeline). Attached below is the relevant part of the log. I didn't have the issue with Gadgetbridge 0.20.2.

[log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/1303366/log.txt)

#### Your wearable device is:
Pebble Time Steel fw v4.3

#### Your android version is:
Lineage OS 14.1/Android 7.1.2 (build shouldn't matter; I had been running the same nightly for multiple weeks before the issue started)

#### Your Gadgetbridge version is:
0.21.0

**Comment by masakoodaa** [comment] 2017-09-14 14:53
(How) can I downgrade to 0.20.2 without losing my settings? Installing the earlier version from F-Droid failed "due to an unknown error"

**Comment by ashimokawa** [comment] 2017-09-14 18:10
@masakoodaa 
There are no calendar related changes in 0.21.0, downgrading won't help

**Comment by danielegobbetti** [comment] 2017-09-14 20:00
I see the screenshots refer to mostly all-day events. Do you live in an area where there was a daylight saving time change in this period?

**Comment by masakoodaa** [comment] 2017-09-15 09:06
@ashimokawa 
Okay, thanks. I guess the timing is just a coincidence then.

@danielegobbetti 
I live in Finland and our daylight saving time change is in October, so no. Both all-day and non-all-day events get duplicated, I just chose to screenshot those as they aren't from my personal calendar.

**Comment by danielegobbetti** [comment] 2017-09-15 10:38
@masakoodaa 
well it was worth a try :) Did you perform other changes that could influence the calendars on the phone (changing calendars' names or colors, updating the ROM, install/uninstall some app that had permission as "sync adapter", etc)
Also can you please check if the calendars that are listed in the Gadgetbridge calendar blacklist settings are somehow wrong?

**Comment by masakoodaa** [comment] 2017-09-15 11:03
@danielegobbetti 
I don't recall changing the calendars' names or colors, but I may have stopped syncing some remote calendars. I updated the ROM after having the issue for a day, didn't fix it. I did install [Dashboard](https://github.com/C-D-Lewis/dashboard) and used it to toggle "Auto-sync data" off and later back on again when I was having problems with my limited mobile internet. Does that affect Gadgetbridge's calendar sync? I should also add that there are no duplicate events in the phone's calendar.  
  
I didn't spot anything wrong with Gadgetbridge's calendar blacklist settings. Should I try unblacklisting all calendars to see if that does anything?

**Comment by masakoodaa** [comment] 2017-09-15 11:05
If I'm the only one having this issue I can try unpairing my Pebble and reinstalling Gadgetbridge from scratch. I'd rather not, but I don't want to waste your time on this when you could be working on more important things.

**Comment by ashimokawa** [comment] 2017-09-15 14:32
@masakoodaa 
We have no influence of when F-Droid builds us or publishes. Unfortunately :(
It takes usually 24h to one week. We wish we had a crystal ball for that.

**Comment by danielegobbetti** [comment] 2017-09-16 09:45
Are the upcoming events still appearing twice on the watch? If so, please try to create a new event and extract the relevant log rows. The rows you sent are dealing with removed events, therefore there's not much info available.
The event should be synced immediately after you save it in the calendar, so start watching the logs before you hit save :-)

**Comment by masakoodaa** [comment] 2017-09-16 10:27
@danielegobbetti
Yes they are. I might have spotted a pattern: Gadgetbridge syncs some events that are over three days away (I put my Pebble in airplane mode during the night and quit GB; the events are visible on the timeline after midnight because then they're in the three day range) and those seem to be the same events that get duplicated. I will do further testing.  
  
About the rows, I don't recall deleting any events. Those might be events from remote calendars. I'll disable syncing remote calendars and see if those still pop up in the logs.

**Comment by ashimokawa** [comment] 2017-09-16 10:57
Have you deleted gadgetbridge data, reinstalled it, or used the official app in between?

**Comment by masakoodaa** [comment] 2017-09-16 11:21
Here's the log extract:  
`13:41:37.384 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.21.1
13:42:35.332 [main] INFO  n.f.g.e.CalendarReceiver - got calendar changed broadcast
13:42:35.394 [main] INFO  n.f.g.e.CalendarReceiver - Syncing with calendar.
13:42:35.397 [main] INFO  n.f.g.e.CalendarReceiver - event id=479 is yet unknown to device id=1
13:42:35.418 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.add_calendarevent
13:42:35.788 [Thread-10] INFO  n.f.g.s.d.p.PebbleProtocol - BLOBDB: success (token 26589)`  
The event is only displayed once on the timeline. I suspect the duplication happens to the events four days away. I created some more events (ids 480-485) to try this theory out, I'll post the logs if those events happen to duplicate.

**Comment by masakoodaa** [comment] 2017-09-16 11:25
@ashimokawa None of those things. I haven't had the official app installed at any point.

**Comment by ashimokawa** [comment] 2017-09-19 18:03
@masakoodaa 
If you have any idea how to reproduce this, I am happy to help.
The problem is that I do not use this feature (even though I implemented most of it). Probably it is my fault but since I only created a bunch of test events I couldn't trigger anything like this..

**Comment by danielegobbetti** [comment] 2017-09-20 09:54
Update: I am also affected, but it started happening today or I was being blind before. I will dig deeper.

**Comment by bluuub** [comment] 2017-09-20 17:01
Encountered this yesterday as well. Right now everything works as expected though. I will make sure to check to report here if I find any clue the next time it happens.

**Comment by masakoodaa** [comment] 2017-09-21 09:05
@ashimokawa I disabled both calendar blacklist and ICSdroid's automatic sync and the events stopped duplicating. I will now re-enable ICSdroid's automatic sync and see if I'm able to hit the bug again.

**Comment by masakoodaa** [comment] 2017-09-22 08:15
Can confirm that they are replicating again - even the events in the local calendars. One of my test events duplicated, I'll try to spot it in the logs.

**Comment by masakoodaa** [comment] 2017-09-22 08:28
There isn't anything super exiting in the logs, just a bunch of "event is up to date", " event is yet unknown" and "event is not up to date". After those there were some `devices.action.{add,delete}_calendarevent`-lines which all seemed to succeed. I think we need a debug build that is more verbose about calendar related stuff and preferably logs the names of the events for easier identification.

**Comment by masakoodaa** [comment] 2017-11-16 09:16
I've been getting a lot of triple duplicates (triplecates?) recently. The "creating and deleting events" workaround only gets rid of one of the dupes. Any progress finding the bug?

**Comment by dentonlt** [comment] 2019-02-22 12:36
I know this is a very old thread, but I'm getting the same problem on a Pebble Time Steel. I added a calendar last week, then changed the color ... then started getting duplicates - as many as 6 or 8 of the same of event. aCal (my calendar program on Android) didn't seem to like syncing the calendar color changes I made between it and calendar.google.com ... the thread above mentioned this sort of change might be a culprit.

Doing a hard reset on the watch + forget + reconnecting didn't resolve this. Other option, of course, is to totally uninstall/reinstall Gadgetbridge. I'll try that, too, though it seems like that won't really resolve the root cause.

I'll browse the repository and try to get some log output for consideration. Thanks to those still working on this bug!

**Comment by dentonlt** [comment] 2019-04-11 23:53
Finally have some time to work on this. I'm now getting 8-10 copies of each event, so the Timeline is super-slow because of the number of events. Kinda disables my timeline =(

I'm on Android + Sony XA1 + Pebble Time Steel + Gadgebridge 0.32.4.

Just FWIW, some of the basic, non-programmed things I've tried. None of these resolved the duplication:

* Soft reset watch, reconnect
* Shutdown the watch, turn it back on, reconnect
* Hard reset watch, reconnect
* Get current Gadgetbridge, reconnect
* Drop bluetooth connections to the Pebble, reconnet
* try Non-LE connection
* re-try LE connection

I _haven't_ yet dumped my whole Gadgetbridge cache ... but I'll try that, too.

**Comment by matejdro** [comment] 2019-04-24 14:06
Has anyone been able to reliably reproduce this? I've experienced this issue and wanted to dig through it, but now I cannot reproduce it anymore after factory resetting the watch.

**Comment by dentonlt** [comment] 2019-04-24 22:00
I'm still getting duplicated events. Tried both soft/hard resets and reinstalling Gadgetbridge.

FWIW, I'm on a Pebble Time Steel, FW4.3, current Gadgetbridge release.

I've started parousing the code, but nothing looks suspect right now. There was a to-do re a date/time string parse (using a deprecated Date() call), but I'm not confident that is related to this.

I'm interested to know what hardware/firmware you're on? Also, whether you're using multiple Google Calendars? I am.

**Comment by IzzySoft** [comment] 2019-04-25 10:58
@dentonlt I'm with the same device & firmware. Had no such issue when GB ran on Android 6 (until about half a year ago), neither when I switched it to a device running Android 7 (still running there). Maybe I don't have enough events in my calendar to trigger that (rarely more than 5..10 per week here; only 1 of then recurring weekly), or maybe the Android version is a factor here (and your device runs a different one – though, OP was on 7.1.2 which is what runs on my BQ as well, so I guess we can rule this one out). Even with 7 full-day events (holidays and such) I didn't see that (and don't see it now).

I won't be able to debug/test this; just adding my 2ct in case it might become relevant (as I wrote, maybe a certain number of events must be there to trigger the bug).

**Comment by matejdro** [comment] 2019-04-25 11:00
@dentonlt did you hard reset with GadgetBridge or stock Pebble app?

**Comment by IzzySoft** [comment] 2019-08-20 12:17
As nobody's claiming the issue still persists, I'm closing this now. Should it resurface, we can reopen anytime. A clue could be "hard-resetting" the watch, as [matejdro's comment suggests](#issuecomment-486252107), quote:

> I cannot reproduce it anymore after factory resetting the watch.

**Closed by IzzySoft** 2019-08-20 12:17 UTC
Labels: bug, device pebble
