### ISSUE TITLE
Wrong summary of time slept

### ISSUE THREAD

**Issue by croisez** [Freeyourgadget/Gadgetbridge#1281] opened 2018-09-24 07:15 UTC
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
As seen on the picture below, the message: "You slept from ... to ..." is wrong.
Actually, as soon as there is more than one sleeping period in a 24 hour frame, the application displays a wrong summary of the sleeping period length. 
Some people have short resting period during the day (after diner for example).
In such case, the summary message is always fooled.
So, my conclusion is: if there are intermittent sleeping periods, 
- either another message should be displayed, 
- or the message should be hidden from the user interface.

![screenshot_20180924-085259](https://user-images.githubusercontent.com/1774281/45940342-d27c4200-bfd8-11e8-9223-bea74335489c.jpg)

#### Your wearable device is:
MiBand v2
FW 1.0.1.81
HW V0.1.3.2

#### Your android version is:
Android 7.0

#### Your Gadgetbridge version is:
0.30.0

**Comment by danielegobbetti** [comment] 2018-09-24 07:40
duplicate of #1277

**Closed by danielegobbetti** 2018-09-24 07:40 UTC
