### ISSUE TITLE
Missing latest version on f-droid.org

### ISSUE THREAD

**Issue by geripgeri** [Freeyourgadget/Gadgetbridge#950] opened 2018-01-21 15:52 UTC
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
The last few versions are missing from f-droid.org.
The latest version on f-droid.org is: ` Version 0.23.2 (116) - Added on 2018-01-03 `

**Comment by ashimokawa** [comment] 2018-01-21 16:02
We have no influence on f-droid  builds.

**Comment by TaaviE** [comment] 2018-01-21 16:05
I decided to create a Play Store release to, for one get around company policy against 3rd pray sources but secondly to provide an more up-to-date and comfortable access to the app, [here's a link](https://play.google.com/store/apps/details?id=ee.aegrel.gadgetbridge).

It's a bit modified to be suitable for Google Play, all changes are visible [here](https://github.com/TaaviE/GadgetBridgeUpdate).

**Comment by ashimokawa** [comment] 2018-01-21 16:18
Please DO DOT release on google play.

**Comment by IzzySoft** [comment] 2018-01-21 16:51
@TaaviE that only will cause confusion. I second @ashimokawa with full backing: we've discussed that in length already in the past (see #480: this is free and open source software and most of us feel it doesn't belong into a walled garden). As for faster updates, there's always be my repo as soon as the signing issue is solved.

**Comment by TaaviE** [comment] 2018-01-21 18:03
I've read that issue and I'm sorry if this rubs you the wrong way, but I'm opposed to further limiting people's freedoms by not making some software more accessible. If you're not willing to maintain a Google Play presence then that's okay, but I have the freedom to maintain one. It's also worth noting that the listing complies with GB's license fully and the builds are 100% reproducible but just signed with my key.



> This is free and open source software

And remains to be so. 

> As for faster updates, there's always be my repo as soon as the signing issue is solved.  

Given the instability of the whole F-Droid infrastructure I and many others can't be sure of that. Can't even be sure their keys aren't compromised.

**Comment by IzzySoft** [comment] 2018-01-21 19:12
Taavi, it doesn't do any good to antagonize the original developers just because you feel you're right. It's their work, so they should have a say in that. If a developer doesn't wish for a certain distribution channel, you should respect that (as do I in my repo – and yes, there were several denials where I could also simply have stated "the license allows for and this is free and open source software so you cannot forbid me"). One might "stick to the letter" and still violate the spirit.

> Given the instability of the whole F-Droid infrastructure we can see

We see that the official repo currently has problems with their build server, yes. Stabbing in their backs that way won't help fixing those issues (better donate or help them out in other ways). My repo is around for how long now, and what issues are you claiming according to its "instability" – or that of Guardian or any of the other repos for that?

> And neither can we even be sure your signing keys aren't compromised

Apart from the fact that I'm not signing anything (but use tha packages signed by their resp. developers): with your key we can be sure of that? And what makes you more trustworthy in this context? I don't want to start a flame war here – but the developers, backed by many users, decided for good reasons to stay OFF playstore. I wish you'd respect that.

> replacing the proprietary OEM spyware commonly used

If someone really cares about that, such person should really look beyond playstore. An infrastructure build for the sake of advertisements (guess why you're never warned about e.g. the internet permission when installing something from Play) I should trust when it comes to privacy?

----

I have to give you credits for pointing out things pretty clearly with the description of your playstore listing – so at least noone can confuse it with an "official release". That doesn't mean we're happy with it.

Apologies if the above sounded harsh, but it just blew my hat. You might mean well but, forgive my directness, it sounds rather arrogant.

**Comment by TaaviE** [comment] 2018-01-21 19:34
@IzzySoft 
> good to antagonize the original developers

Never been my intention, but forcing someone to stick to a certain distribution channel is just as antagonizing. "Spirit of FOSS" is definitely not forcing the user's hand. 

> Apart from the fact that I'm not signing anything (but use tha packages signed by their resp. developers): with your key we can be sure of that? And what makes you more trustworthy in this context? I don't want to start a flame war here – but the developers, backed by many users, decided for good reasons to stay OFF playstore. I wish you'd respect that.

Good and you can keep using the F-Droid binary. But I wish you'd respect that **not everyone can**, wants to or knows how to.

**Comment by IzzySoft** [comment] 2018-01-21 20:18
@TaaviE I've said my words, I won't discuss this further.

**Comment by danielegobbetti** [comment] 2018-01-21 21:27
@TaaviE we are off topic, the discussion about Play Store release is #480 as already mentioned.
I reviewed the link to the play store release of the app you built based on a fork of Gadgetbridge, and have a few observations. Please consider this message as a statement by all the core developers of the project (that is: @ashimokawa , @cpfeiffer and me):
1. You are listing the wrong license in the text: this project's license is **A**GPLv3, not GPLv3 as you incorrectly state. We urge you to change this.
1. Please make it clear - if possible in the application title - that the application you released on the play store is not an official release by the project.
1. Please add in the application description the devices that are supported. Technically speaking you could use the fastlane metadata we are already publishing on our official repository as long as you intend to keep the codebase compatible.
1. We acknowledge that you are not currently violating the project's license by publishing a derivative work to the play store, but we are not happy about this.

**Comment by TaaviE** [comment] 2018-01-21 21:49
> You are listing the wrong license in the text: this project's license is AGPLv3, not GPLv3 as you incorrectly state. We urge you to change this.

Thank you, I fixed that typo.

> Please add in the application description the devices that are supported. Technically speaking you could use the fastlane metadata we are already publishing on our official repository 

I'm not a copyright lawyer so I'd rather avoid mentioning any trademarked names or explicit compatibility with anything unless there's clear proof I may do so. 

> as long as you intend to keep the codebase compatible.

I intend to keep the codebase compatible as much as possible.

> Please make it clear - if possible in the application title - that the application you released on the play store is not an official release by the project.

I will add it to the title too.

I suggest either an issue or e-mail could be used for further communication about the Play Store release.

**Comment by danielegobbetti** [comment] 2018-01-22 08:18
> I suggest either a new issue or e-mail to be used for further communication about the Play Store release.

There is no such thing as a "Play Store release" of this project at the time of this writings.

**Comment by danielegobbetti** [comment] 2018-01-22 12:34
@geripgeri apparently f-droid built the new version, so hopefully this issue can be solved soon (TM).

I tried to summarize our insights on how to follow f-droid progress (unfortunately we have no secret access to other info, we just learned where to look) [on our wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki/When-will-a-new-release-appear-on-f-droid). Feel free to add missing pieces or reformulate some passages.

**Comment by IzzySoft** [comment] 2018-01-22 13:37
@danielegobbetti the last paragraph could possibly could be rewritten from "no idea" to "some idea" – especially as it includes, as the last steps, "updated the index and made the apk available". Following options (let me know if I shall add them, and which):

* Perform a manual refresh of the repo index(es) in your F-Droid client. If you have GB installed, you should be notified about an available update. If not, you still can search for the app and open its detail page – available builds should be listed.
* Visit the [Gadgetbridge web page on the F-Droid repo](https://f-droid.org/packages/nodomain.freeyourgadget.gadgetbridge/). In the "Packages" section, just below the blue "Download F-Droid" button, available packages are shown. What's listed here should reflect the latest index build.
* Download the `index.xml` manually and parse it (oops)

If you want to find out whether F-Droid has published any new apps or updates within a given time frame, check with the [IzzyOnDroid Repo Browser](https://apt.izzysoft.de/fdroid/index.php?repo=main). Here you can filter by "added since" (new updates) and/or "updated since" (updates to already existing apps) to get an idea on "successful activity" in this context (the repo indexes are updated once per day, so they might not always reflect latest activities). Not only for the F-Droid main repo, by the way :wink:

**Comment by danielegobbetti** [comment] 2018-01-22 15:01
@IzzySoft please go ahead and add anything you deem interesting to the page :-) (Also: feel free to link it from the sidebar if you think it is in a good enough shape).

**Comment by IzzySoft** [comment] 2018-01-22 17:16
@danielegobbetti Done – with adding that page to the FAQ section in the sidebar. Only replaced that last paragraph on this article, everything else already looked perfect :wink:

**Comment by danielegobbetti** [comment] 2018-01-23 06:33
Fdroid published versions 0.24.0 and 0.24.1, I'm closing this.

**Closed** 2018-01-23 06:34 UTC

**Comment by geripgeri** [comment] 2018-01-23 07:33
Thank you for the information.
