### ISSUE TITLE
please encourage discussions and feedback!

### ISSUE THREAD

**Issue by d-p** [Freeyourgadget/Gadgetbridge#319] opened 2016-06-02 16:16 UTC
Hello,
I see "Please do not use the issue tracker as a forum, do not ask for ETAs and read the issue conversation before posting." in the Readme.

This is the problem. But no solution is presented.

I find it conflicting with:

"Contributions are welcome, be it feedback, bugreports, documentation, translation, research or code."

I am new to Gadgetbridge, and I for sure I have questions that do not are issues, not sure if are feedbacks...

Thanks,
Daniele

**Comment by danielegobbetti** [comment] 2016-06-02 19:31
Hello and welcome. I'm sorry you find our readme confusing. To this end, I believe a constructive way to approach the issue is reformulating what you find confusing. The readme file is like any other file of the repo, so you can open a pull request with the changes you deem appropriate: then we will continue the discussion in that pull request.

For instance, the translation service we use is listed immediately below the snippet you quoted, for documentation there's the github wiki and feedback and issue should go to the issue tracker, after having checked if the issue isn't present already.

Looking forward to your proposal of a better formulation of the readme!

**Comment by d-p** [comment] 2016-06-02 20:52
> Looking forward to your proposal of a better formulation of the readme!

Thanks Daniele for the warm welcome!

My reasoning is the following:
- you state to not use the issue tracker like a forum
- I guess because in the past someone abused the issue tracker
- so you want to use the issue tracker not as a forum
- but you do not offer an any alternative!

Maybe the popularity of Gadgetbridge has reached the point that
there is the necessity of a user forum or (better for me) for a user 
mailing list or irc channel.

I think you will agree that  it does not make sense to me to fork
the repo announcing the mailing list!

If you think that you can manage the project without a forum,
it will be fine to rephrase the readme to something more
positive like: we can not offer estimate, but if you have any
issue or suggestion please search the already present
issue list, if nothing exist please open a new one.

Everything in the project makes me think that you are really
open and committed, for example, the wiki has a lot of
useful content, there where new releases in a short
timeframe, the issues are well labelled, you replied 
in a very short time in a very friendly manner...

Maybe the only thing missing is a "forum"!

Let me know what you think, and I will be happy
to propose a patch for the latter (no forum, feel
free to open an issue after a check).

Thanks and best,
Daniele

**Comment by cpfeiffer** [comment] 2016-06-02 21:47
You make very good points, thank you. So far we have avoided to open a forum because we were afraid of the extra load. Maybe you're right and we are enough people to have a more or less self sustaining forum.

Do you have a suggestion for a forum? Self hosting is out of the question, it is way too much trouble due to spammers.

There's reddit, stackoverflow, disqus, Usenet, ...?

I didn't search for github connected forums yet, that might make it easier for us all.

**Comment by IzzySoft** [comment] 2016-06-03 06:11
@cpfeiffer SO is not a forum, it's a Q&A site – discussions aren't welcome there (except for in chat). Disqus is rather a comment system for blogs. XDA might be a place to consider: several Android app projects have their own "area" there. Checkout [this video](https://www.youtube.com/watch?v=cN-QVwK7T3s&html5=1) (just 1:25) – and [here](http://forum.xda-developers.com/android/apps-games/) would be the "starting point".

Before you ask: I have no experience with Xda:DevDB, I'm just a normal user at XDA running a low profile.

**Comment by ashimokawa** [comment] 2016-06-03 07:43
We could also reactivate the gitter chat. And hope people help themselves. I can only speak to myself, but most probably I won't be too active in a user forum, as Gadgetbridge related research/programming is already eating up most of my free time.

**Comment by danielegobbetti** [comment] 2016-06-03 08:14
Adding a second place for discussion may yield to 
- a higher involvement by the community, or
- even more confusion for new users (creating new accounts, doubts like "where should I post this?") and more work regarding triaging/moderating/answering questions that would pop up in two separate places.

Honestly I can't predict which outcome is more likely, hence my proposal would be to add the needed labels to github issues ("feedback", "question", everything that's needed) and reformulate the readme, wrt the info about how to provide feedback

As already said: time spent dealing with questions is time not spent developing. Both activities are important! We should find the most effective way to deal with this situation, and I doubt that it is a separate place for asking questions.

**Comment by IzzySoft** [comment] 2016-06-03 08:30
I have to agree with @danielegobbetti and @ashimokawa here on "divided loyalities" (time spent in discussions will be taken from time spent on development), so the most effective way should be chosen.

If someone wants to create a "Gadgetbridge forum from users for users", and act as a bridge to the project here (bundling things that would make up issues – while keeping "generic discussions" in said forum), I guess that would be welcomed – and could be done by someone experienced enough with Gadgetbridge to be able of "bridging" while not necessarily being a developer. GB devs of course could drop in now and then if they like – but should not be burdened with "binding forum responsibilities" ;)

**Comment by danielegobbetti** [comment] 2016-06-04 15:15
I added a paragraph in the readme. This, together with the newly created issue labels, should solve this issue.
I'd like to hear back from @d-p if he is satisfied before closing this issue.

**Comment by d-p** [comment] 2016-06-05 20:00
Thanks @danielegobbetti, very satisfied!

**Comment by d-p** [comment] 2016-06-05 20:04
By the way I also appreciated the conversation. For future reference to the list of the software for the community I will suggest to give e try to https://www.discourse.org/faq/
Best

**Closed** 2016-06-05 20:04 UTC
Labels: discussion
