### ISSUE TITLE
MiBand: two devices listed in main Gadgetbridge activity

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [Freeyourgadget/Gadgetbridge#23] opened 2015-04-20 15:23 UTC
Hi there,
I installed version 0.31 from F-Droid and managed to connect the miband initially (by reproducing the steps from the readme) and get it to vibrate on the debug test notifications as well as notifications from other apps (although those are a bit long, but I guess that will be configurable in the future).

However, two mibands are listed in the main activity. If I tap the top one, it connects, if I tap the second one, the top one connects. So all seems to work fine, except for this "graphical issue".

Sidenote: All other apps that would want to communicate (original MiBand app, and OpenBand app, are uninstalled). The MiBand is however used by the Smart Unlock function of Lollipop.

**Comment by ashimokawa** [comment] 2015-04-20 16:57
Could it be that your MiBand is paired? I mean if you go to the Android Bluetooth Settings is it listed as paired?
That would explain your issue.
There is an evil hack that adds the Miband to the list of paired devices in Gadgetbridge since I assumed it cannot be paired.

**Comment by 1337sup3rh4x0r** [comment] 2015-04-20 18:24
Yes it's paired.

**Comment by ashimokawa** [comment] 2015-04-20 19:37
Interesting, how did you do that?

**Comment by 1337sup3rh4x0r** [comment] 2015-04-20 21:44
It might habe happened by adding it as trusted unlock device via the dialog in the native miband app. Maybe that somehow put the band in a mode that enabled pairing. I'll see if I can reproduce this tomorrow

**Comment by cpfeiffer** [comment] 2015-04-20 22:03
Thanks, please report back if its fixed with 0.3.2.

**Comment by chrisvella** [comment] 2015-04-30 03:01
I can confirm the issue is fixed. I previously had this problem.

My firmware version is 1.0.9.14. Running Lollipop.

**Comment by ashimokawa** [comment] 2015-04-30 06:44
OK, I'll close this.
Please reopen if this is still a case for someone else.

**Closed by ashimokawa** 2015-04-30 06:44 UTC
Labels: mi band
