### ISSUE TITLE
Cant set miband call repetitions number- app crashes.

### ISSUE THREAD

**Issue by domovoirt** [Freeyourgadget/Gadgetbridge#285] opened 2016-04-16 05:30 UTC
Subj

**Comment by cpfeiffer** [comment] 2016-04-16 06:11
Works for me. Which version? Do you have a logfile?

**Comment by domovoirt** [comment] 2016-04-16 18:34
Log.
16 апр. 2016 г. 9:11 пользователь "Carsten Pfeiffer" <
notifications@github.com> написал:

**Comment by cpfeiffer** [comment] 2016-04-16 21:25
I'm sorry, but there is no log!?

**Comment by domovoirt** [comment] 2016-04-16 21:33
Sorry. Where can I find needed log?
17 апр. 2016 г. 0:25 пользователь "Carsten Pfeiffer" <
notifications@github.com> написал:

**Comment by cpfeiffer** [comment] 2016-04-17 06:07
There is a page in the wiki describing how to enable logging. Basically you have to enable it in the settings and restart gadgetbridge, possibly via force-stop when the Quit option does not terminate it completely.

On next start you will find the log file in/sdcard/Android/data/nodomain/freeyourgadget/....

**Comment by cpfeiffer** [comment] 2016-04-24 22:15
Sorry, closing as invalid because
- I cannot reproduce it
- nor do I know the version with which you experienced it
- nor do I have a logfile or any other indication of might happen

Feel free to add more information; then we can have another go at it.

**Closed by cpfeiffer** 2016-04-24 22:15 UTC
Labels: invalid, mi band

**Comment by cpfeiffer** [comment] 2016-04-25 22:07
After some discussion and digging, we changed pretty much all access to SharedPreferences to avoid type conversion errors with it. This should fix your issue as well.
