### ISSUE TITLE
Amazfit Bip: Support Export of gpx

### ISSUE THREAD

**Issue by bioschaf** [Freeyourgadget/Gadgetbridge#952] opened 2018-01-23 07:14 UTC
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Is it possible to export GPS data from the Amazfit Bip? That way, it could be used as GPS tracker. 

#### Your wearable device is:

Amazfit Bip

#### Your android version is:
lineage OS 

#### Your Gadgetbridge version is:
latest

**Comment by ashimokawa** [comment] 2018-01-24 08:50
We have that working in bip-wip branch. It needs some cleanup but basically mostly works

**Comment by salvisdagis** [comment] 2018-02-15 19:57
Is there any posibilities to export GPX or TCX data from Amazfit Bip?

**Comment by danielegobbetti** [comment] 2018-02-15 20:10
The mentioned branch exports data in gpx format.

**Comment by pietrorim** [comment] 2018-02-21 23:06
The application Mi Fit reads the tracking data from Amazfit Bip to a Android smartphone, but not allows to export them as GPX or TCX data. Anyone haves suggestions in that field?

**Comment by salvisdagis** [comment] 2018-02-22 06:28
With bip-wip failed to retrieve workouts, so now I use Notify & Fitness for Amazfit, which can greatly export TCX

**Comment by danielegobbetti** [comment] 2018-02-22 06:37
@salvisdagis sharing logs of our branch showing the errors of Gadgetbridge would help more in fixing issues, but it's good - if off topic - that you found a working solution.
The merge is not released exactly because it needs more work and polish, having said that it works for me. Which firmware were you on when you had issues?

**Comment by salvisdagis** [comment] 2018-02-22 06:54
I'm use Firmware v0.1.0.86.
After push refresh button I see only "Fetching activity data", but after that Activities frame always is empty. I don't know why. I'm also run in Debug mode, but breakpoint never stops in "lucky place".
It would be very nice if I could get GPX with bip-wip, because I have found that the Amazfit bip GPS attitude (after export to TCX) is very inaccurate / noisy and in my case (running on a flat area) it's better not to use it at all or to put a strong filter, a mask for an attitude, etc.

**Comment by danielegobbetti** [comment] 2018-02-22 12:08
Try going to the debug screen and pushing button "test new functionality"

**Comment by pietrorim** [comment] 2018-02-22 17:41
I try to use the application "Notify & Fitness for Amazfit"  for exporting the tracking  files in gpx format, but doesn't  work. These files are present in the telephone internal memory as files or as database?
What is the directory containing these files in the Android system? There are other applications for making the conversion to the gpx format? Thank you for the attention

**Comment by danielegobbetti** [comment] 2018-02-22 18:54
We cannot provide assistance for other apps. I'm clearing this thread up to avoid confusion.

**Comment by andrewheadricke** [comment] 2018-03-13 11:10
Just received my Amazfit Bip and was surprised GPS log exports has so little support across the different apps Bip related apps.  

Initially, I was just running the vanilla GadgetBridge on F-Droid and somehow there existed a couple of BIP_XXXX.log files which contained GPS log data.. but i'm not sure how that happened, and was unable to recreate them.

So I managed to checkout `bip-wip` branch and get it compiled... reading the comments above I was able to use the debug screen to download the activity into the "Activities" tab.  However from there I am stuck.. any advice on how to export to GPX from there?

**Comment by danielegobbetti** [comment] 2018-03-13 11:29
The gpx files are in the same folder where you saw BIP_XXX.log entries, the prefix is ``gadgetbridge-track-`` followed by the date/time.

Additionally, if you tap an entry in the "Activities" tab it will fire an Intent that should list all apps on your android device which is capable of displaying gpx files (Osmand works well for me).

Of course there is no gpx file for "treadmill" activities.

**Comment by andrewheadricke** [comment] 2018-03-13 11:39
I must have screwed something up, cause GadgetBridge is no longer creating those BIP_xxx.log files and doesn't appear to be creating the gpx files either.  

The gadgetbridge.log and db exports still appear there though.

**Comment by danielegobbetti** [comment] 2018-03-13 12:36
Does tapping an activity work?

**Comment by andrewheadricke** [comment] 2018-03-13 12:41
Tap does nothing, a long press brings up the delete which works.  

I have breakpoints on the "gadgetbridge-track-" and its not even hitting the breakpoint.

**Comment by danielegobbetti** [comment] 2018-03-13 12:44
Do you see a track plotted on the watchscreen for these activities?

**Comment by andrewheadricke** [comment] 2018-03-13 12:44
Yup

**Comment by danielegobbetti** [comment] 2018-03-13 12:46
Then please share your firmware version, as I guess there is something different/new in the message contents.

**Comment by andrewheadricke** [comment] 2018-03-13 12:48
Its the last stable firmware `0.1.0.86`

**Comment by andrewheadricke** [comment] 2018-03-13 13:02
I'm not an Android dev so forgive me for not just fixing the issue.. on line 158 of AbstractFetchOperation.java it cheks that the Metadata = `MiBand2Service.RESPONSE_FINISH_SUCCESS` which is [16,2,1], but my MetaData = [16,2,4]

Which is causing the success = false.

Is the MiBand2 response the same as the Bip?

**Comment by andrewheadricke** [comment] 2018-03-14 13:31
Ok, at the line 187 mentioned above I have made these changes..

```
Calendar cal = Calendar.getInstance();
int dstoffset = cal.get(Calendar.DST_OFFSET);

cal.setTimeInMillis(BLETypeConversions.toUnsigned(buffer.getInt()) * 1000);
cal.add(Calendar.MILLISECOND, -1 * dstoffset);
summary.setStartTime(cal.getTime());
```

And it appears to be working fine.  I'm not sure why the BIP is returning values not inclusive of DST, maybe thats just how it is.  Hope this helps.

**Comment by andrewheadricke** [comment] 2018-03-15 00:47
Sorry to spam this thread.. I also had to convert the GPX Exported track point times into UTC format to be compatible with sites like Strava.

**Comment by piggz** [comment] 2018-03-21 12:44
I tried out the bip-wip branch, but I cant get this version to do the application level auth/pair step.  If I checkout master or 0.25.0 and compile that one, it does do the auth ok.  I tried rebasing the branch on master (and fixing the conflicts) but it too wouldn't do the auth step.  Is this a known issue? Am I doing something wrong?

Out of interest, I was wondering if I could get some tips on doing the GATT auth steps.  Im looking to write an app to support the bip in C++ for the SailfishOS and linux desktops.  I think ive worked out that there is a characteristic write to the auth uuid, handle 0x004c by looking at your source code, but would appreciate any insight you've got on this.

Cheers

**Comment by swiss5555** [comment] 2018-03-21 14:08
hi, i was able to export tracks to gpx format. However is missing the heart rates in that file.

**Comment by swiss5555** [comment] 2018-03-21 17:43
hi, i dont want to make pull requests etc, so i paste the code here to fix missing HR in GPX. (just notice that Im not a java developer rather .NET :P )

`String fileName = FileUtils.makeValidFileName("gadgetbridge-track-" + DateTimeUtils.formatIso8601(summary.getStartTime())+".gpx"); // please add extension to the file
`


 `private boolean includeHeartRateByTime = true;`



```
private void exportTrackpointExtensions(XmlSerializer ser, ActivityPoint point, List<ActivityPoint> trackPoints) throws IOException {
        if (!includeHeartRate) {
            return;
        }
        int hr = point.getHeartRate();
        if (!HeartRateUtils.isValidHeartRateValue(hr)) {
            if(!includeHeartRateByTime) { return; }
            Date time = point.getTime();
            ActivityPoint closestPointItem = null;
            long lowestDifference = Long.MAX_VALUE;
            for (ActivityPoint pointItem : trackPoints) {
                int hrItem = pointItem.getHeartRate();
                if(HeartRateUtils.isValidHeartRateValue(hrItem)) {
                    Date timeItem = pointItem.getTime();
                    if (timeItem.after(time) || timeItem.equals(time)) continue;

                    long difference = time.getTime() - timeItem.getTime();
                    if (difference < lowestDifference) {
                        lowestDifference = difference;
                        closestPointItem = pointItem;
                    }

                }
            }
            if(closestPointItem != null) {
                hr = closestPointItem.getHeartRate();
                if (!HeartRateUtils.isValidHeartRateValue(hr)) {
                    return;
                }
            }


        }
        ser.startTag(NS_DEFAULT, "extensions");

        ser.setPrefix(NS_TRACKPOINT_EXTENSION, NS_TRACKPOINT_EXTENSION_URI);
        ser.startTag(NS_TRACKPOINT_EXTENSION_URI, "hr").text(String.valueOf(hr)).endTag(NS_TRACKPOINT_EXTENSION_URI, "hr");

        ser.endTag(NS_DEFAULT, "extensions");
    }
```

**Comment by pietrorim** [comment] 2018-03-21 18:33
I'm sorry, but I'm still a newbie. I use Amazfit bip V0.1.0.86 and Gadgetbridge 0-25-5-5 apk, but exporting the database (using debug mode) I can find in the directory nodomain.freeyourgadget.gadgetbridge only these files: amazfitbip_date_hour.log  and Gadgetbridge_date_hour.
Tapping on these files I'm not able to see a gpx path on GPS applications as Osmand or Oruxmaps. Thanks for your suggestions.

**Comment by swiss5555** [comment] 2018-03-21 19:39
are you using Gadgetbridge  from google store or compiled from github? if from google then this export will not work for you. If from github you need to check if you using master branch or if bip-wip branch . If you using from master branch that will not work for you as well. You need to download and compile bip-wip branch and then go to debug option and click the latest button. then you will be able to see activities in mobile application.

**Comment by swiss5555** [comment] 2018-03-22 07:40
if you are not able to compile the apk from code. Im sharing already compiled version together with added HR to GPX (my changes) : https://drive.google.com/open?id=15P4isW4b1dVHJE3cJZqfCu-O-Rn89VOt

**Comment by danielegobbetti** [comment] 2018-03-22 10:02
Please remember that this is an issue tracker **for the project development/developers**, not a user support forum.

**Comment by pietrorim** [comment] 2018-03-23 09:27
The last thing... I hope. I cannot read or copy in my PC the gpx tracks contained in the directory android/data/nodomain.freyourgadget.gadgetbridge/files (message: file access denied). The same happens for the same gpx tracks contained in the directory android/data/net.osmand/files/tracks. These files are not empty and are correctly completed in the OsmAnd app.  Thanks in advance.

**Comment by swiss5555** [comment] 2018-03-23 10:16
maybe the appliction which you are using to browse the files dont have permission to that location. im using Total commander android on the phone. and im able to access the files in both, OSM and gadgetbridge location.  however this seems to be rather phone permission issue. eg. i just open endomondo from the browser in the phone, select my profile, and then i see  button on the page to upload traning (you need demand PC version of the site). then I just click select traning and navigate to exported file. select it, and i am happy becouse :) becouse I just use phone, no needs for upload to PC first.

**Comment by swiss5555** [comment] 2018-03-30 13:31
there is no possibility to export track anymore after latest upgrade of the watch to version  0.1.1.14

**Comment by danielegobbetti** [comment] 2018-03-30 15:47
Does this happen for tracks recorded with new firmware, or also old tracks are not exposed anymore?

**Comment by swiss5555** [comment] 2018-03-30 18:02
there is something strange. becouse after downgraded FW to 0.1.0.86 still is not possible to parse datas.

I tryied to debug that from last 2 nights, without success.
Basically onCharacteristicChanged is triggered by UUID_UNKNOWN_CHARACTERISTIC4, with 15 bits, and that is OK.

Then I receiving notification from UUID_CHARACTERISTIC_5_ACTIVITY_DATA, and buffer is filled up with 127bits.

Then UUID_UNKNOWN_CHARACTERISTIC4 is calling again with 3 bits, 16.2.4 and then UUID_UNKNOWN_CHARACTERISTIC4  is called again with 15bits but expectedDataLength is equal to 0.

When I trying to parse that 127 bits manually with  ActivityTrack parse(byte[] bytes) throws GBException {

I get exception (lenght exception).

I wondering is this is only my device, or that also for you is not working?

**Comment by ashimokawa** [comment] 2018-03-30 18:23
The data on the device does not change when up or downgrading. So IF the data recorded with .14 is incompatible then it is still incompatible when downgraded. We are aware of two different versions which we both support. I will record data with .14 tomorrow and test.

**Comment by ashimokawa** [comment] 2018-03-31 17:35
I can confirm that it is broken with Firmware 0.1.1.17

**Comment by ashimokawa** [comment] 2018-04-01 22:27
It wasn't a firmware issue and should be fixed in master (yep, bip-wip has been merged by now)

Please not that you have to swipe to sync in the "Activities" overview (does no longer work in the debug activity) and that there will be no proper indication whether syncing is done etc.

**Comment by andklv** [comment] 2018-04-04 23:00
hi
I got 0.25.1 from f-droid website, and I can see log files only in Android/data/nodomain.... no GPX files. What I do wrong? a newer Gadgetbridge version required?

**Comment by danielegobbetti** [comment] 2018-04-05 05:36
Please read the comments before posting. This feature is not released yet (first(!) comment!)

**Comment by andrewheadricke** [comment] 2018-04-06 11:51
Great work devs.. GPS downloading is working well on `master` now.

Looks like there is still some issues with the lack of `.gpx` extension, and the exported XML still has some issues.. I found it really handy to have the option to be able to reset the `last sync time` in gadgetbridge so that I can redownload past activities if needed.  I may look at creating a PR for that.

**Comment by pietrorim** [comment] 2018-04-06 16:31
Previously I used  the compiled bip-wip version by swiss5555 (including the heart rate changes)  that worked perfectly. But , after the actualisation of Amazfit Bip to V0.1.1.17, the old gpx files continue to be in the right latitude&longitude position ; instead the new gpx files (after the actualisation date) have a constant  lat&lon shift from the true position and also the track date is reported 2 days later. 
So I come back to  Gadgetbridge 0.25.1 (from F-droid) but  the GPS export does'nt work (I cannot find any gpx track in the directory Android/data/nodomain.freeyourgadget.gadgetbridge/files). Maybe the Gadgetbridge master version of F-droid is still not updated to the more recent changes introduced?

**Comment by danielegobbetti** [comment] 2018-04-06 18:01
@pietrorim the feature has not been released yet, as clearly written in the first comment.

**Comment by andklv** [comment] 2018-04-16 02:38
just got 0.26 from f-droid.
My bit cannot connect to the app (it could in previous versions).

**Comment by piggz** [comment] 2018-04-16 15:42
I too can't get this version to connect. Start discover, finds watch, clic!, Says it's creating bond, but never pops up the message on the watch, and gadget bridge just sis waiting.

**Comment by danielegobbetti** [comment] 2018-04-16 16:28
@andklv and @piggz unfortunately this release is having issues on older android versions. The fix is already in master and a release should follow soon.

**Comment by piggz** [comment] 2018-04-16 21:35
Confirmed working after building from source. Helped debug my own bip app too :)

**Comment by danielegobbetti** [comment] 2018-04-17 10:02
Basic support was released, hence I am closing this issue.

**Closed by danielegobbetti** 2018-04-17 10:02 UTC
Labels: device amazfit bip, not a bug, task, user interface / UX

**Comment by szilardx** [comment] 2018-06-27 13:20
I have been using this app successfully with an Amazfit Bip. My only concern: the gpx export of the workouts miss the beginning part, thus the workout is shorter. 
Exporting tcx from other apps shows the missing part. 
Comparing the tcx with gpx shows that the bip might record the activity with a bad timecode at the beginning - same timecode for a few points at the beginning. 
I can provide files in email. 
Should I open a new issue for this? 
Thanks!
