### ISSUE TITLE
Doesnt received data correctly from miband 1s

### ISSUE THREAD

**Issue by marioalvarado7** [Freeyourgadget/Gadgetbridge#701] opened 2017-05-25 22:00 UTC
* Your problem is:
- Statistical data are not received (steps, heart rate and hours of sleep)
- error buffering activity data: remaining bytes 4, recived 5 (always receive one more)
* Your usable device is:
- MiBand1s,
- FW: 4.16.11.15,
- HR: 1.3.76.22
* Your version for Android is:
- Android 6.0.1
* Your version of Gadgetbridge is:
- 0.19.2
![whatsapp image 2017-05-25 at 17 50 05](https://cloud.githubusercontent.com/assets/26925725/26472418/fc4ce4ca-4173-11e7-9d08-cfaf6c64b54b.jpeg)

**Comment by marioalvarado7** [comment] 2017-06-01 20:07
...?

**Comment by iamserious** [comment] 2017-08-05 09:34
I have the same issue with a Mi Band 1 (without "s"). Only live acivity is working.

**Comment by zedascouves** [comment] 2017-08-05 10:48
Add another one to the list. I'm also having this problem. My details are:

- MiBand1s
- FW: 4.16.11.15
- HR: 1.3.76.22

Your version for Android is:
- Android 5.1.1 (Cyanogen 12.1 based ROM)

Your version of Gadgetbridge is:
- 0.19.4

**Comment by iamserious** [comment] 2017-08-05 11:13
Some more informations from me.

- [x] I have read the wiki
- [x]  I have searched for similiar issues

My Details:

- MiBand 1
- FW: 1.0.15.0

Device
- Moto X 2014
- LineageOS
- Android Version: 7.1.2

What I tested already:
- older Version of GB (till Version 0.19.2 -> no earlier version in Fdroid)
- tested different setting under "device specific setting"
- different smart phone (same tests on an Nexus 4 Stock 5.1.1 w root)

--> fetching data does not work with any of this settings

What work:
- parining with band
- connecting with band
- live activity

Log attached:
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1202321/gadgetbridge.txt)

**Comment by Olivier4murs** [comment] 2017-09-15 10:51
Same problem for me :

    MiBand1s
    FW: 4.16.11.15
    HR: 1.3.76.22

Your version for Android is:

    Android 7.1.2 (AOSP Jiayu S3)

Your version of Gadgetbridge is:

    0.21.0

What work:

- pairing & connecting

- live activity

- notifications

Problems:

- no data received

- same errors like first post

- sometimes it doesn't connect automatically. I have to click on the device line to make it connect.

Can we provide you additional logs to fix this problem ?

**Comment by nixi-awoo** [comment] 2017-09-24 06:28
I had the same issue. Note that you all use FW 4.16.11.15 on version 1S, which is the cause of this issue. It can be fixed by flashing one of the [recommended firmware versions](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Information#mi-band-1s-firmware-4x).

I flashed the 4.16.4.22 firmware extracted from the mi fit apk version 2.1.6. I used [apktool](https://ibotpeaches.github.io/Apktool/) for the firmware extraction. Everything works perfectly now.

**Comment by forkoz** [comment] 2017-11-03 13:09
Clearing the DB helped the data sync too. Especially when syncing to multiple apps. I have had no issues since then.

**Comment by zedascouves** [comment] 2017-11-03 18:14
@forkoz did you downgrade the FW?

**Comment by forkoz** [comment] 2017-11-07 13:24
I upgraded to try it out and get this error. Also remaining 8, received 9. Everything else in the firmware appeared to work and other apps could sync fine.

The magic byte is wrong? https://pastebin.com/nwRX4swb Then it crashes: int nodomain.freeyourgadget.gadgetbridge.service.devices.miband.operations.FetchActivityOperation$ActivityStruct.activityDataRemainingBytes' on a null object reference

[gadgetbridge-2017-11-07.1.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1450104/gadgetbridge-2017-11-07.1.log)

**Comment by forkoz** [comment] 2018-01-01 02:25
Can be closed now, the commits fixed it.

**Closed** 2018-01-01 09:58 UTC
Labels: device mi
