### ISSUE TITLE
Add Google Fit support. 

### ISSUE THREAD

**Issue by RustyRaptor** [Freeyourgadget/Gadgetbridge#351] opened 2016-07-01 00:54 UTC
It would be nice to add support for google fit. I understand this app is meant to avoid sending data to anyone but some people use it as an alternative simply because the official app doesn't support anything older than android 4.4. Maybe just make it optional.

**Comment by relan** [comment] 2016-07-01 01:42
Free software should _not_ be tainted by proprietary software support. I hope Gadgetbridge will never do this.

**Comment by IzzySoft** [comment] 2016-07-01 06:21
This is already dealt with in #248. And to [quote on e of our devs](https://github.com/Freeyourgadget/Gadgetbridge/issues/248#issuecomment-220355165):

> We will not add this directly to Gadgetbridge, that's for sure. We could support this scenario through other means, though, e.g. through export and an additional sync tool.

**Comment by danielegobbetti** [comment] 2016-07-01 14:40
Duplicate of #248 .
Further, as correctly already reported, this is a WONTFIX for the main app.

**Closed by danielegobbetti** 2016-07-01 14:40 UTC
Labels: duplicate, wontfix
