### ISSUE TITLE
Gadgetbridge continuously crashes

### ISSUE THREAD

**Issue by tecufanujacu** [Freeyourgadget/Gadgetbridge#876] opened 2017-11-08 15:12 UTC
After the last update Gadgetbridge continuously crashes and when it works for a bit of time it doesn't automatically reconnect in case of disconnection. I'll try to record a log.

Pebble Steel
CM 13 | Android 6.0.1
Gadgetbridge 0.22.2

**Comment by ashimokawa** [comment] 2017-11-08 18:21
Duplicate of #868  ?
We really need a log

**Comment by ashimokawa** [comment] 2017-11-08 18:21
Duplicate of #868  ?
We really need a log

**Comment by ashimokawa** [comment] 2017-11-08 18:21
Duplicate of #868  ?
We really need a log

**Comment by tecufanujacu** [comment] 2017-11-08 22:36
Possible, for me this happened with the last update, with Gadgetbridge 0.22.2.
I'll provide a log.

**Comment by tecufanujacu** [comment] 2017-11-09 16:17
Ok, I took the log.
After a disconnection Gadgetbridge hasn't been able to automatically reconnect, I pushed the connect button on the notification area and Gadgedbridge has crashed, after i restarted Gadgetbridge it has been able to reconnect. This is what happens every time.

Please could you also check the issue #685 ? I know that it is unrelated but I have never received any answer.

Here the log:

**Comment by cpfeiffer** [comment] 2017-11-12 00:08
Your log contains a few IOExceptions that seem to occur during connection establishment:
```
16:18:04.105 [Thread-1825] WARN  n.f.g.s.d.p.PebbleIoThread - error while connecting: read failed, socket might closed or timeout, read ret: -1
java.io.IOException: read failed, socket might closed or timeout, read ret: -1
	at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:740) ~[na:0.0]
	at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:752) ~[na:0.0]
	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:374) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.connect(PebbleIoThread.java:162) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.run(PebbleIoThread.java:353) ~[na:0.0]
```
However this exception is just logged and would not lead to a crash. (Un)fortunately there is no reference to any crash, the log contains only the output of single application lifetime.

**Comment by tecufanujacu** [comment] 2017-11-12 12:47
I know but this is what the log has recorded during the crash.
I can get other logs or I can directly get a logcat, or I can get both on the same time.
Let me know if you have some other idea.

At the moment I can't use Gadgetbridge, should I clean its data for some reason?

**Comment by ashimokawa** [comment] 2017-11-14 22:59
@tecufanujacu 
This bug should be fixed in Gadgetbridge 0.22.4 which I just tagged.

**Comment by tecufanujacu** [comment] 2017-11-15 13:52
Great, I'll test as soon it will be on Fdroid and I'll report back my feedback.
About the issue #685 any hope to solve the problem? I'd really like to use my Pebble with Misfit but unfortunately from several versions it is unusable.

**Comment by IzzySoft** [comment] 2017-11-15 14:06
I'm especially curious for the reconnection (as described on the related issue, this one here is exactly what I'm having with 0.22.2 here – and like @tecufanujacu I'll check as soon as 0.22.4 is available. Though if it no longer crashes, I cannot see whether the reconnect is working :stuck_out_tongue_winking_eye: )

**Comment by ashimokawa** [comment] 2017-11-15 20:59
@IzzySoft 
Crashing and restarting automatically is no different from starting Gadgetbridge on your phone for the first time after rebooting it. And there is no such option as "connect when Gadgetbridge starts", so there is currently also no way to "reconnect on crash".

So to test the fictive possible to be implemented "connect when Gadgetbridge starts due to whatever reason" option you do not need crashes. 😛

**Comment by IzzySoft** [comment] 2017-11-15 22:09
@ashimokawa OK, makes sense – then I wait for the fiction to become reality :wink:

Honestly, such an option would really be useful (and should of course only fire with BT enabled). My guess is it looks "too easy" to those with only one device – and the reason that option is not there is to decide which of the 10 devices @danielegobbetti has configured with his installation it should connect to when started (just naming him because of some screenshot I remember – don't nail me on the number, I just saw the list didn't fit on the screen). But hey, what does GB do when BT is toggled? For me, it automatically connects. Maybe to the "last connected device"?

**Comment by ashimokawa** [comment] 2017-11-19 08:57
0.22.4 is out on f-droid, please test if this resolves your crash

**Closed** 2017-11-19 21:59 UTC
Labels: device pebble

**Comment by tecufanujacu** [comment] 2017-11-20 09:48
The problem seems resolved. No more crashes.

**Comment by fgerrits** [comment] 2017-12-25 21:35
Hi,

I have just with the latest update 0.22.4 and Pebble watch that it crashes .
Where can I send my log file to to get it resolved?

**Comment by ashimokawa** [comment] 2017-12-26 21:27
@fgerrits

The latest release availavle on fdroid is 0.23.0 and 0.22.5 has been out for a long time, what makes you think 0.22.4 is latest?

**Comment by fgerrits** [comment] 2017-12-27 01:01
Just updated to 0.23.0, the version 0.22
6 was not in my library on F-droid, why it wasn't i dont know. Testing this version now.
Thx for your support.
