### ISSUE TITLE
Android Oreo: After restart, Gadgetbridge will not connect with the watches

### ISSUE THREAD

**Issue by rbarat** [Freeyourgadget/Gadgetbridge#1024] opened 2018-03-14 20:59 UTC
Hi, I have big problem -> After restart, Gadgetbridge will not connect with the watches (Amazfit Bip).
The Gadgetbridge application itself will start, but it will not connect with my watches.
I need to click on the watch bar in the app for the connection.

I am using Oreo ROM -> Nitrogen ROM, phone: Xiaomi Redmi Note 3 SE (Kate)
Link to my ROM: https://forum.xda-developers.com/redmi-note-3/development/rom-nitrogen-os-11-01-2017-t3536211

**Comment by danielegobbetti** [comment] 2018-03-15 11:36
Please use the issue template.

This issue is a duplicate of #693 .

**Closed by danielegobbetti** 2018-03-15 11:36 UTC
Labels: duplicate
