### ISSUE TITLE
Fetch activity data

### ISSUE THREAD

**Issue by danielegobbetti** [Freeyourgadget/Gadgetbridge#68] opened 2015-06-10 17:00 UTC
The data fetching is the basis for both #45 and #44 , and it works reliably but could be made better. What's surely missing is:
- do not acknowledge the data transfer to the band if even a single segment failed to be received. This way the data stays on the band and we can retrieve it again.
- Ideally wrap the storage of the data in a transaction and rollback it if the checksum of the data do not match (eg: if we are not getting the amount of data we were expecting from the band. 

This kind of misreads happen in my experience when the bluetooth stack has issues like:

```
  E/bt_h4   (10165): [h4] Unknown HCI message type drop this byte 0x0
  E/bt_h4   (10165): [h4] Unknown HCI message type drop this byte 0x0
  E/bt_h4   (10165): H4: Unable to acquire buffer for incoming HCI message.
```

We cannot fix this, but can prevent data loss.

**Comment by keverets** [comment] 2015-07-26 13:09
Is this issue still open? It seems that data fetching is in the 0.4.4 release.

That said, it's trying to pull a months worth of data (nice that it gives the start date!) but I can't tell if it's progressing at all as it just spins for about 15-20 minutes, then the spinning stops and it still says "No data. Synchronize device?". Should I open a separate issue for this, or is it appropriate as part of this issue?

I can add logging as well, or try a more recent development commit if that would help.

**Comment by danielegobbetti** [comment] 2015-07-26 13:44
Hi, fetching the data mostly works but there are still rough edges.

What we noticed is that the longer the timespan to sync, the more likely you will encounter issues, that's why I prefer to sync once in a while (and only when I have time to debug, but I digress...)

One month worth of data will take a couple of minutes, but it's supported by GadgetBridge. The way the sync works is that the band sends data in chunks of 20 bytes, and sometimes it will "split" the series in "segments". How long a segment is is completely up to the band fw, I have no idea how it is decided, I've seen segments that were two days long and others a couple of minutes. In any case, you're going to see a Toast (that little popup) for each segment. If you see only one toast it means we are not fetching the first segment correctly.

The length of each segment is also known to us, and is shown in the Toast as well (about to fetch xx hours, yy minutes of data...).

If you want to help debugging the issue you could enable saving the gadgetbridge log to file (it's in the settings) and send it to us (or upload to pastebin/pastie...). In order to avoid Bluetooth issues I'd recommend to try restarting your phone before fetching the data.

**Comment by keverets** [comment] 2015-07-26 19:38
I get the initial toast that it's about to fetch 26 days, 2h worth of data, but it just spins after that then eventually when I check it has stopped spinning and no data is available. I suspect something is going wrong with the sync that's holding it up.

I enabled "Write Log Files (needs restart)", quit the app, then tried another sync. I can't find in the file system where the log file might have been written. Where do the log files go?

**Comment by cpfeiffer** [comment] 2015-07-26 20:07
Log files go to /data/Android/nodomain.freeyourgadget.gadgetbridge/files/gadgetbridge.log (or something like that).

Interesting that you get 26 days of data. I once read that the Mi Band only supports up to 10 days of data.
What is your mobile device and what OS/version are you running? I actually have the same problem with a Moto G with a specific KitKat version.

**Comment by keverets** [comment] 2015-07-26 20:22
It's a Moto G running 4.4.4 (SlimKat).

In /Android/data there's no nodomain.freeyourgadget.gadgetbridge directory. In /data/data/nodomain.freeyourgadget.gadgetbridge (which requires root to get to) there's no files/ directory or logs visible.

Am I affected by the Moto G issue you saw?

**Comment by cpfeiffer** [comment] 2015-07-26 20:31
Did you restart Gadgetbridge after turning on logging? It should create directory if necessary. We don't exactly specify the directory, we just use an Android API to create the "external memory directory for this application", so it may vary by device/OS/version. It should be readable by everyone, though, that's the point of this directory. Maybe there is another one on your device?

Whether you have the same issue I can't say, yet, but it might be. For sure there is some incompatibility with this device's BT stack. I hope to get it fixed by installing Lollipop, but I can't promise anything.

I haven't researched for other Moto G owners with BTLE devices yet.

**Comment by keverets** [comment] 2015-07-26 20:38
I used the Gadgetbridge "menu -> Quit" after turning on logging. I just tried it again, and then force-killed the app, and after that the directory is created in /Android/data.

It seems to have now gotten some activity data off the device, and it's down to collecting 19d 7h worth of data. Hopefully the log will be revealing as to why it keeps failing and needing to be restarted.

**Comment by cpfeiffer** [comment] 2015-07-26 20:59
I'm sorry about this. I've added a compatibility-page at https://github.com/Freeyourgadget/Gadgetbridge/wiki/Compatibility-Issues for a start.

I can hardly use the Mi Band anymore with the Moto G now that the Mi Band fw version is 1.0.9.14. Which version do you have?

**Comment by cpfeiffer** [comment] 2015-07-26 21:27
BTW, I had captured a btsnoop dump when I last tried it and it looked like the Mi Band did send some data but it never reached Gadgetbridge (as if it got lost somewhere in the stack).

**Comment by keverets** [comment] 2015-07-26 22:18
I have fw version 1.0.10.3 according to Gadgetbridge

**Comment by danielegobbetti** [comment] 2015-07-29 10:08
@keverets I never tried a firmware in the 1.0.10.X series, it may be that there are some incompatibilities. Do you have the firmware file available?

Further, how does the log look like? Is the problem still present?

**Comment by keverets** [comment] 2015-07-30 11:13
I don't have the firmware file. Is there a way of retrieving the firmware from the device?

Some data has transferred, but the problem is still present. Looking at the logs, it does transfer some data then eventually appears to just stop until I (several minutes later) restart the process. What's the best way of getting the log to you?

**Comment by danielegobbetti** [comment] 2015-07-30 15:21
I am not aware of a way for getting the firmware from the device, unfortunately.

To share the log you could upload it to pastebin / pastie or on http://paste.scratchbook.ch/ which is an open source alternative to these services :-) and post the link here.

Please take a look at the logfile and be sure that it doesn't contain any information that you do not want to disclose before uploading. If you are unsure what kind of information might be contained in the log than ask here again before posting and I'll give you more info.

**Comment by simonvanderveldt** [comment] 2015-09-16 19:16
I'm having issues with syncing data from my Mi Band as well, my Mi Band is on firmware 1.0.10.11 and I'm using a Galaxy S4 with a 4.4.4. GPE edition rom.

First of all I have to manually "click" on MI in the Gadgetbridge UI (it shows "not connected" below "MI").
Once I do this the "not connected" changes into "initializing" or "connected". For the majority of the time this seems to result in the Mi Band perceiving this as a new pairing request because it performs the matching vibration and LED light pattern.
Is this supposed to happen?
Because of this re-pairing I seem to loose all my data.

In the cases where I have been able to sync some data it seemed like it missed all sleep activity.

So it's not really working as it should :P
Am I doing something wrong?

And @danielegobbetti Which firmware version are you using?

**Comment by danielegobbetti** [comment] 2015-09-16 20:09
Hi Simon,

Im on your sane fw version but my phone is running Android 5.1 (it's a Sony).

It is normal that gb expects you to click to connect (unless you choose to autoconnect when bt is turned on).

The band should say initialized and I confirm that it should not vibrate and blink. But please confirm the following:
1- you *did* confirm the pairing at least once (by tapping the band while it was blinking/vibrating)
2- you're not using gb and another app at the same time. If you do you have to make sure that *all* your details match in both apps, otherwise the band behaves exactly as you describe.

It is normal that when you re-pair the band deletes the data it has on records.

Please let us know the answers to the questions and we'll try to solve your issues.
--

**Comment by simonvanderveldt** [comment] 2015-09-17 09:41
@danielegobbetti Thanks for the info.

Regarding the questions:
- I did confirm the pairing, actually more than once because it kept happening ;)
- The Mi Fit app apparently had a service running in the back, I've uninstalled it now to see if that changes anything.

I'm also using Mi Band Tools, which has the Mi Band's address set in the app. Should I also, manually, set the Mi Band's address in Gadgetbridge?

**Comment by danielegobbetti** [comment] 2015-09-17 13:27
@simonvanderveldt no problem.

Premise: Since you are using also other apps I can only make assumptions, because I don't have any. Please share your findings on our wiki when you found out the root cause of your problems.

If Gadgetbridge wants to pair constantly, then there is definitely another app competing with us. I repeat my previous advice: check if your personal details are set exactly the same in each app, in this case I believe everything should work.

Regarding manually setting the band address this is not mandatory, unless you don't see the band in the main Activity of Gadgetbridge. Since you can connect to the band, you don't need to do this.

Regarding the other apps, keep in mind that the band will send the data to a single app, and then delete them from its internal memory, hence if you were syncing your activity data with the official app (or with Mi Band Tools? I don't know it) it's normal that you were seeing your data only in one app (i.e. the data available in Gadgetbridge were not available in the official app, and vice versa). We added an option in Gadgetbridge work around this issue, but it means that you should always sync with Gadgetbridge first (that will not confirm the transfer to the band, hence not clearing its memory) and only later with an external app. The option is disabled by default and is next to the Miband Address option you already discovered.

**Comment by simonvanderveldt** [comment] 2015-10-21 20:13
@danielegobbetti
> Premise: Since you are using also other apps I can only make assumptions, because I don't have any. Please share your findings on our wiki when you found out the root cause of your problems.
> 
> If Gadgetbridge wants to pair constantly, then there is definitely another app competing with us. I repeat my previous advice: check if your personal details are set exactly the same in each app, in this case I believe everything should work.

Thanks for the info! I've disabled/removed all other apps and that made the synchronisation a lot more stable. One thing I'd like to understand is why the settings of personal details would trigger the Miband to initiate the pairing sequence. Than I can contact the developers of the other tools and see if it can be fixed. 

What I am seeing right now when syncing is the following:
-  The initial connection to the Miband takes a different amount of time each time. This is between a couple of seconds and +-30s. Using the Mi Fit app this was always just a couple of seconds/almost instantly.
- After connecting the Miband status switches to `connected` and stays that way for a long time while other times it almost immediately switches the status to `initialized` and it shows the Miband details (% battery, etc). Sometimes it stays on `connected` indefinitely.
- The actual syncing of the data once I've reached the `initialized` status works the majority of the time
- I have a data backlog of a bit more than 1.5 days on the Miband at the moment and it won't fully sync that data. It seems like it stops at the same spot, but it's a bit hard to determine that from only the "download" bar. Is there any way I can debug this so we might be able to solve it?

**Comment by cpfeiffer** [comment] 2015-10-22 22:48
@simonvanderveldt That's how the Mi Band works. It basically creates a unique ID from your personal information, a bit like the Windows activation being based on a computer's hardware. As soon as the hardware (or your personal information) changes, the ID changes as well. Then the Mi Band wants to pair with the new ID.

Could you please open a new issue for the connection problems? This is completely unrelated to activity data fetching. I'm seeing this as well, but I don't know the cause, yet. I don't use any other software with the Mi Band, so it's no interference with them.

I'm going to debug this, but it's not an easy one, it's not even easily reproduceable.

As a workaround, you can long-press and invoke "Disconnect" when it takes longer than a few seconds and then try again.

**Closed** 2018-05-22 12:18 UTC
Labels: device mi, enhancement
