### ISSUE TITLE
Synchronization data to proprietary 3rd party service

### ISSUE THREAD

**Issue by bigretromike** [Freeyourgadget/Gadgetbridge#248] opened 2016-03-10 06:44 UTC
Is there a plan for sync database from gadgetbridge to service like google_fit etc?
I was thinking about this app as a bridge between smart band --- smart phone --- smart services
Previously I used Mi Fit which wasn't that great + the sync was a bit broken and sending my data to china just to send them to google wasn't optimal. 

Im not saying that you guys should support google_fit_botnet but would be nice to have ability do sync to any (maybe opensource self hosted ones) service to parse data.

Is it in plan ? is there a roadmap ?

**Comment by danielegobbetti** [comment] 2016-03-10 06:49
duplicate of #49

**Comment by bigretromike** [comment] 2016-03-10 06:52
Your post is about self-hosted. 
Mine was more about 3rd party like Google/Apple. but ok, lets hit the 'orginal' one with 3rd party

**Comment by danielegobbetti** [comment] 2016-03-10 18:59
reopening as requested by @cpfeifer

**Comment by bigretromike** [comment] 2016-03-11 08:32
I think for Google Fit this is right place to start: https://developers.google.com/fit/overview#responsible_use_of_google_fit

**Comment by IzzySoft** [comment] 2016-05-19 13:48
Usually it's @danielegobbetti pointing this out: GB has a high trust not least due its lack of the Internet permission. Syncing with 3rd party services would require Internet – and with services like GoogleFit and the likes said trust would definitely be undermined.

I'm not "against" having such features, but would strongly suggest not having them baked into GB directly for the named reasons. So again my "buzzword": this would be a fine candidate for an addon that could plug into GB – giving each user the chance to actively decide whether that is wanted or not (opt-in, privacy-first).

**Comment by cpfeiffer** [comment] 2016-05-19 15:12
We will not add this directly to Gadgetbridge, that's for sure. We could support this scenario through other means, though, e.g. through export and an additional sync tool.

**Comment by bigretromike** [comment] 2016-05-20 05:36
that's a good idea

**Closed** 2018-02-07 19:53 UTC
Labels: help wanted

**Comment by JokerGermany** [comment] 2019-04-30 22:24
> [...] sending my data to china just to send them to google wasn't optimal.
/signed
It should be my free will allowing to send my data to evil companys> 

> We will not add this directly to Gadgetbridge, that's for sure. We could support this scenario through other means, though, e.g. through export and an additional sync tool.
This sounds weird.
How about addons like in conversations?
