### ISSUE TITLE
Subsonic Track Info Doesn't Appear in Pebble Music App

### ISSUE THREAD

**Issue by jaylittle** [Freeyourgadget/Gadgetbridge#474] opened 2016-12-25 15:56 UTC
When using the subsonic android application to play music, I've discovered that none of the information relating to the the file being played is displayed in the Music app on my PTS.   I can however move between tracks and control the behavior of the application using the controls in the Pebble music application.

Gadgetbridge version: Latest
Android version: CyanogenMod 13.1 sans Google Play Services
Device: Pebble Time Steel with latest firmware

**Comment by ashimokawa** [comment] 2016-12-26 23:06
@jaylittle 
MIght work in the next release, I wasn't able to test since Subsonic didn't want to play anything from my local library.

**Comment by jaylittle** [comment] 2016-12-27 00:35
If you install the Android app, it comes with a demo subsonic server already setup that I believe actually works.  You can connect to that demo server and play music hosted on it using the apps default config.

**Comment by ashimokawa** [comment] 2016-12-27 12:59
@jaylittle 
Ok confirmed working in master. Will be released with the next version (0.16.0) really soon.

**Closed** 2016-12-27 12:59 UTC
Labels: pebble

**Comment by jaylittle** [comment] 2016-12-27 14:35
I appreciate it, thank you so much!
