### ISSUE TITLE
Automatic refresh

### ISSUE THREAD

**Issue by robin13** [Freeyourgadget/Gadgetbridge#698] opened 2017-05-19 11:40 UTC
#### Your issue is:
Automatic / regular download of data from device

#### Your wearable device is:

Mi Band 1S

#### Your android version is:

CM 13

#### Your Gadgetbridge version is:

0.19.2

It would be great if you could set Gadgetbridge to regularly (hourly, daily, every connection, ...) download data from the device.  This could then be coupled with a sync script to regularly move the data off the Android to be able to do other work on it (automated reporting etc.).

**Comment by cpfeiffer** [comment] 2017-05-20 19:40
Duplicate of #336.

**Closed by cpfeiffer** 2017-05-20 19:40 UTC
