### ISSUE TITLE
Gadgetbridge crashing when pushing notifications to pebble

### ISSUE THREAD

**Issue by Daniel0Wellby** [Freeyourgadget/Gadgetbridge#1327] opened 2018-11-09 22:20 UTC
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
When notifications are attempted to be sent to the smartwatch, gadgetbridge crashes I have attempted to clear the cache and dalvic alongside wiping the program.
It seems to be a issue with how the notifications are being handled.

From testing, smaller notifications like bluetooth file transmission and es file explorer work as expected while the test notification sent via the notification bar crashes the program but if I send it directly it works as expected

#### Your wearable device is:

Wearable device is a Pebble time running v4.3 ofw 
hw revision snowy23

#### Your android version is: 15.1-20181107-NIGHTLY-oneplus3 (android version 
8.1.0)
#### Your Gadgetbridge version is: 0.31.0

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by Daniel0Wellby** [comment] 2018-11-09 22:31
Sorry about the lack of a log It didn't want to attach then https://pastebin.com/vcEDCCQe
I have blanked out gps coords from the log file

**Comment by ashimokawa** [comment] 2018-11-10 10:13
Duplicate of #1323
Is fixed in 0.31.1 which as been tagged and will be in f-droid soon.
As a workaround add a predefined reply in pebble setting.

**Closed by ashimokawa** 2018-11-10 10:13 UTC
