### ISSUE TITLE
Weather does not work in PEBBLE weather watchfaces - Gadgetbridge y Android.

### ISSUE THREAD

**Issue by Gabicu** [Freeyourgadget/Gadgetbridge#899] opened 2017-12-01 15:18 UTC
Sorry for my English.

Android: 7.0
Gadgetbridge: 0.22.4
Pebble Firmware: v3.12.3
Phone: Huawei P8 Lite 2017

I havve some weather watchfaces, but these do not update the time in the pebble.
I have installed android weather notification on the phone.
I think, in principle, I have everything as it should be, but nothing. What I can do?
Any solution?
Thank's for all.
![screenshot_20171130-134106](https://user-images.githubusercontent.com/33549649/33488969-c380b156-d6b2-11e7-9f8f-5e9e7eb9d4af.png)
![screenshot_20171130-134130](https://user-images.githubusercontent.com/33549649/33488970-c3bbda74-d6b2-11e7-8bc1-895500727a98.png)
![screenshot_20171130-134209](https://user-images.githubusercontent.com/33549649/33488971-c3dfe43c-d6b2-11e7-988c-38191c7e639e.png)
![screenshot_20171130-134247](https://user-images.githubusercontent.com/33549649/33488973-c405f8c0-d6b2-11e7-98e6-01f0d8610f45.png)
![screenshot_20171130-134258](https://user-images.githubusercontent.com/33549649/33488974-c4301f42-d6b2-11e7-88b3-891e1fc857b9.png)
![screenshot_20171130-134318](https://user-images.githubusercontent.com/33549649/33488975-c45d800e-d6b2-11e7-924c-0be48bac234b.png)
![screenshot_20171130-134351](https://user-images.githubusercontent.com/33549649/33488976-c49c1d46-d6b2-11e7-81c1-5101248220f0.png)
![screenshot_20171130-134455](https://user-images.githubusercontent.com/33549649/33488977-c4bf0ac2-d6b2-11e7-8e96-f9236137bb5d.png)
![screenshot_20171130-134623](https://user-images.githubusercontent.com/33549649/33488979-c4f81e70-d6b2-11e7-8241-64059e447dcd.png)

**Comment by IzzySoft** [comment] 2017-12-01 15:27
Not all watchfaces might be supported. Could you try with one we *know* to be working, such as TrekVolle or Healthify – so we can at least tell on which end the problem lies?

**Comment by Gabicu** [comment] 2017-12-08 15:54
Well, Trekvolle and Timestyle works, the others, no. But i want ona face with the wind in the weather, exist one? Thank's

**Comment by IzzySoft** [comment] 2017-12-08 16:43
@Gabicu Take a look [here](https://github.com/Freeyourgadget/Gadgetbridge/issues/482) for a list of watch faces we *know* are supported by GB with weather data.

@danielegobbetti could you check your initial post there again, please? Though the issue is closed, some check-boxes are not marked and have no comment on why (simply not completed? or not possible? or not possible *then* but could to now with backgroundJS?) Also, ping me then if I should transfer some information to the Wiki (I'm thinking of an additional "chapter" [here](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Watchfaces)).

**Comment by Gabicu** [comment] 2017-12-08 21:06
I think taht Multifunctional 7-Segment is a complet and good weatherface to pebble. If you get it to work with GB, great. 😉

**Comment by IzzySoft** [comment] 2017-12-08 22:37
@Gabicu that's why I brought it to that list back then. I personally use TrekVolle. Haven't tried Multi-7; you could try and report back – might encourage @danielegobbetti to update that list :wink:

**Comment by Gabicu** [comment] 2018-01-12 12:23
TrekVolle don't work to me

**Comment by IzzySoft** [comment] 2018-01-12 13:25
Do you have BackgroundJS enabled in GB, @Gabicu ? In that case, only battery status works but no wheather. If you disable BackgroundJS, wheather will work but battery status not. Not sure what's the culprit.

**Comment by Gabicu** [comment] 2018-01-12 13:54
I have this

**Comment by Gabicu** [comment] 2018-01-12 13:55
I have de JS

**Comment by Gabicu** [comment] 2018-01-12 13:57
I have the chek  of JS on

**Comment by Gabicu** [comment] 2018-01-12 13:57
I have the chek  of JS on

**Comment by Gabicu** [comment] 2018-01-12 13:59
![screenshot_20180112-145333](https://user-images.githubusercontent.com/33549649/34878080-1d3f8c96-f7a9-11e7-8a5a-ba38a98e44d3.png)

![screenshot_20180112-133752](https://user-images.githubusercontent.com/33549649/34878086-25fe1a8c-f7a9-11e7-8b4b-fa76cdc35d2f.png)

**Comment by IzzySoft** [comment] 2018-01-12 14:00
Then try to untick, then disconnect and reconnect the Pebble.

**Comment by Gabicu** [comment] 2018-01-12 14:07
No work
![img_20180112_134121](https://user-images.githubusercontent.com/33549649/34878369-3bfc33b8-f7aa-11e7-9931-def6972e48f5.jpg)

**Comment by Gabicu** [comment] 2018-01-12 14:17
Ok. Work. Thank's for all

**Comment by IzzySoft** [comment] 2018-01-12 14:25
Yeah, when TrekVolle shows "updating" one needs a little patience, @Gabicu :wink:

**Comment by Gabicu** [comment] 2018-01-12 14:29
Thank's
I think that TimeStyle work.
AllThatInfo don't work

**Comment by IzzySoft** [comment] 2019-08-20 11:43
Closing this then as the problem was confirmed solved.

**Closed by IzzySoft** 2019-08-20 11:43 UTC
