### ISSUE TITLE
Workout/activity GPX misses the beginning of the activity on Amazfit Bip

### ISSUE THREAD

**Issue by szilardx** [Freeyourgadget/Gadgetbridge#1134] opened 2018-06-28 14:43 UTC
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*In case of a bug, do not forget to attach logs!*

#### Your wearable device is:
Amazfit Bip - tested with older and newest firmware - 0.1.1.45

#### Your android version is:
6.0.1 LOS
#### Your Gadgetbridge version is:
0.26.5, 0.27.0

The activities imported from the Amazfit Bip with Gadgetbridge (and the gpx exported) are shorter than reported on the device. First I thought this was the inaccuracy of the Bip's internal calculations, but comaparing with an other app's tcx export I found the problem.

Comparing the TCX from other app, and the GPX from Gadgetbridge in GPXSee shows that the GPX misses the first few trackpoints.
Comparing the two files in a text editor shows, that the TCX has the trackpoints that the GPX file misses, but the missing trackpoints has the same timecode value.
So this could be the value why Gadgetbridge misses those points.

This could be an issue caused by a bad report from the device, but it is also frustrating, that the GPX has a shorter activity than the length reported on the device. 

I can provide the tcx and gpx files in email.

Thanks for developing this app anyway, really appreciate it 👍

**Comment by szilardx** [comment] 2018-07-16 20:00
I have investigated this issue.

When an activity is sent from the Bip, the beginning of the activity data has issues.
I am no android developer, but I did a little testing in Android Studio.

Gadgetbridge throws away the first 30-31 GPS coordinates, because they have the same timestamp. I made an override to keep those activity points.
All of the ActivityPoints in an ActivityTrack have a little offset from the baseDate, which is the starting time for the activity, that the Bip shows on the device.
The first few ActivityPoint seems to be HR data only. The number of these point are between 4-37 something.
Then comes the 30-31 ActivityPoint with the same timestamp (after my modification).
After this 30-31 "bad" ActivityPoint comes the good ActivityPoints with GPS and HR data.

The timestamps are clearly off in the beginning, so I made the following hack:
I have copied this method with an extra signiture.
`    private ActivityPoint getActivityPointFor(long timeOffsetSeconds, GPSCoordinate gpsCoordinate) {
        Date time = makeAbsolute(timeOffsetSeconds);
        if (lastActivityPoint != null) {
            if (lastActivityPoint.getTime().equals(time)) {
                if (lastActivityPoint.getLocation() != null &&  !lastActivityPoint.getLocation().equals(gpsCoordinate)) {
                    return new ActivityPoint(time);
                }
                return lastActivityPoint;
            }
        }
        return new ActivityPoint(time);
    }`
And this is called in `consumeGPSAndUpdateBaseLocation`.

The first 30-31 GPS points need a good timestamp, so I thought about the following:
Take the time between the basedate and the last "bad" ActivityPoint with GPS info.
Distribute this time between the bad GPS ActivityPoints. 

I added this to the end of the parse function in ActivityDetailsParser.java

`try{
            int pointer = 0;
            List<ActivityPoint> activityPointList = activityTrack.getTrackPoints();
            Date gpsStartTime = null;
            List<Integer> gpsEntryIndexes = new ArrayList<>();
            while (pointer < activityPointList.size()){
                if (activityPointList.get(pointer).getLocation() == null){
                    pointer++;
                    continue;
                }
                gpsEntryIndexes.add(pointer);
                if (!(activityPointList.get(pointer).getTime().equals(activityPointList.get(pointer+1).getTime()))){
                    gpsStartTime = activityPointList.get(pointer).getTime();
                    break;
                }
                pointer++;
            }
            long differenceInSec = TimeUnit.SECONDS.convert(Math.abs(gpsStartTime.getTime() - baseDate.getTime()), TimeUnit.MILLISECONDS);

            double multiplier = (double) differenceInSec / (double) (gpsEntryIndexes.size());

            for (int j = 0; j < gpsEntryIndexes.size(); j++){
                long timeOffsetSeconds = Math.round(j * multiplier);
                activityPointList.get(gpsEntryIndexes.get(j)).setTime(makeAbsolute(timeOffsetSeconds));
            }

        }
        catch (Exception ex){
            throw new GBException("Error cleaning activity details: " + ex.getMessage(), ex);
        }

        return activityTrack;`

I have been testing this for a week now, and it seems to make gpx files that is very similar to the info display on the watch. The activity length is 2-3 seconds shorter than on the watch (I could not figure that out, as the period between the start and end time in the summary field is longer than on the watch).

**Comment by pro-copcfc** [comment] 2018-07-26 16:31
Confirm, also have this problem. f.e. application reduce distance from 8km to 7.7 and time from 28m to 26.55 sec...
I don't know your algorytm, but in modified MiFit from Lolex 3.4.1 export function works almost perfectly, i can add a link for it. (it necessary to login for downloading)  https://4pda.ru/forum/index.php?showtopic=596501&st=29800#entry74314759

**Comment by danielegobbetti** [comment] 2018-07-27 10:21
@pro-copcfc do I understand you right that the original workout was 28 **minutes** and the gpx exported by gadgetbridge was 26.55 **seconds**, so almost 26 **minutes** *shorter* than the original? If so, this is not about missing just a few samples at the beginning.

**Comment by pro-copcfc** [comment] 2018-07-27 10:43
No, not 26 minutes shorter. 1min11sec and 250 metres shorter. Real distance
was 8 km and time 28.06.
 I'll try to test it again soon and will write results with screenshots and
.gpx files.
пт, 27 июл. 2018 г. в 12:21, Daniele Gobbetti <notifications@github.com>:

**Comment by cpfeiffer** [comment] 2018-07-27 20:30
I think @szilardx pretty much nailed it. Throwing away the samples is obviously not the best way to deal with this, and while I'm not really fond of *inventing* timestamps for trackpoints, I think it is the only thing we can do here. This should be fixed in the Bip firmware of course, but what can we do.

We could add a metadata comment to the gpx track that the first xxx minutes may have slightly incorrect timestamps.

@szilardx would you like to open a PR for this?

**Comment by szilardx** [comment] 2018-07-29 10:42
@cpfeiffer I pushed the changes to my github, so it would be easier to check on them:
https://github.com/szilardx/Gadgetbridge/commit/b480f3ec9ad4f2fbf54ffd3f4c3e3cff654f83a6

Should I do the PR with this? (java is not my language, but my commit works for me, although there could be issues with the style).

Besides the metadata, an another solution could be to add a menu option to enable/disable this fix for the Bip in the Miband/Bip options. (There could be a disclaimer also, that the first few timestamps are guesstimates) This way, the user can decide about the usage, and also turn this off, if this is fixed in the firmware. (but I think I would make more mess if I'd try to code this)

**Comment by cpfeiffer** [comment] 2018-08-01 17:37
Thanks! I cherry-picked your commit, so you don't have to create a PR. I also changed some things and would like to have your feedback on them. For simplicity, I'll add them as comments to my change commit.

**Comment by cpfeiffer** [comment] 2018-08-01 17:46
Note: I didn't actually test my changes since I'm having some issues with my bip, so I'd appreciate if you could have a look at the change and tests if it works.

**Comment by szilardx** [comment] 2018-08-01 22:47
Thank you for the fix. Now I can use the main branch again :)

As I said in the reply to your comment at the commit:
I tested your changes, they work with my Bip. Your functional changes make sense to me, they should only produce minimally different results from mine when the time difference is much bigger.
Because these are _invented_ timestamps, this does not really matter.

We are still a few (3-10 secs) seconds short with the activity time compared to what display on the bip, but I was not able to figure out a pattern for that. The mod of the other app mentioned before seems to rearrange the timestamps for the whole activity (I base this presumption on forum post I read), and account for the pauses too. But I have no idea how to do that.

With this fix, the starting point on the gpx is pretty close to the physical starting point, and with the timestamp fixes the speed is sensible too.

**Comment by szilardx** [comment] 2018-08-04 19:06
@cpfeiffer Could you have a look at line 143 and my reaction to your comment here:
https://github.com/Freeyourgadget/Gadgetbridge/commit/7f1c0521eadb282a3c7ad45ffa1dfc361d452dd1#comments

Thanks in advance!

**Comment by cpfeiffer** [comment] 2018-08-04 21:12
Thanks a lot, fixed!

**Closed** 2018-08-04 21:13 UTC
Labels: device amazfit bip

**Comment by doodhout** [comment] 2019-04-03 12:24
Currently on Amazfit Bip 1.1.5.16 and GadgetBridge 0.32.3 and I'm seeing a discrepancy in distance and duration of a walk activity between the Bip and whatever OSMAnd+ displays when opening the synchronised activity from within GadgetBridge.

What might this mean? I haven't had the chance to investigate like OP did, but does that mean the issue isn't fixed yet?

Should I try something other than OSMAnd+ to try and display the GPX data?

**Comment by szilardx** [comment] 2019-04-03 12:56
For me, a Run activity displays the same lenght - 3,59 km for example. I will try the walking activity.

**Comment by doodhout** [comment] 2019-04-03 21:32
By the way, I can confirm from another walking activity that the issue clearly still exist - for walking activities.

I've also done some biking today and for that kind of activity the distance is always correct, concluded from two biking activities.

**Comment by szilardx** [comment] 2019-04-04 07:37
Can you test if the MifitTcxExport mod by jps1x2 (it now has an xda thread - cannot post links) exports walking activity ok? He seems to have more advanced algorythm, if that is better, we can try to ask for help! :)

**Comment by doodhout** [comment] 2019-04-04 13:19
I'll try doing that in the coming days, thanks for the tip.
