### ISSUE TITLE
Crashes on 0.19.1 when calendar permissions are not granted

### ISSUE THREAD

**Issue by RiFellow** [Freeyourgadget/Gadgetbridge#678] opened 2017-05-06 15:31 UTC
Hello,
i've just made an update from 0.18.5 to 0.19.1 on my Moto G4+ with LineageOS 14.1 (Android 7.1.2). Before that i have had no problems to connect to my 2 gadgets, a Pebble Time Steel and a MiBand 2. Now i cant connect to my MiBand 2 and when i try to connect to my PTS GadgetBridge crashes.
I've tried to reinstall an older version of GadgetBridge through F-Droid but there is an error when i try this. I dont want to uninstall GadgetBridge to try it again because of the data.
I attach a log-file.
Any hints?
With regards
Thomas
[gadgetbridgelog.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/981003/gadgetbridgelog.txt)

**Comment by ashimokawa** [comment] 2017-05-06 16:04
@RiFellow 
Thanks for reporting.
Regarding pebble:
You have two ways to fix it. Chose one.

1) Grant Calendar Access
2) Switch "sync calendar" off in pebble settings

Of course we should fix the crash if the user denies calendar access. :/

Regarding Mi, I have no idea. Error 133 is pretty generic.

**Comment by RiFellow** [comment] 2017-05-06 16:34
@ashimokawa 
thx, i've granted calendar access and no longer crashes.
4 Mi, i'll have to wait. It has FW 1.0.0.34 and HW 0.1.3.2

**Comment by RiFellow** [comment] 2017-05-06 18:08
Epilog: 8-)
after searching about connect-problems with MI Band 2 in the 3W i've tried to bind the MB2 to another smartphone and then tried to connect it in gadgetbridge on the Moto G4+. Now i have to say: All is ok, it wasn't a problem of the new gadgetbridge version.
Thx for reading and answering.

**Comment by danielegobbetti** [comment] 2017-05-08 10:23
Marking this as device: pebble as the crash happens only for that device, even though the problem is general.

**Comment by ashimokawa** [comment] 2017-05-08 20:27
Forgot to fix in time for 0.19.2, will be in 0.19.3

**Closed** 2017-05-09 10:33 UTC
Labels: bug, device pebble
