### ISSUE TITLE
Adding and deleting alarms on bip

### ISSUE THREAD

**Issue by WhiteGrizly** [Freeyourgadget/Gadgetbridge#1167] opened 2018-07-19 22:24 UTC
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your wearable device is:
Amazfit Bip HW: V0.11.2.4 FW: 1.0.1.00

#### Your android version is:
MIUI 9.2.4.0 (7.1.2 N2G47H)

#### Your Gadgetbridge version is:
0.28
-------------------------------------------
I would like to be able to **add** and **remove** alarms on amazfit bip to eliminate the need of run mi fit. Alarm clocks in bip more than 3.

**Comment by danielegobbetti** [comment] 2018-07-21 12:31
Duplicate of #577

**Closed by danielegobbetti** 2018-07-21 12:31 UTC
Labels: device amazfit bip
