### ISSUE TITLE
Pebble Round

### ISSUE THREAD

**Issue by gwidionr** [Freeyourgadget/Gadgetbridge#919] opened 2017-12-24 20:41 UTC
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*In case of a bug, do not forget to attach logs!*

#### Your wearable device is: pebble round aka spalding, actual Firmware (4.3)

*Please specify model and firmware version if possible*

#### Your Gadgetbridge version is: 0.22.5

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*
Since five vor six days I've got no sync oft sleep data. Pebble recognice sleep correctly but I don't geht the data transfered.

**Comment by ashimokawa** [comment] 2017-12-25 09:30
@gwidionr 
It is normal that the movement data is transferred first,  then sleep data. These come in when the pebble decides to send it (after post processing on the watch).

But of course the sleep data should have come if a while after being awake, so if you still have missing sleep data for the previous days there is something wrong, if you look at the data just after waking up, it is normal that there are no sleep data yet.

**Comment by danielegobbetti** [comment] 2018-02-10 22:59
Closing for the lack of feedback. Feel free to reopen if the issue is still present!

**Closed by danielegobbetti** 2018-02-10 22:59 UTC
Labels: device pebble, no feedback
