### ISSUE TITLE
Messages are displayed in Chinese

### ISSUE THREAD

**Issue by jmlopezo** [Freeyourgadget/Gadgetbridge#630] opened 2017-03-30 14:38 UTC
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
I configured the device with the application, but all messages are displayed in Chinese.

#### Your wearable device is:

Makibes Aerobic A1

Motorola X 2nd generation Android 6.0

#### Your Gadgetbridge version is:
0.18.3

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by jpbarraca** [comment] 2017-03-30 22:23
Can you provide a log file including the display of a message?
What is the language setting of your phone?

**Comment by jmlopezo** [comment] 2017-03-31 11:53
Can you tell me where I'm looking for the log file?

The mobile is setting in Spanish.

![photo_2017-03-31_08-38-11](https://cloud.githubusercontent.com/assets/26796072/24549211/ac29f592-15ee-11e7-87b1-30c02e306bc9.jpg)

Thanks.

**Comment by jpbarraca** [comment] 2017-03-31 11:56
In the configurations menu, the last item. Enable it, reconnect the device to gadgetbridge and trigger some messages.

Use messages with and without accented characters.

**Comment by jmlopezo** [comment] 2017-03-31 12:23
Enable debug mode ... but where is the log record?

I just connect with gadgetbridge

![image](https://cloud.githubusercontent.com/assets/26796072/24550205/704b44ae-15f3-11e7-98ea-a2c2f3459cf4.png)

**Comment by kowalski215** [comment] 2017-03-31 13:45
Same happens with Zeblaze Plus - Both caller ID and SMS are displayed only in Chinese.

**Comment by jpbarraca** [comment] 2017-03-31 13:49
Please see this: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files

**Comment by jmlopezo** [comment] 2017-03-31 21:22
I attached the log, sorry for the delay, can not before.
[gadgetbridge-2017-03-31.1.log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/886955/gadgetbridge-2017-03-31.1.log.zip)

[gadgetbridge.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/886950/gadgetbridge.zip)

**Comment by jpbarraca** [comment] 2017-04-01 14:07
Can you try this branch: https://github.com/jpbarraca/Gadgetbridge/tree/fix-630

If you wish, the corresponding APK is attached. If you are using GB from F-Droid or other market, when you install apk you will probably loose your data.

[gb-debug-630.apk.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/887686/gb-debug-630.apk.zip)

**Comment by jmlopezo** [comment] 2017-04-03 13:41
Now it does not come out in Chinese, but it is only possible to see the sender, there are many spaces between characters.

![image](https://cloud.githubusercontent.com/assets/26796072/24611934/209d9a56-185a-11e7-81e5-11da21e6c15f.png)

**Comment by jpbarraca** [comment] 2017-04-04 10:57
Can you provide an BT logfile of the original app?

**Comment by jmlopezo** [comment] 2017-04-04 12:28
Of course, where is the log file?

**Comment by jpbarraca** [comment] 2017-04-04 14:16
Go to the developer options in the Android Settings app, and enable the HCI log.
The file will be in the root of the sdcard.
If possible, try to present some known text as a notification. In the GB debug menu you can trigger notifications.

This may help you:
https://play.google.com/store/apps/details?id=com.android_rsap.logger
http://www.fte.com/webhelp/sodera/Content/Documentation/WhitePapers/BPA600/Encryption/GettingAndroidLinkKey/RetrievingHCIlog.htm

**Comment by jmlopezo** [comment] 2017-04-04 15:46
This is?

[btsnoop_hci.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/893698/btsnoop_hci.zip)

**Comment by cpfeiffer** [comment] 2017-04-04 22:45
Didn't have a look at the dump yet, but this looks a bit like utf-16 encoded characters. FWIW, UTF-16 is Java's internal String encoding.

**Comment by jpbarraca** [comment] 2017-04-04 22:53
My problem with these devices is that the result in a Zeband is totally different. Only the first char of the message is presented.

@jmlopezo The log was created with the original application?

**Comment by jpbarraca** [comment] 2017-04-18 09:28
There was a commit that potentially fixed this issue. Can you test the latest version from the GB master repository?

**Comment by jmlopezo** [comment] 2017-04-18 12:08
Thanks for your help, but I gifted the smartwatch to an iphone user ... there it works without problems.

Greetings.

**Comment by dawiddudek** [comment] 2017-04-20 17:54
[log_bt.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/944976/log_bt.zip)
in this log you have test notification from hplus watch app and gadgetbridge
check this attach

**Comment by jpbarraca** [comment] 2017-04-21 17:00
I will analyse the log and see if there is something new. Thanks.
I made a commit that should have fixed this but it was made after 0.8.5. Please wait a few days for the next version.

**Comment by dawiddudek** [comment] 2017-04-22 22:16
Thanks for reply and I wait for New version

21.04.2017 19:01 "João Paulo Barraca" <notifications@github.com> napisał(a):

I will analyse the log and see if there is something new. Thanks.
I made a commit that should have fixed this but it was made after 0.8.5.
Please wait a few days for the next version.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Freeyourgadget/Gadgetbridge/issues/630#issuecomment-296246913>,
or mute the thread

**Comment by 1140921** [comment] 2017-04-28 13:23
Zeband I still receive notification in Chinese with version 1.85

**Comment by 1140921** [comment] 2017-04-28 13:29
[btsnoop_hci_20170428141717.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/964425/btsnoop_hci_20170428141717.zip)

**Comment by jpbarraca** [comment] 2017-04-28 16:28
@1140921 Can you provide a log using the official app?

**Comment by 1140921** [comment] 2017-04-28 17:00
@jpbarraca you mean hplus watch?
can you tell me how to get log file plase?

**Comment by ashimokawa** [comment] 2017-04-28 17:42
@1140921 
That is because the fix is Gadgetbridge 0.19.1 and not in your imaginary 1.85 version.
Please read the Changelog before posting

**Comment by dawiddudek** [comment] 2017-04-28 17:47
Where I can find 0.19.1? In f-droid i have 0.18.5

28.04.2017 19:42 "Andreas Shimokawa" <notifications@github.com> napisał(a):

**Comment by danielegobbetti** [comment] 2017-04-28 20:01
@dawiddudek version 0.19.1 was tagged yesterday and will be released by fdroid hopefully soon. (we have no influence on fdroid release process)

**Comment by Logh0nox** [comment] 2017-04-28 20:12
@ashimokawa ok my bad I'm sorry when apk released I'll give it a try thanks

**Comment by ashimokawa** [comment] 2017-05-01 13:53
@Logh0nox 
@dawiddudek 
0.19.1 is now in f-droid, please test and report

**Comment by Logh0nox** [comment] 2017-05-01 14:45
@ashimokawa I downloaded from f-droid using the debug to send message I still receive characters in Chinese

**Comment by dawiddudek** [comment] 2017-05-01 16:25
I tested, i have that same problem. And i can't send debug notification to
oryginal aplication. When I go back to home download hci log and attach.

01.05.2017 15:53 "Andreas Shimokawa" <notifications@github.com> napisał(a):

**Comment by jpbarraca** [comment] 2017-05-02 10:48
@dawiddudek 
The string "Test powiadomienT wiadomienie z Gad" appears in Chinese characters?
When you get home, please provide the dump of the original HPLUS app.
Is the device a Zeband or Zeband Plus?

**Comment by dawiddudek** [comment] 2017-05-02 12:10
[hci_log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/970322/hci_log.zip)
I have a problem with debug in GB. When i connect with orginal app I can't send any notification. When i push "create new notification" in orginal app doesn't reackt. 
When i connect to GB and send new notification zeband show this info in chainise.

I have a ZeBand Plus. in zip file You have hci log and GB log. (first row in log has a orginal app, second is GB and send sms from other phone to my number)

**Comment by jpbarraca** [comment] 2017-05-04 12:35
Thanks. I see that the Zeband Plus is sending a few different messages.
I will need some time to fully analyse the logs.

**Comment by dawiddudek** [comment] 2017-05-04 12:40
Easy, i Will wait for solution a problem :-)

04.05.2017 14:35 "João Paulo Barraca" <notifications@github.com> napisał(a):

**Comment by cpfeiffer** [comment] 2017-05-14 23:03
AFAIU this should be fixed in 0.19.2 (available in f-droid) -- can check if this works for you now?

**Comment by FerryDaBoss** [comment] 2017-05-22 10:59
Hi.
Same issue with the Zeband Plus. Chinese characters are displayed on the watch. Running apk 0.19.2

**Comment by jpbarraca** [comment] 2017-05-22 18:52
all characters as displayed in Chinese? Can you provide a log?

**Comment by FerryDaBoss** [comment] 2017-05-22 19:14
[gadgetbridge-2017-05-22.1.log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1019957/gadgetbridge-2017-05-22.1.log.zip)

Please find attached the log file. It`s not that straight forward. If I send the text: "apple" from the debugger, I get only Chinese characters, but if I send: "Apple" (with upper case A) I get the first letter A on the watch, and after that only chinese.

**Comment by FerryDaBoss** [comment] 2017-05-22 19:29
Update:

I`ve sent from the debugger: "qwertyuiopasdfghjklzxcvbnm" and received:

![img_20170522_222234](https://cloud.githubusercontent.com/assets/23486805/26324980/bec91b1a-3f3d-11e7-819f-802891cc0f5c.jpg)

Then I`ve sent the same but all with upper case: "QWERTYUIOPASDFGHJKLZXCVBNM" and got:

![img_20170522_222407](https://cloud.githubusercontent.com/assets/23486805/26325023/e9279d1e-3f3d-11e7-950a-70ea555e58c2.jpg)

**Comment by jpbarraca** [comment] 2017-05-22 22:23
There was a bug when storing the type of encoding required for the Zeband HPlus (and others). Can you try this apk built from the current master?

[app-debug.apk.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1020378/app-debug.apk.zip)

**Comment by FerryDaBoss** [comment] 2017-05-22 22:33
Great! It's working with this version. All the characters are displayed correctly. Minor visual notice: too big spacing between the characters.

**Comment by jpbarraca** [comment] 2017-05-23 07:58
That is actually a bug... I will look at it later today. Can you provide the log file?

**Comment by FerryDaBoss** [comment] 2017-05-23 08:13
Here you go:


[gadgetbridge.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1021372/gadgetbridge.zip)

**Comment by jpbarraca** [comment] 2017-05-23 08:14
That is actually a bug... I will look at it later today. Can you provide the log file with gb and the original app?

**Comment by FerryDaBoss** [comment] 2017-05-24 07:38
I`ve sent you the log from the gb, but for the life of me, I can`t get to generate a log from the official app.

**Comment by ashimokawa** [comment] 2017-07-16 19:55
Gadgetbridge 0.19.3 is out - but due to a bug in the f-droid android app it can't be updated.
The apk is here:

https://f-droid.org/repo/nodomain.freeyourgadget.gadgetbridge_96.apk

**Comment by IzzySoft** [comment] 2017-07-18 10:05
@ashimokawa the "bug" being the index not updated for ~3 days again.

**Comment by ashimokawa** [comment] 2017-07-18 10:35
No the bug is that the index is broken for many apps now, not even old versions can be installed.
New f-droid users have no way of downloading Gadgetbridge through the f-droid app at all!

**Comment by IzzySoft** [comment] 2017-07-18 11:13
@ashimokawa have you tried with one of the "new-design-betas"? I've got an idea which bug might be behind that if it works with those (which is one of the reasons my repo doesn't run on the latest version of fdroidserver ← pointer/reminder for you-know-what-I-mean :wink:).

**Comment by ashimokawa** [comment] 2017-07-18 11:42
@IzzySoft 
Hmm. I just tried an old version of f-droid (the one that downloads from their site) and Gadgetbridge actually showed up, latest and previous versions.
Then I upgraded again and it broke again.

**Comment by IzzySoft** [comment] 2017-07-18 12:02
@ashimokawa Believe it or not, that makes sense. I had the other bug in mind (lastest fdroidserver allows for multiple copies of the same version of an app to co-exist under certain circumstances – which breaks the index for older versions of the client) – but thinking closer, can't be that, which you proved. The other one are some "instabilities" with the latest clients – which seems to be what hits here. Now guess why their homepage doesn't link to one of those "latest versions", but to an older (stable) client version instead.

Not sure what exactly is wrong with the latest client (I'm not involved with that), and I like the old look-and-feel better anyway. So advice would be to stick with the stables – and you will see the new GB and can update it :stuck_out_tongue_winking_eye:

**Comment by ildar** [comment] 2017-07-18 13:32
Did you search their issue tracker?
https://gitlab.com/fdroid/fdroiddata/issues/

**Comment by ildar** [comment] 2017-07-18 13:35
Emm
https://gitlab.com/fdroid/fdroidclient/issues

**Comment by IzzySoft** [comment] 2017-07-18 14:13
@ildar I found no related bug, but know from several sources that the latest versions (those with the new design) are still a bit flaky. I won't file a bug as I'm not affected; I rather stay with the "old-style version" as long as possible – unless some new version offers back that style. I'm not a fan of that "fancy tile stuff".

**Comment by ildar** [comment] 2017-07-19 06:02
@Izzy , could you please check with 1.0-alpha client and then I'll start
bugging f-droid guys?
I see the 0.19.3 in F-Droid newer client.

**Comment by TT1972** [comment] 2017-07-19 06:29
Using the new version (0.19.3) Chinese characters are still showing up when message contains umlauts (äöü). Message is in English up to the first umlaut than switches back to Chinese characters

**Comment by IzzySoft** [comment] 2017-07-19 06:49
@ildar No, I won't install the alpha (I strongly dislike the new layout, and much prefer the older). Today it turned up in the older client as well – so if you say it is available with the newer, that part of the issue is gone :wink:

**Comment by ashimokawa** [comment] 2017-07-19 16:16
@TT1972 
Ow, it seems it interprets the utf8 byte sequence as GB encoding. And I think umlauts are not supported by the font. You can enable transliteration as a work around for now. It will use ae oe and ue in your case.

@IzzySoft 
I have the latest alpha, and it seems to me that the problem might simply be that I run by own debug build of Gadgetbridge, maybe that triggers a bug and makes all versions disappear. Previous f-droid versions always showed "from unknown source".
I will check on someone else's phone later - with no Gadgetbridge installed at all.

**Comment by jpbarraca** [comment] 2017-07-19 16:19
Some characters are not supported by the font. We work around some known cases and transliteration will also help.

**Comment by ashimokawa** [comment] 2017-07-19 16:23
@jpbarraca 
If I understand @TT1972 correctly the first umlaut causes all following characters to be chinese

**Comment by jpbarraca** [comment] 2017-07-19 16:47
With the latest version, äöü are displayed correctly in a Zeband. Don't know about a Zeband Plus as I do not own the hardware.

However, there is a transliteration map that is always applied to circumvent characters that are not at standard positions (those are included). Maybe that map is causing problems for Unicode enabled devices as it was designed for GB2312 devices. 

Can you please try this version, which only applies the map to GB2312 devices?
[app-debug.apk.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1159839/app-debug.apk.zip)

**Comment by ashimokawa** [comment] 2017-07-19 17:06
@jpbarraca 
Offtopic, I think we need a wiki page of the various HPlus devices, if I wanted one for testing, I wouldn't know what to buy..

**Comment by jpbarraca** [comment] 2017-07-19 17:17
They are mostly the same, with a different shell and display and minor protocol variations. There are basically two families of devices: the ones supporting Unicode characters, and the ones only supporting GB2312.

I will add this information to the Wiki

**Comment by ashimokawa** [comment] 2017-07-19 20:02
@IzzySoft 
@ildar 
still offtopic but I confirm that even in latest fdroid 1.0-alpha Gadgetbridge including icon and all versions is properly displayed if there is no self-compiled Gadgetbridge installed. If it is, then there is no icon and no versions displayed

**Comment by IzzySoft** [comment] 2017-07-19 20:25
@ashimokawa Educated guess: signature check ("I cannot install this anyway, so no reason to show it and wake expectations"). You could see whether there's some related setting (like "ignore signature check", or "show X even if Y").

**Comment by TT1972** [comment] 2017-07-20 09:36
@jpbarraca 
With this version the umlauts are diplayed
![img_20170720_113143](https://user-images.githubusercontent.com/9975194/28410906-6ea548cc-6d3f-11e7-9928-b4a18c041645.jpg)

**Comment by IzzySoft** [comment] 2019-08-20 13:08
Closing as the problem was reported solved.

**Closed by IzzySoft** 2019-08-20 13:08 UTC
Labels: device hplus, potentially fixed / needs confirmation
