### ISSUE TITLE
mi band S1 - pair but will not sync

### ISSUE THREAD

**Issue by 5shekel** [Freeyourgadget/Gadgetbridge#226] opened 2016-02-11 12:37 UTC
just got the S1 band  
it will pair but not sync  
hope attached log and screenshots will help.

![after paring](https://cloud.githubusercontent.com/assets/222526/12976382/93389812-d0fe-11e5-886e-2dd1eb9c422d.png)

![options aviable](https://cloud.githubusercontent.com/assets/222526/12976381/93383548-d0fe-11e5-9233-9ba322469cb9.png)

![error1](https://cloud.githubusercontent.com/assets/222526/12976379/933099e6-d0fe-11e5-82f4-54e8ad9b421d.png)

![error2](https://cloud.githubusercontent.com/assets/222526/12976380/9331401c-d0fe-11e5-990a-6e850da695e4.png)

[gadgetbridge.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/126310/gadgetbridge.log.txt)

**Comment by Samarium151** [comment] 2016-02-11 13:29
I'm having identical issue .  Your shots match what I'm seeing exactly.  Some relevant discussion in #178 (that's where I posted my log file).

**Comment by bigretromike** [comment] 2016-02-23 07:09
I would love to see this being supported!
And ability to import data from official (closed source) app

**Comment by cpfeiffer** [comment] 2016-02-25 23:20
Closing this, as it is a duplicate of #205

(see progress there)

**Closed by cpfeiffer** 2016-02-25 23:20 UTC
Labels: duplicate
