### ISSUE TITLE
MiBand does not pair

### ISSUE THREAD

**Issue by elmanytas** [Freeyourgadget/Gadgetbridge#165] opened 2015-11-13 05:59 UTC
Hi
MiBand is detected by gadgetbridge but it does not pair. Lights in miband does not blink neither vibrate.
How can I depurate the problem?
I don't know how to obtain the firmware version installed

**Comment by Helius** [comment] 2015-11-13 06:28
What android version do you use?
Probably I have the similar problem on Nexus5/Android6.
You can see firmware version in MiFit, Settings->FirmwareVersion (latest item in menu)

**Comment by jmferrer** [comment] 2015-11-13 10:50
Paired! Just retrying and retrying.
Now the band disconnects from cell phone so I cannot use notifications but alarms and activity works.
FW: 5.15.10.14
But this is other problem and must be solved in other issue. Maybe in #156 
Helius, can you pair your band after retrying 10 times?
To pair the band search and add it. Then wait 1 minute. If lights does not blink and band does not vibrate maybe has been paired silently in bluetooth devices. Unpair it and repeat the process from gadgetbridge app.

**Comment by jmferrer** [comment] 2015-11-13 10:53
I use cyanogenmod 11 -> android 4.4.4 .
My cell phone is a Motorola Droid 4. I love keyboards. ;-)

**Comment by cpfeiffer** [comment] 2015-11-13 21:41
@ashimokawa just said noted the Droid has Bluetooth 2.1 (according to https://en.m.wikipedia.org/wiki/Droid_4). So unless that information is wrong or you somehow added Bluetooth 4.0 Smart/LE yourself, this cellphone should not work with a Mi Band at all.

The Mi Band only uses Bluetooth LE and Gadetbridge's Mi Band support as well.

Clarifications welcome :-)

**Comment by jmferrer** [comment] 2015-11-16 10:17
In fact Google Play Store does not let me install MiFit but in fact:
![img_19800106_013220](https://cloud.githubusercontent.com/assets/8694168/11179333/ed8e897a-8c52-11e5-82ab-1f8eb910fa44.jpg)
![img_19800106_012836](https://cloud.githubusercontent.com/assets/8694168/11179363/15ee09e0-8c53-11e5-904b-2c4a8d5f2932.jpg)
![img_19800106_013333](https://cloud.githubusercontent.com/assets/8694168/11179373/22cf5a60-8c53-11e5-8611-08607457d509.jpg)

The problem is that ALWAYS I need to retry the connection. Sometimes it "hangs" in connecting phase, others in initiating phase, ... but after retrying 10 times always works. Maybe it could connect the first time.
Maybe the band has a "crontab daemon" like that makes itself "visible" to devices that not support LE in short periods of time? I don't know ... but it works to me.

**Comment by cpfeiffer** [comment] 2015-11-16 22:20
Well, that is indeed interesting. The Mi Band only supports LE and so does the Mi Band support i nGadgetbridge. So, apparently your Droid does support Bluetooth LE, congratulation :-)

Can you try the latest version 0.6.6 from f-droid and see if it improves the connection situation?

**Comment by elmanytas** [comment] 2015-11-22 20:48
I have updated and tryed some days but I have the same connection issues. How can I debug the problem?
Thanks

**Comment by cpfeiffer** [comment] 2015-11-22 21:37
You could check with logcat-root for the system logcat, which would also include Gadgetbridge log entries as well as system-level log statements (i.e. bluetooth-related ones). If that does not indicate any problems, you could enable a bluetooth snoop (in the developer options of Android's preferences).

If you post any of these logs, please check first, if there's any sensitive information in there.

**Comment by elmanytas** [comment] 2015-11-25 10:20
I updated the cyanogenmod version to 11-20150901-SNAPSHOT-XNG3CAO3GO-maserati and now I only need to retry one or two times. Then the connection is stable.
When I go away from my droid and return close the droid, the app does no try to reconnect. Is this a normal behaviour?

**Comment by cpfeiffer** [comment] 2015-12-07 21:11
Sorry for responding late -- completely missed your comment.

Too bad you need to try a few times before you get a connection. If it annoys you , please file an enhancement issue and we could at least try to automate the repeated connection attempts.

The reconnection behavior is like this:
1) There is a lowlevel bluetooth reconnection feature, but we do not use it anymore because some people (including you) can hardly connect at all then.
2) We do not perform application level reconnection because continuously scanning for nearby devices when disconnected hurts battery life.
3) Whenever a connection from phone to Mi Band is needed (e.g. a notification arrives) we attempt to connect implicitly, iff your band was connected manually before getting disconnected.

It might be that 3) does not work for you because you need a few connection attempts.

**Comment by cpfeiffer** [comment] 2016-03-27 14:34
I guess we can't do anything about this issue, so I'm closing it. Fee free to reopen it if necessary.

**Closed by cpfeiffer** 2016-03-27 14:34 UTC
Labels: mi band
