### ISSUE TITLE
OnePlus One with COS13.1.2 reboots after a while of scanning for devices

### ISSUE THREAD

**Issue by FichteFoll** [Freeyourgadget/Gadgetbridge#412] opened 2016-10-17 14:24 UTC
My phone just stops responding to touch events after a short while of "scanning" in GB. The only thing that works is the power button, which turns off the display but won't turn it back on anymore. About 15s later the phone reboots.

I use a rooted stock firmware (Cyanogen OS, version 13.1.2-ZNH2KAS3P0).

I installed GB 0.13.3 using F-Droid.

**Comment by FichteFoll** [comment] 2016-10-17 15:30
After a couple reboots and retries, GB started asking for accessing my device's location during the scan. It didn't do that previously. The Mi Band 2 is not found, however it doesn't crash the phone anymore.

**Comment by cpfeiffer** [comment] 2016-10-17 19:08
We also experienced crashes on several devices. It even happened with the plain Android Bluetooth dialog, so unfortunately it's not something we can fix. We might try workarounds by adding delays or something like that. If someone's interested in doing that, I can give the necessary infos where to look in our code.

**Comment by cpfeiffer** [comment] 2016-10-17 19:26
You might try discovering your band with a different phone/tablet to see if that makes a difference. I have the same mobile and OS version and no problem discovering the Mi Band 2.

If you're anywhere near Berlin or Cologne, I could have a look at it.

**Comment by FichteFoll** [comment] 2016-10-21 11:34
I can't unpair my Band from the Mi Fit app for some reason, which I think is required in order to attempt a GB pairing, correct?

**Comment by cpfeiffer** [comment] 2016-10-28 21:56
I don't know, I never used Mi Fit myself.

**Comment by pseudotechy** [comment] 2016-11-21 00:26
@FichteFoll I had this same problem (OnePlus One and CM 13.1.2 not rooted) and it completely went away when I disabled Privacy Guard for Gadgetbridge.   I suggest trying that to see if it helps.

**Comment by 927589452** [comment] 2016-12-19 13:03
I fixed a similar problem by doing a standard wipe and reinstall

**Comment by cpfeiffer** [comment] 2016-12-25 21:59
Thanks for the feedback guys, I'll close this as "not a bug in Gadgetbridge" then.

**Closed** 2016-12-25 22:00 UTC
Labels: not a bug
