### ISSUE TITLE
GB force closes with background JS enabled

### ISSUE THREAD

**Issue by IzzySoft** [Freeyourgadget/Gadgetbridge#889] opened 2017-11-19 23:33 UTC
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
With background JS enabled, GadgetBridge force-closes whenever I try to connect my Pebble Time Steel. This is completely independent from what watchface is running (tried with TrekVolle, Healthify and even TicToc). Last FC via logcat:

```
--------- beginning of crash
E/AndroidRuntime(10614): FATAL EXCEPTION: Thread-3382
E/AndroidRuntime(10614): Process: nodomain.freeyourgadget.gadgetbridge, PID: 10614
E/AndroidRuntime(10614): Theme: themes:{}
E/AndroidRuntime(10614): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/AndroidRuntime(10614):     at android.app.ContextImpl.startActivity(ContextImpl.java:682)
E/AndroidRuntime(10614):     at android.app.ContextImpl.startActivity(ContextImpl.java:669)
E/AndroidRuntime(10614):     at android.content.ContextWrapper.startActivity(ContextWrapper.java:337)
E/AndroidRuntime(10614):     at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.connect(PebbleIoThread.java:170)
E/AndroidRuntime(10614):     at nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread.run(PebbleIoThread.java:197)
```

No logs in `/sdcard/Android/data/nodomain.freeyourgadget.gadgetbridge/files` (oops, guess I didn't enable logging). If those would help, just let me know and I crash it again.

As soon as I disable background JS, I can connect fine. 100% reproducable

#### Your wearable device is:
Pebble Time Steel with its last firmware.

#### Your android version is:
Android 6.0 (LineageOS)

#### Your Gadgetbridge version is:
0.22.4 (updated today)

**Comment by danielegobbetti** [comment] 2017-11-20 07:51
Duplicate of #863

**Closed by danielegobbetti** 2017-11-20 07:51 UTC

**Comment by IzzySoft** [comment] 2017-11-20 08:46
Indeed. No idea how I've missed that. Doesn't contain the term "background" I guess :wink: Sorry for the dupe.
