### ISSUE TITLE
Controlling multiple audio playback apps

### ISSUE THREAD

**Issue by p-friedrich** [Freeyourgadget/Gadgetbridge#639] opened 2017-04-03 12:05 UTC
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
I use 3 different apps for audio playback: Shuttle+(1) as general music app, PocketCast(2) for podcasts and sometimes Deezer(3) for music streaming. Here is the behaviour I expected from the media control: I start (1) and start playback, it shows song information on the watch and the controls work as expected. This works. If I open (2) and start playback, (1) stops but is still in the notification tray. If I use the media controls on the watch now, I can't really predict the outcome: Sometimes (1) starts playing again, sometimes (2) just stops. The displayed media info is also not consistent and changes to the other app sometimes. If playback is stopped and I press play on the watch, I can't be sure what starts playing. Interestingly, sometimes when playback is stopped it shows the info of (1) but pressing play starts (2). The best case scenario would be, if it remembered the last app playing and the media control always act on this app. So pressing stop always stops the playback and doesn't start another app.
I hope I was able to express my problem. If I can help to resolve this, please feel free to tell me.

#### Your wearable device is:

Pebble Time v4.3

#### Your android version is:

7.1.1

#### Your Gadgetbridge version is:

0.18.4

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by danielegobbetti** [comment] 2017-04-03 17:05
Can you please share which preferred music app is set in gadgetbridge? Does the behavior change if you switch the configured app?

**Comment by danielegobbetti** [comment] 2017-04-03 17:06
(Marking this as device:pebble for clarity even though theoretically any gadget would behave the same)

**Comment by p-friedrich** [comment] 2017-04-04 09:51
Currently the preferred music app is set to "Standard". I will try to test different settings soon.

**Comment by danielegobbetti** [comment] 2017-05-01 09:32
Closing for the lack of feedback, please feel free to reopen once you performed your tests.

Further, if you can build from source, you could give the notification-refactor branch a try as something was changed in the logic.

**Comment by bluuub** [comment] 2017-05-02 15:16
I experience the same issue:
Using Material Player (Audiobooks) and Vanilla Music (Music). 

Test 1:
Default: Material Player

Playing: Vanilla Music

On Pebble: Pause
Expected behaviour: pause Vanilla Music
Actual behaviour: plays Material Player


Test 2:
Default: Vanilla Music

Playing: Vanilla Music

On Pebble: Pause
Expected behaviour: pause Vanilla Music
Actual behaviour: pauses Vanilla Music (shows track info for Material Player though)

**Comment by p-friedrich** [comment] 2017-05-08 08:45
@danielegobbetti I'm running the notification-refactor branch now, but the behaviour is still not as expected. My assumption was, that the Media control through gadgetbridge is similar to the Bluetooth media control (play, pause, skip) with a Headset. But this seems to be not the case.

**Comment by chrisvfritz** [comment] 2017-05-30 21:44
A few notes that may be related: when the preferred audio player is set to Default in GB, controls on the Pebble 2 Music app have a 10-15 second delay for YouTube Music. In YouTube Music, the controls update on the watch almost immediately after the action has finally registered on the phone. In Pocket Casts, although actions from the watch controls register very quickly, the currently playing track, play time, and play status all seem to update erratically. When both apps are in use, the music controls also seem to show a preference for Pocket Casts. Setting the GB preferred audio player to a specific app seems to solve all issues for that app, except for info from Pocket Casts often not updating on the Pebble Music app.

**Comment by razzintown** [comment] 2017-06-01 02:08
I also experience this bug.

**Comment by gabethecabbage** [comment] 2017-09-07 15:57
From my own digging it seems GBMusicControlReceiver.java isn't actually sending KeyEvents to anything other then the preferred audio player. Here's a test case to demonstrate this:

Test 1:
Preferred Audioplayer: Default
Playing Audioplayer: AntennaPod

Disable the "Default" music player (Settings -> Apps -> Music -> Disable)

On pebble: Pause

Expected behavior:  Pause AntennaPod
Actual behaviour: Nothing at all (volume control works fine though)

Test 2:
Preferred Audioplayer: Default
Playing Audioplayer: AntennaPod

Re-enable the "Default" music player (Settings -> Apps -> Music -> Enable)

On pebble: Pause/Next/Previous

Expected behavior:  Pause on AntennaPod
Actual behaviour: Pauses playback on AntennaPod, and resumes previous playback on "Music"

This AntennaPod pause is presumably only caused by playback starting in another application.

"Music" in this case refers to the default music app on LineageOS. Identical behaviour can be obtained by installing the "Preferred Audioplayer" if it is not a system application.

**Comment by gabethecabbage** [comment] 2017-09-08 07:13
Done some builds, commenting out the conditional blocks in [GBMusicControlReceiver.java](https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/receivers/GBMusicControlReceiver.java) and I now understand the existing functionality. Apologies for any ill-fitting terminology, I'm completely new to Java and haven't done any development for a few years.

Having made our new intent objects (downIntent, upIntent) the Receiver checks the if the "Preffered Player" is anything other then the "default" media player. If so the intent is targeted at the selected media player using ```up/downIntent.setPackage(audioPlayer);```. Otherwise it is broadcasts the intent without setting the setPackage string.

KeyEvent intents without setPackage  seem to only hit the default media player. This is where I hit the limits of my android understanding. Can we collect the name of any package currently playing media of media currently playing?

Also @danielegobbetti , can we get the no feedback label removed?

**Comment by gabethecabbage** [comment] 2017-09-08 14:05
Me again, I've hacked together something which provides the same functionality of the original Pebble app, however hacked is the operative and I'm really new to collaborating on software. 

@danielegobbetti  I know it's not fit to merge but should I submit a pull request just to get it reviewed? Sorry if I'm pestering, but I'm new to all this!

**Comment by danielegobbetti** [comment] 2017-09-08 14:38
@gabethecabbage please do submit a PR, we will surely review it!
Please do the PR from a branch other than **master** on your clone, as you will need to push further commits to perform changes.

**Comment by danielegobbetti** [comment] 2017-09-10 13:18
Closed as @gabethecabbage contribution was just merged to master. Please note that this will *not* be in release 0.21 (as it was already tagged a few days ago) but in the one following it.

**Closed** 2017-09-10 13:17 UTC
Labels: device pebble

**Comment by p-friedrich** [comment] 2017-09-26 18:13
I want to thank you all very much! I just tried the current version and the media control works flawlessly.
