### ISSUE TITLE
Riot notifications not sent to device

### ISSUE THREAD

**Issue by tradej** [Freeyourgadget/Gadgetbridge#872] opened 2017-11-07 10:10 UTC
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Riot notifications are not sent to the device.

#### Your wearable device is:
Mi Band 2, FW 1.0.1.54, `Mili_pro.ft` and `Mili_pro.ft.en` installed

#### Your android version is:
Stock 6.0.1 Samsung J510FN, Baseband version J510FNXWU2AQG1

#### Your Gadgetbridge version is:
0.22.2

#### Log:

Pasting only what I think is relevant. Can post a larger chunk if ncecessary.

```
08:40:27.275 [Binder_1] INFO  n.f.g.e.NotificationListener - Processing notification -1788060954 from source im.vector.alpha with flags: 513
08:40:27.275 [Binder_1] INFO  n.f.g.e.NotificationListener - Not forwarding notification, FLAG_GROUP_SUMMARY is set and no wearable action present. Notification flags: 513
```

**Comment by muppeth** [comment] 2017-12-25 14:54
I can confirm the same issue on pebble classic.

**Comment by danielegobbetti** [comment] 2018-02-17 17:02
I see this was reported upstream: https://github.com/vector-im/riot-android/issues/1141
The issue is that the source app is not adding wearable actions to the notification **and** is marking it as group summary. We cannot work-around it without risking to break other apps compatibility.

Further, even if we added a special handling for this app, its notifications would not be actionable on the pebble. As there are [some](https://github.com/vector-im/riot-android/issues/1947) [issues](https://github.com/vector-im/riot-android/issues/1016) asking to fix the notifications, I will close this. Notifications will start coming through as soon as the source app properly marks them.

**Closed by danielegobbetti** 2018-02-17 17:02 UTC
Labels: android integrations/notifications

**Comment by tradej** [comment] 2018-11-07 13:54
FYI version 0.31.0 fixes the behaviour—Riot notifications now appear on the device as expected.
