### ISSUE TITLE
Mi-1S not usable since last Gadgetbridge update

### ISSUE THREAD

**Issue by mr-sneezy** [Freeyourgadget/Gadgetbridge#330] opened 2016-06-15 08:43 UTC
Hi all, 
My Mi1S and the GB app was working quite well together until the 12th when I updated GB. Since that day I have no sleep or step data apart from just a few steps (76) on the 13-14th. It does report transferring data, but the time span is always only a few minutes long. It used to transfer days or hours depending on when I got around to it.
Other symptoms are repetitive Connection - Disconnections and repetive messages saying the band needs paring (with vibration from the Mi 1S). Repairing in the app or in Android setup does occur but is not permanent like it was previously.
I've rebooted the band via the GB Debug options, also fully charged it up, and unpaired and repaired in the Android (as above) a few times. 
Debug checks like heart rate test works as does vibration alert test. 
So summarising, I have had no sleep or workout data since the 12th, and will take any suggestions to try to debug this.
(GB version 0.10.1, FW: 4.16.3.7, HR:1.3.76.18)

**Comment by ralle12345** [comment] 2016-06-15 09:11
My Mi-1S works fine with the latest GB update with FW 4.15.12.10 / HR 1.3.74.64. I just downloaded the last 2 days with full step and sleep data.

**Comment by mr-sneezy** [comment] 2016-06-15 13:21
Hmm, thanks. Slightly different firmwar,e but sounds like GB is not the issue.
Any suggestions that I should try that I didn't cover above ?

**Comment by cpfeiffer** [comment] 2016-06-15 21:26
In my experience this unfortunately sounds like a broken band. We've had this a few times already, with slightly different symptoms, but it was always the activity tracking that didn't work anymore.

You can try the live activity (long press on device, open charts, swipe all the way to the right). I bet that one still counts steps correctly.

Is probably just the memory that is faulty.

**Comment by mr-sneezy** [comment] 2016-06-17 09:41
OK, this is the exception that breaks the rule. With no other suggestions coming I tried reverting back to the previous version of GB, that had some error issue so I reverted back one older. That installed fine and guess what, I now have overnight sleep data and daily steps data like it used to be. So the band is not faulty it seems. I did not reboot the band or do anything else to it.
I now have GB version 0.9.8 running. 
What should I do now ?
Try loading 0.10.1 again or wait for 0.10.2 and see if it breaks again ?

**Comment by cpfeiffer** [comment] 2016-06-17 18:18
Thanks for trying this! Would it be possible for you to install the latest version again, enable logging, perform a synchronization, and, if it is faulty again, share the log with us?

**Comment by mr-sneezy** [comment] 2016-06-19 00:22
Yes no problem I can do that. Before I do I was hoping to 'base line' the band with the older software, and there lays a problem. After two days of normal behaviour I now get times where the band wants to re-pair with the phone, and it does it about once a minute for a few minutes. Each time it seems to pair OK (four solid LEDs) and GB can get info. I note that once it's newly paired again there is no long term data in the device, steps and HR for the previous day are lost again. 
So, it's not just loosing data, it's dropping pairing, and maybe that in turn zeros the data storage ?
I turned logging on today, and it's done some more re-pairing since, is the log worth posting ?

**Comment by cpfeiffer** [comment] 2016-06-19 06:17
Exactly, when you pair the device by tapping it when it blinks, you lose all previous data that was on the band prior to the new pairing. I've never seen or heard of such behavior yet, but it doesn't look like a healthy band.

Maybe you can test the band with a different phone or tablet to see if that makes a difference?

If it turns out that the band is indeed broken, we might want to start collecting the behavior of broken bands in the wiki.

**Comment by cpfeiffer** [comment] 2016-06-19 06:23
We can try to use a lower speed for the activity data transfer. Maybe that makes a difference.

**Comment by danielegobbetti** [comment] 2016-06-19 10:05
Are you by chance using the new-ish "hours offset" settings? I'm thinking there may be issues with time going back and forth and older miband models...

**Comment by mr-sneezy** [comment] 2016-06-19 11:19
OK, so the repeated pairing might explain the data loss. I guess then what causes repeated pairing ?

I'm happy to try a custom build of GB if it may resolve anything.

I'm not using a time offset feature, I was not aware of it actually.

I had a quick look for the log file but did not see it on the phone storage. What is the file name and folder ?

I got a couple more re-pairing events this afternoon.

**Comment by ashimokawa** [comment] 2016-06-19 17:50
https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files

**Comment by mr-sneezy** [comment] 2016-06-20 11:13
Bugger, I hadn't restarted GB and there was no log file in the folder...
I'll run it another day (it's getting annoying with 're-pairing' requests).

Ok, tried to stop GB to restart it for logging. Quit via the apps own button and it seemed to work, but a check in Android - setup - apps - running showed something about GB still active, and no 'stop' button. Is that correct after 'quit' is done ?
![image](https://cloud.githubusercontent.com/assets/6261419/16192279/7b86a242-3727-11e6-925d-16dd07761ef4.png)

**Comment by cpfeiffer** [comment] 2016-06-20 21:56
It could be, yes. There are some notification receivers that are managed by android itself, so it may be that the os prevents our self-termination.

It was a pain to configure logging because you really had to force close Gadgetbridge before the changed settings were applied.

In current versions the settings are applied immediately without a restart.

**Comment by cpfeiffer** [comment] 2016-06-20 21:57
So before you wait another day, enable logging, force close and restart Gadgetbridge and verify that the logfile is created.

**Comment by mr-sneezy** [comment] 2016-06-21 13:23
OK,I did the force close (by phone reboot as force close was not available). 
Tested over night and today. Quite a few re-pairing events, lost all the overnight data, and even though the logging was on there are not logs in the GB folder...
As the the re-pairing buzzing has become really annoying I've uninstalled GB for now and will test the unit on the Mi Fit app for a couple of days, and report back.

PS. If any android process of the Mi Fit app was still running can that cause this behaviour in the band with GB ?

**Comment by cpfeiffer** [comment] 2016-06-21 14:12
Yes, you can't run both mifit and Gadgetbridge at the same time.

**Comment by mr-sneezy** [comment] 2016-06-22 08:11
OK that eliminates one possible issue. 
Got good news for me, with the OEM Mi Fit app the band has been working perfectly now for about 20 hours. I got over night sleep info and step info all day, no re-pair requests at all.
I was about the bin the band yesterday but I'll keep running it on MF for s few more days...

**Comment by cpfeiffer** [comment] 2016-06-22 22:54
I'm still interested in finding the cause for the problems, especially now that you day that it works fine with mifit.

It could also be that mifit did a firmware update that lead to a different behavior.

**Comment by mr-sneezy** [comment] 2016-06-23 08:46
Another 24 has passed with the band working perfectly with Mi Fit app, no re-pairing, and all data being recorded and transferred (other than HR which doesn't seem to get displayed by MF app AFAIK).

OK, suggest away. Load the latest GB up again ?

**Comment by cpfeiffer** [comment] 2016-06-23 20:40
We didn't change anything in that regard yet, so all you could verify if there was any problematic interaction between Mi Fit and Gadgetbridge.

Basically: 
- make sure that Mi Fit is not running, e.g. by force-closing it
- wait a while/overnight so that you get some activity/sleep data
- ensure that Mi Fit is still not running
- start Gadgetbridge
- In Gadgetbridge's Mi Band settings, check the option to keep activity data on the band
- Synchronize
- See the results
- Disconnect
- Start Mi Fit
- Synchronize
- Compare results with those from Gadgetbridge
- Report results here :-)

**Comment by mr-sneezy** [comment] 2016-06-24 10:53
OK. Had another trouble free day on MF here.
Will do you suggested list. I'll have to re-install Gadgetbridge in between step 3 and 4 as I removed it when I went back the Mi Fit. 
I've stopped Mi Fit this evening, so I should be able to do the testing tomorrow morning.

**Comment by cpfeiffer** [comment] 2016-06-24 12:38
Right. Unless you configure gb to connect when Bluetooth is turned on, it will not interfere with your band or mi fit, fwiw.

**Comment by mr-sneezy** [comment] 2016-06-24 14:06
I did have GB configured previously to connect when BT is on...
Is that the wrong thing to do in normal use of GB ?

**Comment by cpfeiffer** [comment] 2016-06-24 15:03
That's OK, but you probably shouldn't do this when you also run Mi Fit :-)

**Comment by mr-sneezy** [comment] 2016-06-24 23:26
OK, if MF was running it was not by my choice (after starting GB). Does that need to be documented ?

**Comment by mr-sneezy** [comment] 2016-06-24 23:32
Testing result 1.
I reinstalled GB latest version this morning, opened settings and ticked logging and keep data on band.
Checked other settings and did NOT tick Connect when Bluetooth Available or the Reconnect options.
Tried to connect to the band.
Issue right away. The device selecting box shows MI1S on the top line and  'connecting' forever on the one below...

At this time I'm going to do nothing and see how long it hangs on 'connecting', or wait for any instruction from you.

**Comment by mr-sneezy** [comment] 2016-06-24 23:45
It took about ten minutes before it connected, and only after it requested pairing again (and I tapped the band).
I refreshed data and we lost the overnight stuff, showed only two minutes, which was from about when it re-paired.

**Comment by cpfeiffer** [comment] 2016-06-25 00:59
The ten minutes are bad, this should not happen.

Repairing after using MiFit might indeed be expected, unless you configured the exact same user information (alias, age, height,...) both in GB and MiFit.

**Comment by cpfeiffer** [comment] 2016-06-25 01:01
I think the wiki states that you cannot use Gadgetbridge and MiFit at the same time.

**Comment by mr-sneezy** [comment] 2016-06-25 01:58
I assumed (probably like most people) that user information was stored and used by the apps rather than internally on the band. I didn't try make all user information the same on both apps (not knowing that it mattered at that time). These are not complaints, just how I interpreted things as presented to me.
Actually the ONLY reason I installed Mi Fit was to get the firmware up date on the band. After that I used GB because I hate manufacturer connected apps on personal devices.

I'll see if I can find the log file. Went does a log get created ?

**Comment by mr-sneezy** [comment] 2016-06-25 02:49
Log files.
I found one on the internal storage called mili_log.txt that seems to have a lot of band data, but it might be from the Mi Fit app. Is that of interest ?
Found your log in android data as well, ready to send it.

**Comment by mr-sneezy** [comment] 2016-06-25 02:51
[gadgetbridge - Copy.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/332877/gadgetbridge.-.Copy.txt)

**Comment by mr-sneezy** [comment] 2016-06-25 03:01
I looked at the other log. It seems to have data logged at the same time as GB log. This worries me as I killed (stopped) the MF app last night... 
Do you want the log, and can I PM it to you rather than drop it here, I'm not sure it's free of personal info like the GB log ?

**Comment by mr-sneezy** [comment] 2016-06-25 03:04
Also of interest (sorry to bomb you with possibly too much feedback) are to screen shots I took today that come from GB or the bands use
![screenshot_2016-06-25-11-54-16](https://cloud.githubusercontent.com/assets/6261419/16354379/1962ceee-3ad1-11e6-976e-333a30d5b40b.jpg)
![screenshot_2016-06-25-09-57-11](https://cloud.githubusercontent.com/assets/6261419/16354382/258ae5c6-3ad1-11e6-808d-3b7404dc6a4b.jpg)

.

**Comment by cpfeiffer** [comment] 2016-06-25 07:13
Just a quick answer before have to leave:
- you can do firmware updated with Gadgetbridge as well
- the band needs the user information to calculate the number of steps
- your Bluetooth process crashing happened after discovery?

**Comment by mr-sneezy** [comment] 2016-06-25 08:23
Re point 1 - Excellent, pity I missed that info, although may not have mattered now.
Point 2 - OK, that was not obvious to me, good to know it.
Point 3 - I think it was during discovery. 

Actually GB is failing to connect currently, tapping the device listed on main page gets 'connecting' then after some time 'not connected'. New (2nd) log attached
[gadgetbridge2nd.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/332988/gadgetbridge2nd.log.txt)

**Comment by mr-sneezy** [comment] 2016-06-26 13:58
GB didn't work today again. It would not connect when activated manually, responded after about 30 seconds with 'not connected'. One unusual thing was I got a vibrating SMS notification through when I received a friends SMS. If not connected I did not think that could occur.

Also, and maybe more sinister. Mi Fit is restarting by itself after some time. It was running again this morning, so I stopped it. Tonight in Settings-apps there it is running again...

**Comment by mr-sneezy** [comment] 2016-06-28 09:00
Continuing my monologue one last time. I ended up having to uninstall Mi Fit completely to stop it restarting by itself (possibly a security or privacy issue right there), After that I am not MF free and after restarting my phone and restarting Gadgetbridge it's back in action again with the band (which did not work until MF was gone).
So, seems to me GB is not the issue but interaction with MF or changes in MF might be.

**Comment by cpfeiffer** [comment] 2016-06-28 21:35
Hooray :-) Thanks for your investigations. I will update the wiki to recommend not having both installed at the same time. If there's anything left not working, please reopen this issue or create new ones.

**Closed by cpfeiffer** 2016-06-28 21:35 UTC
Labels: mi band
