### ISSUE TITLE
New devices

### ISSUE THREAD

**Issue by mariusv** [Freeyourgadget/Gadgetbridge#217] opened 2016-01-29 09:39 UTC
Heya,

Just want to start by saying that you are doing a great job here. Wanted to ask if there is any plan to support any other devices like fitbit for example especially the not yet released one fitbit blaze. Planing to get one if I would know Gadgetbridge would want to make it work with it. How could I help (don't have any programming skills besides scripting)?

**Comment by danielegobbetti** [comment] 2016-01-29 14:16
It's hard to answer to your question. Your best bet is trying to google for "<your desired device> bluetooth protocol" or "<your desired device> reverse engineering" and see if you find some results.

If you find something, than it may be that the available documentation is enough for a developer to add support for a new device, but I wouldn't bet on this: most probably the dev needs access to an actual device.

In any case I am closing this issue as it's a duplicate of #50, please continue the discussion there.

**Closed by danielegobbetti** 2016-01-29 14:16 UTC
Labels: duplicate
