### ISSUE TITLE
Mi Band 1S: GB & Mi Fit wipe data of band after update

### ISSUE THREAD

**Issue by bigretromike** [Freeyourgadget/Gadgetbridge#367] opened 2016-07-29 21:14 UTC
I install Mi Fit to be able to compare data. In GB I tick the "leave data" option so I can sync on both application.
When I enter GB it tells me to pair it (even when string say "connected" - bug maybe?) I double tap band and its connected, then I swipe to sync data and I get "Syncing 1minut..." or something along those words. Then I'm thinking its probably MF working in background, but when I enter MF and have to pair (double tab band) I get empty chars.

One thing I notice is that MF updated band: 
firmware: 4.16.4.22
heart rate: 1.3.76.22

Im currently not getting data in both applications

**Comment by cpfeiffer** [comment] 2016-07-31 21:01
The pairing is the application level pairing, i.e. the confirmation "yes, I want to use this device and agree to delete all previous data on it" (that's what the band does during that sort of pairing).

If you configure user data in gadgetbridge the same way as in Mi Fit, it might be that no re-pairing will be necessary. Otherwise, the option to keep the data is indeed not useful for syncing data both in GB and MiFit.

**Comment by cpfeiffer** [comment] 2016-07-31 21:02
I'm closing this as not a bug, as there is nothing we can do here.

**Closed by cpfeiffer** 2016-07-31 21:02 UTC
Labels: mi band

**Comment by bigretromike** [comment] 2016-08-01 05:25
But is it possible to make them both work without paring before getting data

**Comment by cpfeiffer** [comment] 2016-08-03 22:20
Well, that is a good point. I think I know the reason for this: the fix for #349 

Apparently you need to be paired for this to work. Can you check if your band is actually paired to your mobile? If it isn't can you manually pair it and try again?

**Comment by bigretromike** [comment] 2016-08-04 05:07
It is, as I see it in bt devices. Is there anyway you would like me to test it ?

**Comment by cpfeiffer** [comment] 2016-08-07 07:47
No, not yet. I'm just trying to find a way to fix both #349 and this issue, and so far I don't know how.

Apparently we need to perform the application level pairing in order to avoid re-bonding with Mi Fit, because that's what we disabled in #349. 

1. Some phones have no problems at all with application level pairing, for others it does not work at all.

2. Some phones have no problems with bonding phone and band, for others it does not work at all.

And, to make things work, the groups of 1) and 2) are not the same: some people can bond their devices, but still not perform the application level pairing.

I guess we need to make the application level pairing a configurable option.

**Comment by bigretromike** [comment] 2016-08-07 12:10
I had problem with bonding band with Mi Fit until I run GB, then magicly MiFit saw my band and I was able to pair those after 15minuts of fighting. Thank you for explaining what is the problem here.
