### ISSUE TITLE
Pebble: Gadgetbridge crashes when trying to install non existant pbw from pbw-cache on Firmware 3.x

### ISSUE THREAD

**Issue by glitchphan** [Freeyourgadget/Gadgetbridge#160] opened 2015-11-05 00:22 UTC
This may be because I have Dialer for Pebble installed, but the last two versions have been the worst for me. Any incoming or outgoing phone call makes Gadgetbridge crash. I have tried both with Phone Calls set to Never (my usual setting) as well as Always. I have not tried to uninstall Dialer for Pebble yet. I do have some logs but need to transfer them off my phone.

**Comment by ashimokawa** [comment] 2015-11-05 10:51
You can try to disable support for 3rd party pebble apps, then you don't have to uninstall Dialer for Pebble and report back.
Also logs are appreciated.
Do you mean that before the last "worst" versions it worked?

**Comment by ashimokawa** [comment] 2015-11-05 16:37
I just tried Dialer for Pebble and it worked fine with incoming calls. (outgoing not tested)
So... logs please ;)

**Comment by cpfeiffer** [comment] 2015-11-09 21:51
Maybe this comes from the change how the receivers are handled?

**Comment by ashimokawa** [comment] 2015-11-10 09:07
@cpfeiffer 
Could be the case. But can't reproduce and no logs provided.

**Comment by glitchphan** [comment] 2015-11-24 18:08
Sorry for my slackin response. Checking if attaching a file works.

**Comment by ashimokawa** [comment] 2015-11-24 18:53
OK judging from a quick look this is what happened

- you have a pebble time
- you use pebbledialer but didn't install the pbw through Gadgetbridge
- your pebble time ditched pebbledialer, because it only fakes unlimited app slot and behaves like that.
- a call came in and that made pebble dialer launch (the remaining stub in the pebble app db)
- the pebble asked for the pbw to be installed again
- Gadgetbridge tried to find the missing pbw in its pbw cache, but didn't find it, since you didn't install it through Gadgetbridge.
- my code failed because it is crap.

The original pebble time app just clears the database upon connect and populates it again with data of known apps. So it would delete what was installed from Gadgetbridge.

A quick fix would be to install the pebbledialer pbw again though Gadgetbridge.

But that would still make you loose the call, since installation takes too long.

(Typed from my phone)

**Comment by cpfeiffer** [comment] 2015-11-24 19:42
How about letting the user mark certain apps as "important" and let Gadgetbridge ensure they are installed  (upon connect, not when a call comes in).

**Comment by ashimokawa** [comment] 2015-11-24 19:58
@cpfeiffer 
That won't work.
On FW 3.x we cannot install apps. We can only install app metadata, the pbw will be requested by the watch on demand, with a token we need to do the actual installation. We cannot just force-install.

**Comment by cpfeiffer** [comment] 2015-11-24 20:37
So we need that Gadgetbridge watch app, that does this for us :-)

**Comment by glitchphan** [comment] 2015-11-24 20:41
How do you get the pbw without the official Pebble app?

**Comment by ashimokawa** [comment] 2015-11-24 21:28
@glitchphan 
I packaged the android app for f-droid:

https://f-droid.org/repository/browse/?fdfilter=pebbledialer&fdid=com.matejdro.pebbledialer

The description contains a link I found in the source code. So it is official.

**Comment by ashimokawa** [comment] 2015-11-24 21:29
@cpfeiffer 
I don't understand what you mean, but I am quite sure it won't work ;)

**Comment by glitchphan** [comment] 2015-11-24 21:31
Sorry, I never noticed it was right in the description!

**Comment by glitchphan** [comment] 2015-11-24 21:45
It said to open it on the watch, so I did, and it went through a progress bar and ended up with just a dot/small ball on the screen. If I back out by holding down back, I can get to the menu, but selecting Dialer just hangs. In the app manager, its name is a long number, by N/A. By the way, your "Installation was successful!" notification doesn't go away when you tap it. Also, when I delete the long number from the App Manager, it stays in there but gets removed from the watch.

**Comment by ashimokawa** [comment] 2015-11-24 22:32
@glitchphan 
See #93 for improvements on the app manager.
Really Firmware 3.x sucks, because the watch is no longer the master of its own apps, it is the Pebble Smartphone App. I cannot even ask which apps are installed on the watch! All this worked on Firmware 2.x.

You can try to install the pbw again, maybe there was some mismatch with old metadata or something.  I never tried "upgrading" apps on FW 3.x. 

I do not have a Pebble Time, and the Emulator sometimes behaves different and is really stripped down. Development was a pain. I guess I will do improvements in December when I get the 3.x beta for my OG Pebble.

**Comment by glitchphan** [comment] 2015-11-25 00:57
Thanks much for all your hard work, anyways.

I uninstalled everything, reinstalled official app, dialer for pebble was working. I uninstalled official app and installed gadgetbridge, but dialer would not finish loading (please wait, or something). Reinstalled dialer through f-droid just in case, no change. Updated dialer with pbw through GB, now it says Dialer Update Android App with a bit.ly link that takes me to that same dropbox url with the 2.52 pbw. Sheesh :)

**Comment by glitchphan** [comment] 2015-11-25 00:57
Forgot to mention, official app upgraded fw to 3.7.

**Comment by ashimokawa** [comment] 2015-11-25 08:10
@glitchphan 
I will update Pebble Dialer in f-droid also to 2.52
Might take a while, since f-droid needs to accept PRs manually.

**Comment by glitchphan** [comment] 2015-11-25 17:32
ok, I got the one from Play store and I think it's all working as it should right now! By the way, GB makes all the buttons in Music work with XiiaLive, while with the official app only Play and volume buttons work. Pause and skip/rev do not :).

**Comment by ashimokawa** [comment] 2015-12-06 16:58
Fixed in master, will be in 0.6.8

**Closed by ashimokawa** 2015-12-06 16:58 UTC
Labels: pebble
