### ISSUE TITLE
Sync weather to timeline on fw 3.x

### ISSUE THREAD

**Issue by shtrom** [Freeyourgadget/Gadgetbridge#798] opened 2017-09-06 04:02 UTC
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I have a Pebble Steep with firmware 3.x. I have Weather notification and the Gadgetbridge skin enabled, but the weather is not sync to the Pebble's timeline (like, for example, the sunrise and sunset are). Apparently the weather-to-app sync is only available for 4.x, but it would be good to have it for older watches' firmwares too (

#### Your wearable device is:
Pebble Steel, FW 3.12.3

#### Your android version is:
LineageOS 14, Android 7.1.2

#### Your Gadgetbridge version is:
0.20.2

**Comment by azuwis** [comment] 2017-10-11 05:38
Found a way to sync weather forecast to Pebble timeline https://www.reddit.com/r/pebble/comments/671pdd/how_to_get_weather_info_and_sunrise_sunset_times/

It works by subscribing a weather forecast calendar, than weather forecast will appear on Pebble timeline, since GB can sync calendar to timeline.

Pros: Works without additional apps, works on fw 3.x.
Cons: Google calendar only update external calendar once a day.

So another way to implement this is to sync weather forecast from Weather Notification to calendar, is it easier?

**Comment by danielegobbetti** [comment] 2017-10-11 09:52
nice find. I'm sure that if you grab the ``webcal:`` URL and replace the scheme with ``http:``, then you can use a local application from f-droid (like icsdroid) to subscribe to it.

**Comment by azuwis** [comment] 2017-10-11 13:26
@danielegobbetti Thanks for the info.

@shtrom You can try the combination(Gadgetbridge + Icsdroid + webcal from http://www.webcal.fi/), works well for me.

**Comment by danielegobbetti** [comment] 2017-10-17 13:15
Since the solution is confirmed working I'm closing this.

**Closed by danielegobbetti** 2017-10-17 13:15 UTC
Labels: device pebble
