### ISSUE TITLE
[Feature request] MDN battery api

### ISSUE THREAD

**Issue by aHcVolle** [Freeyourgadget/Gadgetbridge#773] opened 2017-08-21 13:36 UTC
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I'm the dev of the Watchface TrekVolle. 
I did switch from the official pebble app to GB when my watchface's weather requests where enabled in GB. Thanks for that btw.
One thing that's bugging me since the switch is the following:
I do request the phones battery status with the mdn battery api but the used functions aren't present in GB's javascript implementation.
I know this api is deprecated but I think it shouldn't be hard for the GB devs to implement an battery api similar to the one provided by mdn.

Here is the link to my implementation: https://github.com/aHcVolle/TrekVolle/blob/master/src/pkjs/battery.js
Here is the link to the mdn battery api: https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API

I'd do this on my own but i haven't even found where the JS part of GB is implemented nor would i want to taint GB with my crappy coding skills :)

#### Your wearable device is:
Pebble time 4.3
#### Your android version is:
7.1.2
#### Your Gadgetbridge version is:
0.19.4

**Comment by IzzySoft** [comment] 2017-08-21 14:09
Welcome first!

>  when my watchface's weather requests where enabled in GB.

My thanks as well (and yes, that was my suggestion). As I'm using your watchface: Now I know why I don't see the phone's battery level in it. Glad you're working on that!

**Comment by aHcVolle** [comment] 2017-08-21 16:08
> that was my suggestion

well, thanks for that, i didn't know about gadgetbridge before i was mentioned in an issue thread in here :)

**Comment by danielegobbetti** [comment] 2017-08-21 16:11
Hello and thanks for reaching out! If you are running a self compiled version of gadgetbridge I'd kindly ask you to try the background js branch. In master (and in released versions) the JavaScript component on the android side is only working while the configuration page is opened (better said: our own "gateway" to the configuration page itself).
To wrap it up: the issue is less implementing the api but having js running at all :-) I can't link to the background js branch and issue as I am from mobile, sorry.

**Comment by aHcVolle** [comment] 2017-08-21 16:19
Thanks for the reply.
i'm not running a self compiled version of GB so that's not an option right now.
So since "normal" GB isn't running JS in the background how is it able to react on weather requests?

**Comment by IzzySoft** [comment] 2017-08-21 16:25
> i didn't know about gadgetbridge before i was mentioned in an issue thread in here :)

[Really](https://github.com/aHcVolle/TrekVolle/issues/2#issuecomment-275636902)? Oh, right, [this one](https://github.com/Freeyourgadget/Gadgetbridge/issues/482#issuecomment-269873213) was earlier, but it didn't `@mention` you. Nevermind, the real and good thing is you found it :wink: Glad to see you here! `</OT>` ;)

**Comment by danielegobbetti** [comment] 2017-08-21 17:16
@aHcVolle see #482 for information about how we implemented weather for (very few and carefully selected ;-) ) watchfaces. I suspect things will just work on the branch, and if this is the case I'll close this issue. You can follow the progress of the background JS implementation in this issue: #467.

**Comment by ashimokawa** [comment] 2017-08-21 23:19
This can also be implemented in master in pure java in the AppMessage handler for TrekVolle, right?

**Comment by danielegobbetti** [comment] 2017-08-22 05:34
Yes but hopefully background js will become master soon enough :wink: :wink: ?!?

**Comment by aHcVolle** [comment] 2017-08-22 14:35
i just tried this with the background JS branch and it didn't work.
I didn't debug yet but just wanted to let you know that it's "not that easy" :(

**Comment by danielegobbetti** [comment] 2017-08-22 16:53
You beat me to it :) I also noticed the same. An info for you is that we set the webview to be debuggable, hnce you can use chrome://inspect to check its behavior.
Further, there is at least another watchface that (as far as I can tell) uses the same api and it's displaying the phone battery,). It's "multifit" and unfortunately is not open source.
I wanted to turn on debug in your app to see what's going on, but perhaps you'll beat me to it as well.

**Comment by ashimokawa** [comment] 2017-08-22 18:12
please uncomment in PebbleProtocol.java

 mAppMessageHandlers.put(UUID_TREKVOLLE, new AppMessageHandlerTrekVolle(UUID_TREKVOLLE, PebbleProtocol.this));

**Comment by ashimokawa** [comment] 2017-08-22 18:15
Okay I disabled it, just pull background-javascript branch, it is also up to date now

**Comment by aHcVolle** [comment] 2017-08-23 05:43
Wow, i just built it and it seems to be working fine. 
Lets see how it behaves through the day.
Thanks!

**Comment by danielegobbetti** [comment] 2017-08-23 07:15
@aHcVolle to complement @ashimokawa message: the handler (if present) prevents the watchapp to exchange messages with the webview, as it sits in the middle and intercepts messages.
The reason why the handler was uncommented in the branch was that I didn't test your watchface before and forgot to comment it :)

**Comment by aHcVolle** [comment] 2017-08-23 07:30
Ah ok thanks for the info.
The battery part seems to be working fine, but the configuration page doesn't seem to be working.... :)

**Comment by ashimokawa** [comment] 2017-08-23 07:54
IIRC there is a patch in master which enables clay to work in webview 60 which has not yet been backported, correct @danielegobbetti?

If so that could be the problem.

**Comment by danielegobbetti** [comment] 2017-08-23 19:16
Not really, that commit has been merged in the branch as well! Can you share logs? It works well here...

**Comment by ashimokawa** [comment] 2017-08-27 22:47
@aHcVolle 
With configuration page not working, do you mean the following:

The clay configuration openes, but after pressing the "save" button, the json displayed suddenly switches to NETWORK_STATUS:0 ?

@danielegobbetti 
Can you confirm?

**Comment by aHcVolle** [comment] 2017-08-28 06:09
No, the configuration page didn't show up at all, all i got was a blank screen.

**Comment by ashimokawa** [comment] 2017-08-28 19:53
@aHcVolle 
I also had the blank screen today. A general problem with the background_javascript branch seems to be that the webview dies after a while (for whatever reason), after that neither background js nor the clay page seem to work. I have to force close Gadgetbridge every time that happens.

**Comment by danielegobbetti** [comment] 2017-09-03 15:57
I pushed some fixes, please try again.

**Comment by danielegobbetti** [comment] 2017-09-05 14:54
please try force closing GB (swiping it away AND force closing from settings - app info). Sometimes when recompiling and reinstalling there are old ghosts giving trouble.

**Comment by cpfeiffer** [comment] 2017-09-29 21:08
Can we close this then?

**Closed** 2017-10-16 21:06 UTC
Labels: device pebble, potentially fixed / needs confirmation
