### ISSUE TITLE
Cannot install alongside Pebble app

### ISSUE THREAD

**Issue by krayon** [Freeyourgadget/Gadgetbridge#215] opened 2016-01-27 14:44 UTC
Trying to upgrade from v0.7.2 to v0.7.3 however it fails. logcat reports:
 ```W/PackageManager( 2223): Can't install because provider name com.getpebble.android.provider (in package nodomain.freeyourgadget.gadgetbridge) is already used by com.getpebble.android```

**Comment by danielegobbetti** [comment] 2016-01-27 17:00
Yes it was done to solve [multiple](https://github.com/Freeyourgadget/Gadgetbridge/issues/208) [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues/130), and we chose to become mutually exclusive with the legacy pebble app because it has been deprecated (AFAIK) after firmware 3.8 was released for the pebble classic and steel.

Long story short, I'm closing as a wontfix as this is expected behavior. You may think of upgrading to firmware 3.8 (at which point you can install the pebble time app, which is **NOT** conflicting with gadgetbridge).

**Closed by danielegobbetti** 2016-01-27 17:00 UTC
Labels: pebble, wontfix

**Comment by ashimokawa** [comment] 2016-01-27 17:31
If you really want you can compile Gadgetbridge yourself and remove the content provider from the manifest

**Comment by krayon** [comment] 2016-01-27 23:34
@danielegobbetti

Thanks for the explanation. I can't think of any reason to keep it around so I'll stick with GadgetBridge alone.

 @ashimokawa

If necessary I will indeed do this, thanks.
