### ISSUE TITLE
Not able to regect phone call on mi band 4

### ISSUE THREAD

**Issue by rulet** [Freeyourgadget/Gadgetbridge#1663] opened 2019-10-04 05:12 UTC
#### Before reporting a bug, please confirm the following:
- [ ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

### I got Gadgetbridge from:
* [x] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

If you got it from Google Play, please note [that version](https://github.com/TaaviE/Gadgetbridge) is unofficial and not supported here; it's also often quite outdated. Please switch to one of the above versions if you can.

#### Your issue is:
*If possible, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)! that might help identifying the problem.*

#### Your wearable device is:

*Please specify model and firmware version if possible*

#### Your Gadgetbridge version is:

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by IzzySoft** [comment] 2019-10-04 06:22
Without you filling in the details, I'm afraid we cannot help you. Hence I'm closing this now; will reopen once you've edited your post and filled the gaps (marked the relevant check-boxes, named your Android and Gadgetbridge version, etc.).

Possibly related: #1531

**Closed by IzzySoft** 2019-10-04 06:22 UTC

**Comment by rulet** [comment] 2019-10-06 10:22
I added some information, I already reinstalled rom -- bug still exists. So
what else do I have to add to the bug report?

пт, 4 окт. 2019 г. в 09:22, Izzy <notifications@github.com>:

**Comment by ashimokawa** [comment] 2019-10-06 10:44
It is a duplicate of #1531.
Rejecting calls is not possible on Android 9, see discussion in #1531

**Comment by rulet** [comment] 2019-10-06 10:51
No it's wrong, in Notify and Fitness app it works under Android 9.



вс, 6 окт. 2019 г. в 13:44, Andreas Shimokawa <notifications@github.com>:

**Comment by IzzySoft** [comment] 2019-10-06 11:16
It still remains a duplicate of what Andreas pointed to, so please check and continue there (I see you didn't check the boxes of having looked before, so you might have missed that). The two apps you've mentioned might have found a way to work around the Pie restrictions the Gadgetbridge team has not yet discovered – or you have them installed as privileged/system apps, maybe?

**Comment by rulet** [comment] 2019-10-06 11:18
No, not privileged/system apps.


вс, 6 окт. 2019 г. в 14:17, Izzy <notifications@github.com>:

**Comment by rulet** [comment] 2019-10-06 12:02
I just checked again, I have installed Notify and Fitness again, and
rejecting calls on mi band 4 works without problem.



вс, 6 окт. 2019 г. в 14:17, Izzy <notifications@github.com>:

**Comment by lakyljuk** [comment] 2019-11-14 21:07
I would like to note, that rejecting call is possible with Notify and Fitness and also with Master for Miband apps. No special privileges, both are installed from Google Play Store. So I think it should be possible to do it with GB. Any progress on this? If I press reject on band, it stops vibrating, but phone is still ringing.

**Comment by rulet** [comment] 2019-11-14 21:13
I'm using official Mi Fit app for now -- it works, I don't know about Gadgetbridge concerning rejecting calls for now.
