### ISSUE TITLE
Pebble sleep activity also display steps

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#260] opened 2016-03-22 05:53 UTC
In the Pebble graph about sleep  (2nd screen of 'my activity') I also see the steps (green bars).

**Comment by danielegobbetti** [comment] 2016-03-22 06:10
The bottom part shows the last 24 hours of samples (regardless of their type), but the pie chart should show only sleep (and only shallow sleep with pebble health, since we can't store deep sleep as it's being sent by the pebble). Can you confirm?

**Comment by roidelapluie** [comment] 2016-03-22 06:21
Well I do not sleep with my watch so I do not have sleep data. But indeed you are right. However we only see the legend for sleep.

**Comment by danielegobbetti** [comment] 2016-03-22 16:56
Closing this as duplicate of #45 .

**Closed** 2016-03-22 16:56 UTC
Labels: duplicate, enhancement
