### ISSUE TITLE
duplicate "last" message notification for each thread in "conversations"

### ISSUE THREAD

**Issue by chaseadam** [Freeyourgadget/Gadgetbridge#657] opened 2017-04-19 03:04 UTC
#### Your issue is:
If there are multiple "threads" or "conversations" with unread messages in the "Conversations" app and I receive a new message, gadgetbridge sends a new notification with the new messages in addition to duplicates of the newest unread message on any unread threads.

logs below show receiving 2 messages, but gadgetbridge sending 4 messages in two pulses. each pulse include the new message as well as the newest message from a different unread thread. Is this something to be fixed on the gadgetbridge side?
[conversations.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/931632/conversations.txt)

Not sure if I should push this back to Conversations, but I believe Conversations is doing the "right" thing by keeping a list of the "newest" unread messages. Maybe they are overly aggressive keeping the notifications up to date and are tearing them down and recreating them?

#### Your wearable device is:
Pebble Original
FW 3.12.3
hw 1_5

#### Your Gadgetbridge version is:
0.18.4 (fdroid)

**Comment by chaseadam** [comment] 2017-04-19 03:09
I can trigger this behavior when bringing conversations to the foreground as well, so this might be a conversations problem. anyone else experiencing this?

**Comment by chaseadam** [comment] 2017-04-19 03:23
filed: https://github.com/siacs/Conversations/issues/2450

**Comment by ashimokawa** [comment] 2017-04-19 13:02
I assume that this is "our bug".
I think android notification can't be updated, only removed and readded, that is why our code reacts like this to changes.

To fix it we would have more sophisticated tracking of notification contents (I guess) :disappointed:

**Comment by chaseadam** [comment] 2017-04-19 13:09
seems they can be "updated"

> It doesn't resend the notification it only updates them. It also doesn't set a notification sound or a vibration when these updates occur. gadgetbridge should probably able to figure this out and somehow deal with updates differently then with new notifications.

Conversations maintainer is open to adding extra information to the notification update if it will make it easier for gadgetbridge to handle

> If they want me to set an extra flag or something I can probably arrange that. But in principle i don't see anything wrong with updating notifications when something changes.

**Comment by chaseadam** [comment] 2017-04-19 13:15
Looks like updating a notification is related to re-using a notification ID.
https://developer.android.com/training/notify-user/managing.html

**Comment by IzzySoft** [comment] 2017-04-19 13:18
> I think android notification can't be updated

It can. Just give the second notification the very same title, AFAIR. I once encountered that when playing with some *Tasker* profile, where I sent notifications for a status: first, I gave the status in the title (e.g. "Status: OK", "Status: WARN") and got multiple notifications in the "tray". Then I switched that, making the title always just e.g. "Status" and put the details into the body. Result: only a single notification which got updated whenever I "sent a status update". [Reference from that experiment here](https://android.stackexchange.com/a/29449/16575).

**Comment by danielegobbetti** [comment] 2017-04-19 15:34
@chaseadam please post logs, there should be a mention of "Notification Flags", perhaps we can use something that is already provided (although I doubt it).

**Comment by chaseadam** [comment] 2017-04-19 19:00
@danielegobbetti I posted the logs I received from adb. Is there a more verbose log I can pull?

**Comment by danielegobbetti** [comment] 2017-04-19 20:41
Sorry I thought I edited my answer but the edit got lost somehow...

Anyway, if you could pinpoint the log entries that shouldn't have been notified (and the ones that should) we can perhaps identify a pattern within the existing flags.

**Comment by danielegobbetti** [comment] 2017-04-20 10:06
@chaseadam I must say that I cannot reproduce this issue with conversations and my XMPP contacts.

**BUT** when I have a pending notification (with text) and then I receive a multimedia message, then I get the last textual notification as new on my pebble. Can you perhaps test whether text vs image messages behave differently for you?

**Comment by danielegobbetti** [comment] 2017-04-28 16:11
Can you please test the notification-refactor branch? It should fix your problems.

**Comment by lazarosfs** [comment] 2017-08-03 07:01
I saw that too. The notification do come double, that is why gb sends them twice.
For example in whatsapp you get the first unread again, and a second that includes all other unread msgs in the extra lines intent header. In viber a bit different but again double. You also get a group summary.
I sovled it by keeping an array of apps-msgs of last 10 notif and not repeating them. I get the last msg from the one that has all of the conversations. I had to make changes to disectnotification() to ignore some and fetch the last only by splitting the extra lines, or the extra big text header for viber. I only fixed viber and whatsapp dont know what other chats do.
A history array that does not repeat msgs seems to be the best way..

**Comment by yaomtc** [comment] 2018-08-27 20:56
This happens to me with Signal, I tend to get a pair of notifications for the same message. They usually come through at pretty much the exact same time.

**Comment by selurvedu** [comment] 2018-10-12 18:02
Same here with Conversations and GB 0.30.0.

**Comment by danielegobbetti** [comment] 2018-10-31 20:53
Current master should fix this issue, please test if you can and send reports :-)
BTW, if everything works it should also add the notifications actions to the pebble notifications (see #705)!

**Comment by danielegobbetti** [comment] 2018-11-05 07:46
0.31 was tagged, contains the fixes and will be available soon. Closing.

**Closed by danielegobbetti** 2018-11-05 07:46 UTC
Labels: android integrations/notifications
