### ISSUE TITLE
Mi Band firmware images/upgrades

### ISSUE THREAD

**Issue by jtru** [Freeyourgadget/Gadgetbridge#169] opened 2015-11-19 19:05 UTC
For the lack of another support channel (like IRC), I hope it's OK to ask this question in here: The app's source code hints at its support for Mi Band firmware upgrades - is there a (semi) official source for those firmware image files?

I'd like to see if my Mi Band's problems (I have the hardware revision with only white LEDs and 45mAh battery, running firmware release 5.15.7.2) with Gadgetbridge can be fixed by upgrading the firmware, but can't use the official, Xiomai-provided app to do so, as the account registration just won't work for me.

**Comment by cpfeiffer** [comment] 2015-11-19 21:15
You can download the official app, unzip the apk and find the firmware in the assets/ directory. I suppose you need to use the Mili_1a.fw file, while users of the first Mi Band need to use the Mili.fw file. The newest Mi Band with the heart rate sensor supposedly uses the Mili_hr.fw file.

I don't know if anybody of with a Mi Band 1A was brave enough to do a firmware update with Gadgetbridge, yet. I personally only have the first version.

**Comment by cpfeiffer** [comment] 2015-11-19 21:17
Oh, btw, see #147

**Comment by cpfeiffer** [comment] 2015-11-19 21:21
So indeed firmware update is currently disabled for Mi Band 1A, because we don't have such a Band. 

But.. what are your actual problems, what do you want to fix with a new firmware?

**Comment by jtru** [comment] 2015-11-20 09:34
My Band with its current firmware release doesn't, for instance, support alarms set by Gadgetbridge at all - they just don't fire. When I researched the problem yesterday, a comment on another alternative app for using the Mi Band on Windows Phone devices hinted at this problem as being known, and that a firmware update to the latest release is supposed to fix that (and at least one other problem I don't remember right now, while also breaking the "Locate Device" feature). Unfortunately, I can't find that particular site/comment again right now; will have to check my browsing history in the evening to dig it up once more...

I'd be very willing to donate (the funds for buying) a Mi Band 1A if that helps you improving Gadgetbridge, by the way. Let me know how to, if you want to accept.

**Comment by cpfeiffer** [comment] 2015-11-22 17:23
1) Regarding Alarms: setting the alarms *does* work (you get a positive confirmation message), but they won't fire? That might indeed be a buggy firmware. I've added that info to https://github.com/Freeyourgadget/Gadgetbridge/wiki/MiBand-Firmwares-information, feel free to add more infos.

2) I've added another issue for updating the firmware on a Mi Band 1S (#173). And yes, sponsoring a Mi Band would help us implement and test this feature. Unfortunately the delivery time is several weeks, so it'll take a while.

It would surely help to collect all those firmware bugs and niggles so that people can install a firmware that supports all features *they specifically need*.

**Comment by jtru** [comment] 2015-11-24 09:02
1) Yes, that's exactly what happens - or not happens, depending on how you choose to look at it ;)

2) I got three identical bands I originally ordered (one for my personal use, one for playing around with another BLE device, and one intended as a gift). I could get the second one that I had bought to play around with into your hands fairly quickly, since you seem to be located in Germany. If you want, I'll ship it your way asap (just need your address first) - I assume the box having been opened is not a problem, is it? :)

Cheers!

**Comment by youlian** [comment] 2015-11-30 18:20
please unable flashing 1a. why?
because xiaomi firmwares and apps are abismal, mindbogglibgly so :(
my 1a was garbage out of the box. updated to latest firmware and app. so i asked around, somebody posted a guide to downgrading, the problem was that the guide was flawed. did not work...
so now i am stuck with 1a flashed to 1 and white leds stay on, and that kills battery very fast. 
so i am looking for a way to flash back 1a firmwares.

**Comment by cpfeiffer** [comment] 2015-11-30 22:59
Do the batteries stay on even after a notification (i.e. making the band blink)?

For the moment, we can't do much, because we do not have an 1A device yet.

**Comment by youlian** [comment] 2015-12-01 00:59
leds stay on forever, so blinking is kinda hard to notice, but it does blink. 
anyway, i got so annoyed by this xiaomi crappola that i just installed the whole android caboodle, removed all mi band fw checks and then removed the pebble support, because there is a bug in the "coordination" logic, making it possible mi band fw to be recognized as pebble fw, and just burned a random fw starting with 5 (for white leds). voila, back to xiaomi "normal" (which, frankly, to my standards, is far from normal). but at least battery hold now. thank you for your good work. this project rules.

**Comment by cpfeiffer** [comment] 2015-12-01 21:39
That's the spirit! Congratulation! :-)

The coordination bug should already be fixed in #177 by @ashimokawa.
So do I understand it right, that firmware upgrade of Mi Band 1A worked as soon as you removed the safety checks that prevented it? In other words, we can adjust the checks and close #173?

If you've got a spare minute, could you document your findings with model and firmware version to https://github.com/Freeyourgadget/Gadgetbridge/wiki/MiBand-Firmwares-information

In the long run, this shall help finding the best working model/firmware combination.

**Comment by ashimokawa** [comment] 2015-12-02 15:14
@cpfeiffer 
I am not sure if I fixed these errors also, maybe as a side effect, but not intentionally.

**Comment by cpfeiffer** [comment] 2015-12-02 16:49
@ashimokawa I understood that you fixed a case where a pebble was recognized as a mi band and here a mi band was recognized as a pebble. So I assumed a logic error in a certain situation, that you fixed.

**Comment by cpfeiffer** [comment] 2015-12-05 14:51
@jtru Thanks, I received your band and gonna ensure firmware upgrade will work! And I can confirm -- everything except alarms work well.

**Comment by cpfeiffer** [comment] 2015-12-07 20:58
Closing this issue, as upgrading firmware with Mi Band 1A works with Gadgetbridge 0.6.8. Just make sure to use a firmware that actually works (see https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Information)

**Closed by cpfeiffer** 2015-12-07 20:58 UTC
Labels: mi band, question
