### ISSUE TITLE
Blacklisted apps not remembered

### ISSUE THREAD

**Issue by gappleto97** [Freeyourgadget/Gadgetbridge#696] opened 2017-05-19 07:26 UTC
I keep needing to blacklist FDroid. Every time it downloads something it floods my Pebble Time with notifications. At one point it put my watch into recovery mode. Its particularly frustrating because it doesn't remember this setting persistently, when its set via the app OR the watch.

**Comment by ashimokawa** [comment] 2017-05-19 07:56
Are you on the latest Version?

**Comment by gappleto97** [comment] 2017-05-19 09:12
The latest one from FDroid, yes

**Comment by cpfeiffer** [comment] 2017-05-20 19:37
When are those settings lost? On reboot or also in between?

Do you do anything special like exporting/importing the database/preferences?

We had a similar issue in #664 which we couldn't reproduce nor explain.

**Comment by gappleto97** [comment] 2017-05-21 01:19
It seems to be on reboot, though it feels like it was just any time it sat more than a day.

**Comment by cpfeiffer** [comment] 2017-05-21 19:04
I added some log output for the next version. When you upgrade, please enable logging and share the log file (privately, if you want, since it may contain activity data, etc.).

You can also have a look at the logfile yourself of course and look for lines containing "blacklist".

**Comment by danielegobbetti** [comment] 2017-05-28 19:26
@cpfeiffer 
The problem lies in the recycling view. I was implementing #679 and saw the new logs. Working on it.

**Comment by gappleto97** [comment] 2017-07-23 07:53
Seems more stable lately. Still have problems if its shut down within a few hours of setting it, though.

**Comment by cpfeiffer** [comment] 2017-07-25 21:15
@gappleto97 please provide a log so that we can find out what's happening. None of us can reproduce this issue.

**Comment by gappleto97** [comment] 2017-07-31 03:44
[Before reboot](https://github.com/Freeyourgadget/Gadgetbridge/files/1186337/gadgetbridge-2017-07-29.0.log.txt)

[Post reboot](https://github.com/Freeyourgadget/Gadgetbridge/files/1186338/gadgetbridge.log.txt)

I didn't filter through this because I don't know what's relevant to you. The app that was not remembered in this instance was KDE Connect (org.kde.kdeconnect_tp)

**Comment by gappleto97** [comment] 2017-07-31 03:44
Sorry for the delay, but I had to find an app that reproduced.

**Comment by cpfeiffer** [comment] 2017-07-31 22:11
Thanks for the log, that helped! I hope it's fixed now for the next version.

**Closed** 2017-07-31 22:10 UTC
Labels: bug

**Comment by yaomtc** [comment] 2017-08-15 00:22
I've been having this issue for a long time with the email client K-9 Material from F-Droid. I have the latest versions from that repo. It's blacklisted, but notifications get through anyway, consistently.

**Comment by gappleto97** [comment] 2017-08-15 04:55
Can't speak for Google Play, but this patch is not yet on F-Droid. You're gonna have to wait on a new release for that.

**Comment by yaomtc** [comment] 2017-08-15 04:59
Ohh, okay. Thanks!
