### ISSUE TITLE
Increase the size of the installing res files for amazfit bip

### ISSUE THREAD

**Issue by ahsim** [Freeyourgadget/Gadgetbridge#1063] opened 2018-04-11 20:20 UTC
https://github.com/Freeyourgadget/Gadgetbridge/blob/29a05f1d8f8f2952688d7b60a748639c66793b77/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/amazfitbip/AmazfitBipFirmwareInfo.java#L133
Please change 500000 to 1000000 atleast.
in this line:
        if (bytes.length > 500000) { // dont know how to distinguish from Cor .res

**Comment by ashimokawa** [comment] 2018-04-12 06:32
What is the issue you face?

**Comment by ahsim** [comment] 2018-04-12 18:49
I was not able to install a custom res file whose size exceeds 500000 bytes. I changed it in your code for myself, but I want you to change this in your code.

**Comment by danielegobbetti** [comment] 2018-04-12 20:17
In order to ensure as few bricks as possible, people using released code should not flash ``custom`` res files. As long as the official res files are supported by the released app this is not a bug. 
Expert users / developers who know how to deal with custom res files should know how to self compile and install Gadgetbridge, hence I am closing this.

**Closed by danielegobbetti** 2018-04-12 20:17 UTC

**Comment by ahsim** [comment] 2018-04-18 13:38
danielegobbetti I think you don't test it. We install res files on Bips without any problems. Be more friendly)

**Comment by ashimokawa** [comment] 2018-04-19 14:47
@ahsim 
What is the biggest res file you have and why is it so big? Can you post a link? I would like to know what it is for and what you added to it.

**Comment by ahsim** [comment] 2018-04-23 20:04
http://myamazfit.ru/threads/big-menu-modificirovannye-res-ot-proshivki-santax-mod-0-1-1-29-dlja-amazfit-bip.213/post-3495
This is custom res file that I made. We create this res files for Amazfit Bip. And size of this res files more than 500kb. Many other programs can install this res files without any problem, but in your gadgetbridge you set this limitation. Please remove it. Nobody will recieve brick, be patient, developers of firmwares already did protections. So hope you understand me, if not contact me I will clarify.

**Comment by TaaviE** [comment] 2018-04-23 20:25
@ahsim 

But the thing is, if I or core maintainers release a version of the app that allows flashing random `.res` files, it's going to be GadgetBridge that's going to be blamed. If you can provide a method to detect if it's a Cor's `.res` or Bip's `.res` this limitation could possibly be reconsidered.
