### ISSUE TITLE
Amazfit band A1702

### ISSUE THREAD

**Issue by ArcTuruS02** [Freeyourgadget/Gadgetbridge#839] opened 2017-10-09 17:50 UTC
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Relese the support. Unable to connect (close to mi band 2)

#### Your wearable device is:

Amazfit band A1702. (Mili_tempo.fw & Mili_tempo.res in MiFit app.)

#### Your Gadgetbridge version is: 0.21.3

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by danielegobbetti** [comment] 2017-10-09 20:32
I marked this as device request, I hope I did not misunderstood the report.

**Comment by ArcTuruS02** [comment] 2017-10-10 03:11
Anielegobbetti, yes! Thx! It is new Huami band with ips screen with same commands as mi band-2.

**Comment by niclet** [comment] 2017-10-20 08:44
Got it yesterday. Hope to find good news here soon :)
Best regards.

**Comment by ashimokawa** [comment] 2017-10-23 09:31
@ArcTuruS02 
@niclet 
Can you compile and test master?
Firmware update support is still missing and everything is completely untested...

**Comment by niclet** [comment] 2017-10-23 10:16
Sure, I'll test it asap, probably tonight (Paris time)
Thanks a lot.

**Comment by ArcTuruS02** [comment] 2017-10-23 10:29
OK! I'll test. Thnx!

**Comment by ArcTuruS02** [comment] 2017-10-23 22:38
Hi! I build apk, but still there is no automatic connection.  In manual mode, it is also impossible to connect.
"Amazfit Band connecting..." but nothing further.
Nevertheless, thank you!

**Comment by niclet** [comment] 2017-10-24 03:15
Can't install APK. But I'm not very familiar with Android, so probably missed something while building.

**Comment by ashimokawa** [comment] 2017-10-24 05:58
@ArcTuruS02 
Please unpair in Android settings and press the + button in Gadgetbridge and pair though Gadgetbridge.

I got screenshots and photos of the device connected to Gadgetbridge from another user via e-mail and it works for him....

**Comment by ArcTuruS02** [comment] 2017-10-24 06:30
@ashimokawa 
Oh! Got it! Thnx! Conected after MiFit unpare

**Comment by niclet** [comment] 2017-10-24 06:41
Good news :)
Does it let translate into english or only avoid using MiFit app ?

**Comment by ArcTuruS02** [comment] 2017-10-24 06:49
@niclet No. Menu items are image files inside *.res file. It is for another topic/issue.

**Comment by ashimokawa** [comment] 2017-10-24 07:16
@niclet 
Gadgetbridge is meant for people that prefer free open source software and do not want to create a personal cloud account for their private data. Most of our users run f-droid instead of the play store. You are free to only use Gadgetbridge as a flasher tool to flash the firmware to a translated version and then go back to MiFit - but don't expect any MiFit support, we do not use it, in fact no one of our core team has ever seen it running in real life no has a MiFit account.

@ArcTuruS02 
Strings are in the firmware, menu text images are in the res. For the Bip everthing is there 3(!) times (Simplified Chinese, Traditional Chinese, English). As soon as there is an update for this band with English inside Gadgetbridge will switch it to English (as long as the phone is not set to Chinese). And rumors say Mifit switches it back to Chinese.

**Comment by niclet** [comment] 2017-10-24 07:25
OK.
Nice work by the way :)

**Comment by ArcTuruS02** [comment] 2017-10-24 08:41
Hope for firmware update realisation! Thnx!

**Comment by ArcTuruS02** [comment] 2017-10-24 08:51
We need to close this issue?

**Comment by ashimokawa** [comment] 2017-10-24 12:37
I will close this after firmware update support has been landed

**Comment by ashimokawa** [comment] 2017-11-02 14:17
I am closing this, since firmware update is implemented, however it is totally untested since we do not have this device.

**Closed by ashimokawa** 2017-11-02 14:17 UTC
Labels: device request

**Comment by ArcTuruS02** [comment] 2017-11-02 14:38
@ashimokawa 
Hi! Firmware update works? 🥇

**Comment by ashimokawa** [comment] 2017-11-02 15:22
Oh, did you also flash the res file? And if so, which version?
I am asking because the latest version uses a different res format and I don't know whether it needs special handling

**Comment by niclet** [comment] 2017-11-02 16:55
How did you get the firmware ? Are you sniffing network from official MiFit app ?

**Comment by ashimokawa** [comment] 2017-11-02 17:37
No, the firmware and res file is inside the mifit apk

**Comment by niclet** [comment] 2017-11-02 17:41
Ok thanks, I'll have a look at it. Regards.

**Comment by ashimokawa** [comment] 2017-11-02 18:01
Mifit 3.1.0 contains a known .res format. 3.1.2 a new one. I think the update in 3.1.0 will succeed. For 3.1.2 I am not sure.

**Comment by ArcTuruS02** [comment] 2017-11-02 19:24
"Element cannot be installed "
With *.res and *.fw

**Comment by ashimokawa** [comment] 2017-11-02 20:18
@ArcTuruS02 
Which version of Gadgetbridge (you need 0.22.0 minimum)?

Which .fw and .res did you chose?

**Comment by ArcTuruS02** [comment] 2017-11-02 21:33
V 0.22.1./// 
Tempo. from 3.1.0 & 3.1.2

**Comment by ashimokawa** [comment] 2017-11-03 00:11
@ArcTuruS02 
Indeed there was a copy and paste error. Master should be okay now. Please try 0.22.2 when it is ready or build master yourself.

**Comment by ArcTuruS02** [comment] 2017-11-03 10:05
Now it works fine!!! Thnx! Thnx! Thnx!

**Comment by ashimokawa** [comment] 2017-11-03 13:23
@ArcTuruS02
Which version of res did you flash?

**Comment by ArcTuruS02** [comment] 2017-11-03 16:08
@ashimokawa 
red - from 3.1.0
Fw - from 3.0.6

**Comment by ashimokawa** [comment] 2017-11-03 17:38
@ArcTuruS02
Is there a reason for flashing the fw from another version than res?

**Comment by ArcTuruS02** [comment] 2017-11-03 18:01
@ashimokawa 
No. 
I mean that *.res  is available for flashing only from MiFit 3.1.0 to 3.1.2
But *.fw - from 3.0.6 to 3.1.2

**Comment by ashimokawa** [comment] 2017-11-03 21:44
@ArcTuruS02 

>  I mean that *.res is available for flashing only from MiFit 3.1.0 to 3.1.2

What do you mean? .res files for tempo were also in older versions

Also did you try to flash the .res of 3.1.2 (it has a new format)

**Comment by ArcTuruS02** [comment] 2017-11-03 22:06
@ashimokawa 
1.  Yes. From 3.0.0    ///https://www.apkmirror.com/apk/xiaomi-technology/mi-fit////
2.  Yes. I flash *fw from 3.1.2. It's OK! But *res has a new format.
P.s. I think it has also *ft file inside the band or something similar, coz I corrupted fonts by flashing in Notify app

**Comment by ashimokawa** [comment] 2017-11-03 22:49
@ArcTuruS02 

2. I know That res has a new format, did you flash it anyway? If so what happend?

I also know that .ft files are flashable on all devices, but there is no .ft file for Amazfit Band or Bip, so you are out of luck unless they release such a file. This is also the reason why wo do not allow to flash .ft files on Bip and Amazfit Band - because there is no way to fix it.

**Comment by ArcTuruS02** [comment] 2017-11-03 22:57
@ashimokawa 
2. Flashing *res from 3.1.2 leads to mistake... something about metadata... after that I downgrade *fw and flash all by MiFit
Hope *ft will be inside MiFit after international release :)

**Comment by ashimokawa** [comment] 2017-11-04 22:09
@ArcTuruS02 
When you tried to flash the .res from 3.1.2, did you upgrade the firmware before to the one in 3.1.2? It could be neccessary for the firmware to understand the new res format...

**Comment by ArcTuruS02** [comment] 2017-11-05 05:02
@ashimokawa 
Yes. I upgraded the .fw before .res (MiFit works exactly in this sequence)

**Comment by ashimokawa** [comment] 2017-11-05 10:03
If you are really brave and agree to do this on your own risk, can you try to edit HuamiFirwareType.java and change

    RES((byte) 2),

to

    RES((byte) 130),

before flashing the 3.1.2 .res

**Comment by ArcTuruS02** [comment] 2017-11-05 10:50
OK. I'll try

**Comment by ArcTuruS02** [comment] 2017-11-06 05:31
@ashimokawa 
OK! Flashing fine!

**Comment by ashimokawa** [comment] 2017-11-06 06:29
@ArcTuruS02 
Thanks!
I have properly updated master so that old and new .res files work.

**Comment by Jad0886** [comment] 2017-11-06 21:27
@ArcTuruS02
Hello
I have the same problem with my band after update by notify. I m novice with all of your manipulation. Can you explain me step by step? Currently i have problem with fonts. Only ____??__ on my band screen. Thanks a lot

**Comment by ashimokawa** [comment] 2017-11-06 22:31
@Jad0886 
You won't be able to fix the fonts, there is no font file for anything else than Mi Band 2, I have no idea why you guys flash that (Gadgetbridge does not allow that on purpose).

The .res file only contains images - no fonts. To flash the current .res file you need to compile Gadgetbridge master yourself or wait for the next release. But again - it won't fix you fonts. Your only hope is that Xiaomi/Huami releases an updated font file, then I will enable flashing support for that.

**Comment by Jad0886** [comment] 2017-11-07 17:06
@ashimokawa

Belo w the message from @ArcTuruS02
Yes. From 3.0.0Yes. I flash *fw from 3.1.2. It's OK! But *res has a new format.
P.s. I think it has also *ft file inside the band or something similar, coz I corrupted fonts by flashing in Notify app
Si i have the same problem. Crash with notify update

**Comment by Jad0886** [comment] 2017-11-08 16:12
Up!

**Comment by ashimokawa** [comment] 2017-11-08 16:39
What? I have said eveything , just read my last post

**Comment by Jad0886** [comment] 2017-11-08 20:16
I read it thanks. But i saw that @ArcTuruS02 has problem with fonts. So i want To speak with him To know if the problem is solved And if yes, how.
 If i understand weel no way To sent fonts file To the band. Nothing je write on my band when i have notification. Sad... Have a good day.

**Comment by Lombo88** [comment] 2018-02-23 07:28
@Jad0886
I have the sole problem. Do you have fix It? If yes, how?

**Comment by Lombo88** [comment] 2018-02-23 07:30
*same problem

**Comment by ashimokawa** [comment] 2018-02-27 14:10
@Lombo88 
There are no Cor fonts available for flashing. The Mi Band 2 fonts are not compatible and the Bip fonts that were recently released are untested...

We do not allow to flash fonts to the Cor on purpose, so that people don't break their band. IF you are willing to possibly brick your band even  further and are willing to compile Gadgetbridge yourself and try flashing the Bip font, I can give you instructions.

**Comment by Next55** [comment] 2018-03-10 11:41
@ashimokawa 
 I have the same problem with the font on my Cor but I will test to flash and test the  Bip fonts.
**I know is my own risk!**
Can you give me the instructions to flash the Bip font...?

**Comment by Lombo88** [comment] 2018-03-10 17:53
It doesn't fix the problem because bip fonts is not compatible with core. The new version of Mi Fit app fixes the problem for me. Download it from apk mirror.

**Comment by Next55** [comment] 2018-03-10 18:16
@Lombo88
Okay, thank you. I will test ist! :)

**Comment by Next55** [comment] 2018-03-10 18:18
Have you used Mi Fit 3.3.2.1?

**Comment by ashimokawa** [comment] 2018-03-11 10:29
@Next55 
Did Mi Fit Fix  the problem?
If so I wonder how. Do they reflash fonts?
